### ISSUE TITLE
Double-click on "Add Label" causes problems

### ISSUE THREAD

**Issue by stuarteberg** [ilastik/ilastik#1002]
Normally, if the user clicks the "Add Label" button, the shape of the prediction slot changes (the number of channels increases by 1).  GUIs such as the batch export applet notice that the slot metadata has changed, and they update themselves accordingly in `setupLayers()`.

But if the user adds two labels very quickly (i.e. by double-clicking the "Add Label" button), somehow the batch data export applet "misses" the second notification.  I have no idea why this is happening.

Steps to reproduce:
- New project, add data, select features
- In training, double-click the "add label" button
- Add a file to the BATCH input list.
- Open the BATCH export applet.  Notice that the number of prediction layers is not right.

**Comment by k-dominik** [comment]
Hmm, I don't think there is a batch data export applet anymore. In any case I have tried to reproduce this issue but it seems to properly register added layers everywhere I could think to check.
