### ISSUE TITLE
IndexError in Batch Prediction input selection

### ISSUE THREAD

**Issue by kushal124** [ilastik/ilastik#1009]
When deleting some of the already added inputs in Batch Prediction input selections, it throws an IndexError : list index out of range
![screenshot from 2014-09-25 11 28 32](https://cloud.githubusercontent.com/assets/871398/4402318/b2567ec6-4496-11e4-8c4c-298557c2d198.png)

**Comment by stuarteberg** [comment]
It looks like error was fixed on the iiboost branch via ccaab138470c4e5f4afed1bf1a0d305572078ad3, so I just cherry-picked it over to master: 54021a1afebc227f880da548d27e22ced828692b.

**Comment by stuarteberg** [comment]
Whoops, that was a different `IndexError`.  This one is still a problem, and quite easy to reproduce.

**Comment by stuarteberg** [comment]
Duplicate of #1037.
