### ISSUE TITLE
inconsistent prediction preview (Live update off)

### ISSUE THREAD

**Issue by nkrasows** [ilastik/ilastik#1012]
In Pixel classification when Live update is turned off one can still see the probabilities in the places that have been computed before. When labeling (Live update still off) some tiles are removed while others are not affected by the labels on them and stay visible.

**Comment by stuarteberg** [comment]
I'm not able to reproduce this behavior, at least not easily.  It is almost certainly related to caching.  @nkrasows, do you recall how big your dataset was when you encountered this?  Also, what do you mean by "some tiles are removed"?
