### ISSUE TITLE
Tracking / object count classification

### ISSUE THREAD

**Issue by FredHamprecht** [ilastik/ilastik#1015]
The predictions displayed are nonsensical until at least one false detection has been labeled as such. 
That is, when labeling only "1" and "2" objects, all are predicted as "false detections" (in red color). Presumably the color table counts from the first available class, which in this case is "1", not "false detections".

**Comment by stuarteberg** [comment]
The two issues helpfully referenced above by @martinsch have been closed by now, and the behavior described here has been fixed as a result.
