### ISSUE TITLE
Export settings: Select directory dialog should open up in {dataset_dir}

### ISSUE THREAD

**Issue by martinsch** [ilastik/ilastik#1035]
... it currently opens in $HOME on my Ubuntu.

**Comment by agarwalayush** [comment]
It doesn't exactly opens in $HOME. It opens in the director from which you call the `./run_ilastik.h` .
But if you don't press `select` it saves in the `{dataset_dir}` . I am working on this issue.

**Comment by stuarteberg** [comment]
Duplicate of #920
