### ISSUE TITLE
Loading a Segmentation Image (2D+c: xyc) ...

### ISSUE THREAD

**Issue by ilastikdev** [ilastik/ilastik#1042]
... into an Object Classification workflow does not show the segmentation layer automatically.
Clicking on the Raw Image tab and again on the Segmentation Image tab
or
unclicking the Raw Image view layer
does show the segmentation image, so the segmentation image is loaded.

**Comment by akreshuk** [comment]
Works for me now, re-open if it doesn't work anyone else.
