### ISSUE TITLE
Headless issues with the Mac binary

### ISSUE THREAD

**Issue by akreshuk** [ilastik/ilastik#1046]
One of the users reports the following for running headless pixel classification in Mac binary 1.1.3:
- monkey_patches can not be  imported, used to work fine in 1.1.2
- lots of scary, but irrelevant error messages about other workflows which can't be imported in version 1.1.2
- warning about inefficient 3D access also for (X, Y, 1) data

**Comment by stuarteberg** [comment]
`ilastik/monkey_patches.py` was removed in 508c8450aee14d975a0fd2e52acb12d1526e25db.
