### ISSUE TITLE
OSX: drag and drop into data import disables keyboard input if axes change is required

### ISSUE THREAD

**Issue by chaubold** [ilastik/ilastik#1055]
Scenario: import a 3D dataset without axistags (I tried with a multipage tiff) into any tracking workflow by drag and drop into the dataset list, an error message pops up: "the data cannot be used like that for tracking", one clicks "OK" and wants to change the axes, but keyboard input does not work in the dataset-settings dialog!
It works fine if the data is imported by clicking on Add New->Add separate images...

OSX 10.9, ilastik v1.1.3

**Comment by k-dominik** [comment]
can't reproduce this in ilastik `1.4.0b27` using the helmstaedter stack (multipage tiff) on osx `12.4`
