### ISSUE TITLE
OSX Retinadisplay: Laggy GUI

### ISSUE THREAD

**Issue by JensNRAD** [ilastik/ilastik#1056]
Using ilastik (e.g. PixelClassification) on a Mac with Retinadisplay results in laggy updates during scribbling and laggy updates of the labels. Tested on OSX 10.9 (Mavericks). When reproducing the problem on @chaubold's machine, we found that the problem is gone if an external display with lower resolution is connected. It might be a problem of Qt 4.8.x.

**Comment by k-dominik** [comment]
we don't observe this kind of slowness on our macs.
