### ISSUE TITLE
Assigning no Labels for a class during labeling results in its obliteration

### ISSUE THREAD

**Issue by JensNRAD** [ilastik/ilastik#1057]
To reproduce the problem:
1. Create a new PixelClassification project with three label-classes (named 'Label 1' [red], 'Label 2' [green] and 'Label 3' [yellow])
2. Assign labels only for class 'Label 2' and 'Label 3'. After pressing `Live update` we obtain a segmentation only containing *green* and *yellow* regions.
3. Save the project and close ilastik.
4. Load the project. All three labels are still present. However, after pressing `Live update` we obtain a segmentation in *red* and *green*! However, the labels are still shown in *green* and *yellow*. Exporting the segmentation results in a file containing only 1 and 2 as values. Thus, the true class `Label 1`  disappeared and for the other classes `Label N` became `Label N-1`. 

(Assigning only `Label 1` and `Label 3` in step 2 results in deletion of the true class `Label 2` and `Label 3` becomes `Label 2` in the final output.)

**Comment by stuarteberg** [comment]
Two out of the three issues mentioned in this thread are now resolved.  As for the third:

>possibly related: in pixel classification, define three classes. Colors appear as red, green, yellow. Train a little. Now delete classes in the order 2, 1, 3. Recreate three classes. Color ordering is now different. 

I don't consider this a bug.  When the user deletes a label class, that color is "recycled" back into the order of label class colors, so it will be used again the next time "add label" is pressed.  The new color order depends on the order in which the colors were "recycled".  This might be a surprise to the user, but it won't lead to any incorrect results.  Given that we allow the user to change the class colors as she sees fit, I don't think it's worth coming up with more complicated logic to "resolve" this issue.
