### ISSUE TITLE
Incomplete documentation

### ISSUE THREAD

**Issue by akreshuk** [ilastik/ilastik#1058]
- [ ] conservation tracking uses screen shots from the old automatic tracking
- [ ] export options are not in the table of contents and thus not findable easily
- [ ] export of slots other than prob maps should be mentioned
- [x] headless object classification not documented at all

**Comment by k-dominik** [comment]
I'm closing this - @akreshuk I think we worked on the documentation a lot in 2019, some of it might still be outdated, but then let's get to more specific issues in https://github.com/ilastik/ilastik.github.io
