### ISSUE TITLE
Multi-page tiff files are not supported

### ISSUE THREAD

**Issue by thorbenk** [ilastik/ilastik#106]
When selecting Input data -> Import Stack Files it lists .tiff as a supported file extension, but when I select a multi-page tiff stack ilastik tries to load it as a HDF5 file.

Either the supported file extension list should be changed or (ideally) multi-page tiff suport be added.

**Comment by tom-f-oconnell** [comment]
This error message still seems to be in place, but the rest of the GUI seems to have changed, so I don't see an "Add File" button. It seems the error text should be changed to "Add New...->Add separate image(s)..." or something, but that said, I wasn't able to load a multipage TIFF that way, so has this support been dropped?

In case there are differences in the GUI, I'm using the latest (1.3.2post1) Linux version.

Conversion through HDF5 as described here...
https://www.ilastik.org/documentation/basics/common_problems
...did ultimately work for me, but multipage tiff support would still be nice.
