### ISSUE TITLE
Feature Selection

### ISSUE THREAD

**Issue by ilastikdev** [ilastik/ilastik#1064]
Returning to Selecting Features (adding or removing a feature) after selecting them initially and running a workflow triggers an error on exit from the Feature Selection Dialog box.

**Comment by FredHamprecht** [comment]
This issue still is very annoying -- it essentially makes it impossible to change the set of features after a first classification attempt. 

Could someone please look into it before next release?

**Comment by akreshuk** [comment]
This issue has been fixed by @stuarteberg in ilastik/lazyflow@2ae01c35ed7e00667d4e0a13e0e030bf53bbe404
