### ISSUE TITLE
Export to multipage tiff with the data type uint16 (or other conversion) - result is empty

### ISSUE THREAD

**Issue by irudi** [ilastik/ilastik#1068]
Exporting probabilities without pixel type conversion (=float32) is working fine. But if I enable the conversion to int16 or uint16 the resulting tiff is empty (all planes are black). But the structure of the resulting tiff (channels, planes) is as expected.

**Comment by stuarteberg** [comment]
When floating-point data is converted to integer data, no scaling is performed by default.  All values between 0.0 and 0.99999999 will be truncated to 0.

When exporting probabilities, be sure to check the "Renormalize [min,max] from: to:" checkbox, which will cause the data to be scaled to a new range during the conversion.  (See screenshot below.)
![screen shot 2015-01-08 at 11 41 42 am](https://cloud.githubusercontent.com/assets/1655821/5666124/5a384ed0-972b-11e4-9e94-fbe79134fea3.png)

**Comment by irudi** [comment]
Ahhhhh - thanks! It's working. :+1:
