### ISSUE TITLE
Tiling bug in probability export of object classification batch mode

### ISSUE THREAD

**Issue by christophdecker** [ilastik/ilastik#1088]
I got strange results in post-processing so I looked at the exported HDF5 files in detail and found a significant bug: Comparing the object prediction probabilities exported from the export applet versus the batch mode, in the latter the objects were cut/split at the tile boundaries and different probabilities were exported for those different parts of an object.

Example:
![screenshot from 2015-03-03 09 48 40](https://cloud.githubusercontent.com/assets/2794524/6459121/bb57d5a2-c18b-11e4-8bbc-6cbef6864ed0.png)
![screenshot from 2015-03-03 09 49 06](https://cloud.githubusercontent.com/assets/2794524/6459122/bb798b98-c18b-11e4-8cfa-de258c67f1bb.png)

**Comment by akreshuk** [comment]
This is not a tiling bug, it's a consequence of blockwise processing 
with insufficient halo. Try going to the Blockwise applet and finding 
the values for the blocksize and halo such that no object is split in 
the results.

**Comment by christophdecker** [comment]
Thanks for the hint, I'll try increasing this now. I was just wondering because I got different results in batch mode and normal export although the halo and block size were quite large compared to the objects. Do you think it will cause problems if I set the block size to the actual frame size to process a TXY data set frame by frame?

**Comment by stuarteberg** [comment]
>Do you think it will cause problems if I set the block size to the actual frame size to process a TXY data set frame by frame?

No, that should be fine.
