### ISSUE TITLE
tracking: Allow gurobi as an alternative to cplex

### ISSUE THREAD

**Issue by stuarteberg** [ilastik/ilastik#1094]
@chaubold  says using Gurobi for automated tracking is 8x slower than CPLEX (last time he checked), but it would still be a nice option for users, since it's easier to get a license for it.  This is especially true for ilastik workshops.

There are two possible ways to add support for both within pgmlink:
- Somehow build pgmlink to support either library, and load whichever one is available at run-time.
- Build pgmlink twice (with two different names) and then choose the one to load in python

In today's meeting, @chaubold was leaning toward the latter.

**Comment by chaubold** [comment]
Thanks for fixing that thought. Using Gurobi in pgmlink is already in pgmlink's master, see https://github.com/martinsch/pgmlink/commit/cdea616cb1e27c4c96d0328c16b52eb12ecf970e and following commits.

**Comment by akreshuk** [comment]
Possible now, there is even a dropdown menu to select a solver.
