### ISSUE TITLE
MessageServer contains cycle and __del__()

### ISSUE THREAD

**Issue by stuarteberg** [ilastik/ilastik#1096]
If a class implements the Python `__del__` method, we must be careful to [never][1] include it in any object cycles:

>Circular references which are garbage are detected when the option cycle detector is enabled (it’s on by default), but can only be cleaned up if there are no Python-level __del__() methods involved.

[1]: https://docs.python.org/2/reference/datamodel.html#object.__del__

The `MessageServer` class violates this rule.  For example:

- `parent` points to `self` points to `parent`
- `parent` points to `self` points to `self.server` points to `parent`.)

Somehow this needs to be fixed, or the MessageServer will never be garbage collected.

**Comment by nielsbuwen** [comment]
Are you referring to  ilastik.shell.gui.messageServer.MessageServer:178 ?
This is the old MessageServer. I will remove it.

**Comment by stuarteberg** [comment]
Ah, yes.  Even better.  Thanks!
