### ISSUE TITLE
Blockwise object classification: Applying new block size takes too long

### ISSUE THREAD

**Issue by christophdecker** [ilastik/ilastik#1099]
After changing the block size and halo in the "Blockwise Object Classification" applet and clicking "Apply" it takes several hours until you can continue. As the problem appeared with a txy dataset of dimensions 1800x1024x1024, I figure it might be due to ilastik computing the result with the new block size for all time frames instead of only the one currently displayed.

**Comment by stuarteberg** [comment]
Can you try the profiler to see where the slowdown resides?

1. Install the `yappi` module from PyPI.
2. Load a smaller dataset (but one that still exhibits at least some delay).  Be sure to use debug mode.
3. Select menu item: Debug > Profiling > Start
4. Reproduce the issue you described (click "Apply").
5. Debug > Profiling > Stop
6. Debug > Profiling > Save Sorted Stats... (I would guess 'cumulative' or 'time' may be the most informative.)

**Comment by burgerdev** [comment]
You are correct, the preview is in fact computing all time frames at once. There are a couple of lines in `OpBlockwiseObjectClassification` that seem to be using odd / invalid cache block shapes, but the following did the trick for me:

```diff
diff --git a/ilastik/applets/blockwiseObjectClassification/opBlockwiseObjectClassification.py b/ilastik/applets/blockwiseObjectClassification/opBlockwiseObjectClassification.py
index 5f156c6..754135d 100644
--- a/ilastik/applets/blockwiseObjectClassification/opBlockwiseObjectClassification.py
+++ b/ilastik/applets/blockwiseObjectClassification/opBlockwiseObjectClassification.py
@@ -429,7 +429,7 @@ class OpBlockwiseObjectClassification( Operator ):
             elif k == 'c':
                 shape[i] = 1
             elif k == 't':
-                shape[i] = self.RawImage.meta.shape[i]
+                shape[i] = 1
             else:
                 assert False,  "Unknown axis key: '{}'".format( k )
```

@stuarteberg: Perhaps it would be worthwhile taking a closer look at this operator again.

**Comment by stuarteberg** [comment]
Nice find, @burgerdev.  I don't think there is a good reason to make the blocks span across all time slices.  Your fix seems exactly correct to me.
