### ISSUE TITLE
Exporting simple segmentations results in blocky output

### ISSUE THREAD

**Issue by ljschumacher** [ilastik/ilastik#1103]
When doing a simple segmentation, the result looks OK in ilastik, but the exported image files are blocky and have an effectively lower resolution.

Using the default settings in "Prediction Export" for "Simple Segmentation", in ilastik 1.1.5 on Mac OS X 10.10.2
![xx_simple segmentation_00](https://cloud.githubusercontent.com/assets/3407568/7012532/c3b907dc-dca9-11e4-9e19-2b1e4bfc53c9.jpg)

**Comment by stuarteberg** [comment]
Strange.  Would you mind uploading the input image you're using?  And maybe a screenshot of the "preview" of your results that look OK?  Also, if you can provide the full project file, that might help.

**Comment by ljschumacher** [comment]
I will have to check with collaborators if I can provide the original image, but here is a screenshot of the preview in ilastik
![ilastik_simplesegmentation_preview](https://cloud.githubusercontent.com/assets/3407568/7012992/9a5f0c02-dcad-11e4-9c21-5d0a4b7cb443.png)

**Comment by stuarteberg** [comment]
Thanks for the screenshot.  Can you also send a screenshot of the export settings window?

**Comment by Div44** [comment]
Experienced the same bug in ilastik 1.1.5 on Windows 8.1.

**Comment by ljschumacher** [comment]
Here is a screenshot of the export settings window
![screen shot 2015-04-07 at 12 27 17](https://cloud.githubusercontent.com/assets/3407568/7022245/9bf35040-dd21-11e4-92d4-cf60cba00f9b.png)

**Comment by stuarteberg** [comment]
OK, here's the problem: The "simple segmentation" output produces a label (index) image. In this case, every pixel has a value of either 1 or 2.  Apparently JPEG compression doesn't handle that very well.  (I can reproduce this behavior on my machine, too.)  Try exporting to a format that doesn't use lossy compression (e.g. png).

As a side note: label images are useful if you plan to post-process these images in another piece of software, but if you want images that are more easily viewed in "ordinary" image browsers, you could consider changing the range of pixel values in the image by checking the "Renormalize" checkbox.  In this case, the appropriate range of values would be "from 0-2 to 0-255".

**Comment by ljschumacher** [comment]
Thanks, I did mean to post-process the images, but I didn't realise the issue with compression.
