### ISSUE TITLE
Exception from "window leveling" widget

### ISSUE THREAD

**Issue by stuarteberg** [ilastik/ilastik#1106]
A user reported the following error to the `ilastik-user` mailing list:

>I got a few errors with Ilastik 1.1.5 when trying to use the window leveling. With a left click and dragging the mouse left, I often get

```
ERROR 2015-04-15 16:50:24,173 excepthooks 1284 11644 Unhandled exception in thread: 'TileProvider-11644'
ERROR 2015-04-15 16:50:24,173 excepthooks 1284 11644 Traceback (most recent call last):
  File "C:\Program Files\ilastik-1.1.5\ilastik\volumina\volumina\tiling.py", line 90, in _render
    img = self.image_req.wait()
  File "C:\Program Files\ilastik-1.1.5\ilastik\volumina\volumina\pixelpipeline\imagesources.py", line 149, in wait
    return self.toImage()
  File "C:\Program Files\ilastik-1.1.5\ilastik\volumina\volumina\pixelpipeline\imagesources.py", line 193, in toImage
    vigra.colors.gray2qimage_ARGB32Premultiplied(a, byte_view(img), n)
RuntimeError:

Precondition violation!
gray2qimage_ARGB32Premultiplied(): normalize[0] < normalize[1] is required.
(c:\install_vc11\src\vigra-HEAD\vigranumpy\src\core\colors.cxx:384)
```

**Comment by ukoethe** [comment]
This message probably indicates that the lower and upper bound of the normalization parameter `n` are equal, which would subsequently cause a division by zero. This may, for example, happen if the image to be normalized has constant graylevel. Can we verify that this is indeed the case? Then the simplest fix is to set `n = (lowerbound, lowerbound+eps)` for some positive epsilon.

**Comment by bethac07** [comment]
Any word on a fix for this?  I checked the closed bugs but didn't see anything.  Still happening in 1.1.9 Thanks!

**Comment by stuarteberg** [comment]
We can look into this if it's causing you trouble.

1. What OS are you using?
2. Can you provide us with a sample image that can be used to reproduce the error?
3. If there are any special steps to reproduce the error, let us know.

**Comment by javaworms** [comment]
I'm having the same issue. Interestingly, it only happens on my background-subtracted image stacks; the original images don't produce any errors. I am using linux. An example image stack can be found at:

https://www.dropbox.com/s/qgya57oo0o3ff0w/Cherryimg120.tif?dl=0

Just trying to change the window level in the Training section should be sufficient to reproduce the problem.

**Comment by stuarteberg** [comment]
Thanks for the example image.

The issue here is that the above-mentioned `n` variable consists of two signed numbers, e.g. `(-218.36, 3556.89)`, but it is casted to unsigned, e.g. `[65318, 3556]`, on [this line](https://github.com/ilastik/volumina/blob/8b8cfb6f01431ace118cfa82483955ecee94f813/volumina/pixelpipeline/imagesources.py#L188).  The bad cast causes `n[0] > n[1]`. Oops.

Apparently the reason we perform that cast is that vigra's [`pythonGray2QImage_ARGB32Premultiplied` function](https://github.com/ukoethe/vigra/blob/9b168d1b53c144833ccb1a5bbeb13d3ebbe55c6a/vigranumpy/src/core/colors.cxx#L368-L371) expects `normalize` to be of the same type as the input array.  As far as I can tell, there's no need for that.  It should just accept `float` instead.

What do you think, @ukoethe?

**Comment by javaworms** [comment]
Any updates on this? It's quite annoying to work around it at the moment.

**Comment by stuarteberg** [comment]
Sorry for the delay.  I've just submitted ukoethe/vigra#382, which should fix this issue, once it is merged and we update our vigra dependency.  Hopefully this can be resolved next week.
