### ISSUE TITLE
Only default features are exported

### ISSUE THREAD

**Issue by akreshuk** [ilastik/ilastik#1107]
A user reported the following bug in the new object export functionality (1.1.5 binary):

The feature to export the statistics data does work, but not fully. In my hands I can only export the essential parameters. Even if the boxes of the other parameters are checked using 'all features', only the essential features are being stored. This is the case for both the HDF5 and the CSV format. In the project, all features are being selected, both in Object feature selection as in Object Classification. For the rest the files which are generated are fine.

**Comment by stuarteberg** [comment]
@nielsbuwen fixed this today via cefaf2746acb43c866c425707220fb4cb72d84ad.
