### ISSUE TITLE
huge memory consumption during training, ignoring the RAM limit

### ISSUE THREAD

**Issue by timoMa** [ilastik/ilastik#1129]
I am running the current version of ilastik (pulled today).
When I try running ilastik.py with (--headless) --retrain --project=myProject (which is admittedly huge, 9-channel with 1000^3 pixel) the memory consumption keeps growing until it fills almost the complete ram + swap (about 500Gb) even though the RAM limit is set to 100Gb.

Does the RAM limit only apply during prediction?

**Comment by stuarteberg** [comment]
Are you attempting to limit the RAM via the `LAZYFLOW_TOTAL_RAM_MB` environment variable? (Or equivalently, via the `[lazyflow]/total_ram_mb` config setting in `.ilastikrc`?)

>Does the RAM limit only apply during prediction?

It is used in both training and prediction, but the mechanism for limiting RAM usage is different in each case.  During training, the main RAM usage typically comes from the feature caches.  During prediction in headless mode, no caches are used.  The result is computed in blocks, and the blocks are chosen to be smaller than your available RAM.

In your project, how many features are you using?

**Comment by timoMa** [comment]
> Are you attempting to limit the RAM via the LAZYFLOW_TOTAL_RAM_MB environment variable? (Or equivalently, via the [lazyflow]/total_ram_mb config setting in .ilastikrc?)

Exactly! I get the message
INFO ilastik_main: Configuring lazyflow RAM limit to 100000 MB
so I assume it works.

> In your project, how many features are you using?

Currently I am using all of the standard Ilastik features (about 40 I think).

**Comment by timoMa** [comment]
There is also an error message that is probably related:

ERROR 2015-07-15 18:06:02,048 log_exception 27405 139636718774016 Traceback (most recent call last):
  File "~/bin/src/lazyflow/lazyflow/operators/cacheMemoryManager.py", line 252, in _cleanup
    cleanupFun()
  File "~/bin/src/lazyflow/lazyflow/operators/opUnblockedArrayCache.py", line 182, in freeBlock
    block = self._block_data[key]
KeyError: ((0, 0, 256, 128, 0), (1, 256, 512, 160, 333))

It shows up after the RAM limit is well exceeded (maybe a factor 1.5-2) and is repeated several times with the same key.

**Comment by burgerdev** [comment]
The error message you are seeing is a bug in cache cleanup, fixed in #186 (not in master yet). What's good about this: once this bug is fixed, the caches should be cleaned up. What's bad: as @stuarteberg suggested, headless mode should run without caches! Which workflow are you using?

**Comment by timoMa** [comment]
cool thanks for the heads-up! 
> What's bad: as @stuarteberg suggested, headless mode should run without caches! Which workflow are you using?

Hm thats strange... I am using the pixel classification workflow.

**Comment by timoMa** [comment]
> The error message you are seeing is a bug in cache cleanup, fixed in ilastik/lazyflow#186 (not in master yet).

merging your pull request solved the problem! Thank you!

**Comment by burgerdev** [comment]
Solved everything, or just the error message?

**Comment by timoMa** [comment]
It solved the problem of running out of RAM during retraining. The limit is not kept perfectly, however it is only exceeded by about 20% in contrast to over 200% before. This solves the problem for me.

**Comment by stuarteberg** [comment]
>What's bad: as @stuarteberg suggested, headless mode should run without caches!

Now I see what I missed before -- headless *prediction* uses no caches.  But there's no special cacheless path for training, and @timoMa was using the `--retrain` flag in headless mode.  So the caches are indeed used.

>>The error message you are seeing is a bug in cache cleanup, fixed in ilastik/lazyflow#186 (not in master yet).

>merging your pull request solved the problem! Thank you!

I've merged ilastik/lazyflow#186 to master now, so I'm closing this issue.
