### ISSUE TITLE
Preprocessing step in the Carving workflow gives error

### ISSUE THREAD

**Issue by vladimirg** [ilastik/ilastik#1155]
OS: Mac OS X 10.11 (El Capitan)
Ilastik version: 1.1.6

Steps to reproduce:
1. Open a Carving project.
2. Add the attached .png file as input data (avg_hek...).
3. In the preprocessing step, select "dark lines".
4. Press "Run".

An error appears, attached as the "error screenshot" below. This works fine in 1.1.5.

![avg_hek_f0002_w0000-first](https://cloud.githubusercontent.com/assets/1148887/10367823/39acd3ca-6ddb-11e5-88a2-d184c5d2e41e.png)

<img width="654" alt="error screenshot" src="https://cloud.githubusercontent.com/assets/1148887/10367856/6571f3fa-6ddb-11e5-9eea-b2a9be89dfac.png">

**Comment by stuarteberg** [comment]
Thanks for the report.

Guys, I think we may have broken support for 2D carving in the 1.1.6 release (when we switched out the carving backend).  Should we fix it, or should we officially drop 2D support?

**Comment by chaubold** [comment]
How much work would it be to also support 2D? What are the use cases in 2D?

**Comment by stuarteberg** [comment]
>How much work would it be to also support 2D?

@DerThorsten is the best person to answer this

>What are the use cases in 2D?

I guess people sometimes need to segment 2D images... I know we (ilastik devs) don't deal with 2D data very often, but I guess Carving is faster than manual painting in many cases, even in 2D.

**Comment by FredHamprecht** [comment]
Assuming that it should not be too much work to recover that 
functionality, I would be happy to keep it. I have had uses for this in 
the past (important work on medieval maps;-)

**Comment by DerThorsten** [comment]
It is almost fixed.
With a little help from @stuarteberg It can be done within the next days.
Only the volumen rendering needs to be disabled if 2d.
In "watershed_segmentor" the changes are about 4 lines of code.

**Comment by stuarteberg** [comment]
@vladimirg, This has been fixed in the master branch, so 2D carving will work again in our next release (1.1.8).  If you want to try a development snapshot that includes the fix, you can download this Mac binary, hot off the press:
http://files.ilastik.org/ilastik-master-OSX.zip

**Comment by vladimirg** [comment]
@stuarteberg , great, thank you!
