### ISSUE TITLE
windows installer of 1.1.7: setup splash screen looks a little funny 

### ISSUE THREAD

**Issue by FredHamprecht** [ilastik/ilastik#1156]
possibly because I have set default font sizes to "large": 

![installer-screenshot](https://cloud.githubusercontent.com/assets/899006/10510260/395cf3bc-7332-11e5-8308-7d27d3909a23.jpg)

**Comment by ukoethe** [comment]
Fixed by https://github.com/ilastik/ilastik-build-conda/commit/609d237a3d60262f4ce07a8e4dd0915c5e936b76 (hopefully).
