### ISSUE TITLE
Error while loading/saving Raw Image in Ilastik 1.1.5

### ISSUE THREAD

**Issue by AnnaGallis** [ilastik/ilastik#1158]
Hello everyone,
since yesterday afternoon I'm having a big problem with Ilastik: it cannot load my videos anymore in the Pixel Classification workflow, so I cannot proceed with segmentation or tracking. Attached you have a screenshot of the error message I get.

I can open old projects normally and modify them, but I cannot upload new images in new/old projects. Even if I try to load old videos that I have already analyzed (videos that have worked before), they will not open.

I will try to see if the problem persists with new versions of Ilastik (I doubt it, because more people would have noticed), but I'm limited to Ilastik 1.1.5 for tracking (for not too long, I hope) due to arrangements in my university.

Thank you for you help and have a great weekend!

AG
![error with ilastik](https://cloud.githubusercontent.com/assets/14805382/10694483/ad26184c-799e-11e5-8d42-38cc5d95b65b.png)

**Comment by stuarteberg** [comment]
Hi Anna,

>Attached you have a screenshot of the error message I get.

Can you send me (or attach here) a copy of your error log?  It is named `.ilastik_log.txt`, located in your home directory.

>I will try to see if the problem persists with new versions of Ilastik

Indeed, if you're able to give v1.1.7 a try, it would be very helpful.

-Stuart

**Comment by AnnaGallis** [comment]
Hello Stuart!

Thank you for your fast response. I'll be sending you the text file by e-mail to your @iwr.uni-heidelberg.de account, because somehow I cannot attach the file here.

I have tried with v1.1.7 and I don't have the problem at all, with exactly the same videos. Today I have a meeting with the Image processing people in the university, so I can try to convince them to install the latest version in the common computers (the only ones with CPLEX) and hopefully that's it.

All the best,

AG

**Comment by stuarteberg** [comment]
Hi Irene,

Thanks for the log file.  Glad to hear that v1.1.7 doesn't exhibit this error.  Since this issue has been fixed in the latest code base, I guess there's nothing else to do.  Good luck getting v1.1.7 installed on all of your computers.

BTW, the procedure for configuring ilastik to use CPLEX has been simplified somewhat with a new script.  Details are on the website: http://ilastik.org/documentation/basics/installation.html#linux-and-mac

-Stuart
