### ISSUE TITLE
Wildcards for cutout subregion in headless mode

### ISSUE THREAD

**Issue by emii** [ilastik/ilastik#1159]
When batch processing images in headless mode, one can indicate to export only a subset of the input data. If for a given image I would like to export only the prediction map for one class, I can indicate this accordingly with a the `--cutout_subregion` option. However, as images might vary in size (i.e. in the xy dimensions), the cutout subregion should vary accordingly to fit the given shape, thus, it requires to know and indicate the image dimensions beforehand and change this for every image.

Are there currently any wildcards analogous to the filename placeholders, or full range indicators to indicate this in the `--cutout_subregion` option?

e.g.

 Instead of:

`--cutout_subregion="[(0,0,0,0,0), (1,100,200,20,3)]"`

Something like:

`--cutout_subregion="[(1,x_start,y_start,z_start,2), (1,x_end,y_end,20,t_end)]"`

**Comment by stuarteberg** [comment]
>Are there currently any wildcards analogous to the filename placeholders, or full range indicators to indicate this in the --cutout_subregion option?

Yes, there is, but it's hard to guess.  Use the word `None` (with capital `N`):

    --cutout_subregion="[(None, None,1), (None, None,2)]"

**Comment by emii** [comment]
Great! and indeed not easy to guess. It might be worth to include them in the documentation. Thanks

**Comment by FredHamprecht** [comment]
Hello emi i.,

> It might be worth to include them
> in the documentation.

absolutely!

Would you like to make this your first contribution to this open source 
project?

Best regards,

Fred

**Comment by stuarteberg** [comment]
FWIW, this is the section of the docs to edit:
https://github.com/ilastik/ilastik.github.io/blob/master/documentation/pixelclassification/headless.md#output-options

**Comment by emii** [comment]
>Would you like to make this your first contribution to this open source
project?

Yes! My pull was requested already.

Just for completeness in this post, worth mentioning that ranges can also be declared as one side bounded. In a similar fashion:

`--cutout_subregion="[(None, 1,None), (None, None,2)]"`
