### ISSUE TITLE
manual tracking local variable reference error

### ISSUE THREAD

**Issue by danielmug** [ilastik/ilastik#1169]
I get an exception when starting manual tracking in ilastik 1.1.8:
(I confirmed this issue on another machine. Does anybody have a solution / does anybody face the same problem?)

*ERROR 2015-12-23 11:18:42,431 log_exception 5488 5732 Could not load project file.*
*Could not create instance of '<class 'ilastik.workflows.tracking.manual.manualTrackingWorkflow.ManualTrackingWorkflow'>'
args   = (<ilastik.shell.gui.ilastikShell.IlastikShell object at 0x000000000D6AE
0D8>, False, [], [])*
*kwargs = {}*
*The exception was:*
*local variable 'default_export_filename' referenced before assignment*
*Traceback:*
*Traceback (most recent call last):*
*File "C:\Program Files\ilastik-1.1.8\ilastik-meta\lazyflow\lazyflow\operator.py", line 107, in __call__
    instance = ABCMeta.__call__(cls, *args, **kwargs)*
*File "C:\Program Files\ilastik-1.1.8\ilastik-meta\ilastik\ilastik\workflows\tracking\manual\manualTrackingWorkflow.py", line 69, in __init__
self.dataExportApplet = TrackingBaseDataExportApplet(self, "Tracking Result
Export")*
*File "C:\Program Files\ilastik-1.1.8\ilastik-meta\ilastik\ilastik\applets\trac
king\base\trackingBaseDataExportApplet.py", line 35, in __init__
self._default_export_filename = default_export_filename*
*UnboundLocalError: local variable 'default_export_filename' referenced before assignment*

**Comment by chaubold** [comment]
Yes we are aware of this issue and fixed it in our master branch, so it will be fixed in version 1.1.9.
You could manually apply the code change of this commit in your local file to get a working version right now: https://github.com/ilastik/ilastik/commit/da8f641a99dc28f4f2ed88e81f16f1e77998475a
