### ISSUE TITLE
Prediction Export generates only black images

### ISSUE THREAD

**Issue by rtcx** [ilastik/ilastik#1174]
Hello, everyone!!!

I've been trying to export 'simple segmentation' images from Pixel Classification workflow, but no matter how I choose the export settings, the only thing I've got untill now is an image in black. Do I have to pre-process my images before performing its segmentation through Ilastik? How can I fix this?

Thanks in advance

**Comment by stuarteberg** [comment]
Hi, the "Simple Segmentation" export option produces a "label image" in which each pixel has a value of 1,2,3, etc. (depending on how many label classes you defined).  When viewed in a standard image viewer, these pixels will be so dark that the image will appear to be entirely black.

To view these images, you'll have to post-process them, or use a viewer that knows how to display such label images.

If you only need to process a small number of images, you can also try the "what you see is what you get" export mode.  On the training page, click on the camera button in the corner of the screen.  The images produced with that button will be in full color, just as they would appear on your screen.  (Make sure that "live update" is activated when you perform the export!)  Unfortunately, there is no way for you to use "what you see is what you get" mode from the command line or in batch processing mode.

**Comment by rtcx** [comment]
Thanks for your quick reply stuarteberg. But as you said, the problem is actually the number of images I have to analyze, over one hundred, for which the batch mode would be really helpful, even more with the learning machine-based segmentation processing from Ilastik. Would it be possible to 'select' those labels you've mentioned that are of my interest by using ImageJ or FIJI? I tried the split channels tool, but it didn't help anyway.

**Comment by ilastikdev** [comment]
Hi,

As mentioned by Stuart, the best way would be to post process your images:
re-scale the pixel values according to the max label you use, for example,
use a function that maps
(0,max_label) ---> (0,255) for a grey scale image output
and you will be able to see all your labels with any viewer.

Janez




"
Hi, the "Simple Segmentation" export option produces a "label image"  
in which each pixel has a value of 1,2,3, etc. (depending on how many  
label classes you defined). When viewed in a standard image viewer,  
these pixels will be so dark that the image will appear to be entirely  
black.

To view these images, you'll have to post-process them, ...

"


Quoting rtcx <notifications@github.com>:

**Comment by rtcx** [comment]
Hi, ilastikdev. Thanks for the help. But I'm still not sure about how I can re-scale the pixel values as you pointed. Do you recommend any software that runs this kind of pixel re-scaling? Is it possible to do this in batch mode?

**Comment by ilastikdev** [comment]
Hi,

Typically you would write a script in python or matlab.
You can loop over all the image files in your chosen directory and
while copying the files pixel per pixel you apply a transformation,  
for example:

pixel_new = 255*(float)(pixel_old - min_label)/(max_label-min_label)

In your case you have min_label = 0 and you can get max_label with a  
max() command on an image array.

Hope this helps,

Janez.




Quoting rtcx <notifications@github.com>:

**Comment by rtcx** [comment]
Hi again,

I have another issue concerning the segmentation of both images below. As you can see, there is a huge difference in background intensities among them, although they were acquired by confocal microscopy under the same parameters (it might be a problem of the staining protocol or antibody specificity). What I'm trying to quantify is the intensities of the brighter spots, those you can barely see in the second image, even though the signals are still there. Ilastik itself seems not to be able to transpose differences like that. So, any of you know how to reliably detect those spots instead of using thresholding tools, or a way to equalize the signal/background ratio for every image?

Thank you


![tu 261 cd31-488_ko-sti1 414 3_z0_ch00](https://cloud.githubusercontent.com/assets/16688365/12436601/e0139c94-befd-11e5-82b2-3a3c7abc6446.jpg)
![tu 261 cd31-488_tga 66 3_z0_ch00](https://cloud.githubusercontent.com/assets/16688365/12436602/e015424c-befd-11e5-9a61-51ee81524860.jpg)
