### ISSUE TITLE
AssertionError exporting 5-channel hdf5

### ISSUE THREAD

**Issue by dlogan** [ilastik/ilastik#1183]
I am trying to export 5-layer probability maps for multi-spectral data similar to that in #1176 (using Mac build which loads it fine).  The h5 file gets exported with these settings
![image](https://cloud.githubusercontent.com/assets/1225595/12785647/6f417ffe-ca5b-11e5-9202-34f60b50817a.png)
but this error dialog appears
![image](https://cloud.githubusercontent.com/assets/1225595/12785668/8afe8e8a-ca5b-11e5-9129-b3e063db105f.png)
and the log says (repeated 5 times, presumably for each output channel):
```
...
ERROR 2016-02-03 09:44:26,893 excepthooks 12178 140735236535040 Unhandled exception in thread: 'MainThread'
ERROR 2016-02-03 09:44:26,894 excepthooks 12178 140735236535040 Traceback (most recent call last):
  File "/Applications/ilastik-1.1.8-OSX.app/Contents/ilastik-release/ilastik-meta/volumina/volumina/widgets/dataExportOptionsDlg.py", line 183, in _handleRoiChange
    tagged_output_shape = opDataExport.ImageToExport.meta.getTaggedShape()
  File "/Applications/ilastik-1.1.8-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/metaDict.py", line 141, in getTaggedShape
    assert self.axistags is not None
AssertionError 
```
The h5 file looks ok when I view it, but the error dialog is annoying. Thanks!

**Comment by stuarteberg** [comment]
Thanks for the bug report.  Will be fixed in the next release, later this month.  If you'd like a pre-release binary for Mac or Linux, I can cook one up for you.

**Comment by dlogan** [comment]
Thanks for the quick update @stuarteberg .  A Mac binary would be useful to me, thanks!
