### ISSUE TITLE
Installed ilastik but cant load pictures, available file type is only ilastik project 

### ISSUE THREAD

**Issue by iopss** [ilastik/ilastik#1190]
Hi, 

I don't know if I have done anything wrong during installation. I just downloaded the package for linux, extracted it and ran the included run_ilastik script. I get to the start page, but when trying to make a new project, the only supported file type to upload is ilastik projects, that I do not yet have...
I tried going through the documentation, but it just says that it should support most common image files.
I am running it on a machine with ubuntu 12.04 64-bit.
Any help is appreciated.
Thanks

**Comment by akreshuk** [comment]
Hi there,
When you make a new project, you have to click the project type on the startup screen (for example, the first one, Pixel Classification). It would then ask you for the file name and create an empty project. The first applet you see, the data input applet, should allow you to load most common image files. Is that not the case? There is also a "Browse" option on the startup screen, but this is indeed only for existing projects. To start a new one, click the project type.

**Comment by akreshuk** [comment]
I assume this is resolved, please re-open if you are still having problems.
