### ISSUE TITLE
Merge labels

### ISSUE THREAD

**Issue by akreshuk** [ilastik/ilastik#1196]
Sometimes users define more classes than ilastik can find in the data. In that case, they'd like to merge the two labels rather than delete one of them and redo its annotations in another color.

**Comment by stuarteberg** [comment]
Is this for object classification or pixel classification?  For pixel classification, just right-click the label list (in non-live-update mode) and click e.g. "Merge Label 2 into Label 1"

**Comment by akreshuk** [comment]
That's for pixel, I didn't realize it was in already :) Thanks!

P.S. I replied via e-mail right away, but for some reason github is not posting my reply here.

**Comment by chaubold** [comment]
Using the 1.1.9 rc3 on Linux, merging labels (I had 5, went to 4) actually merged the WRONG labels. Is it possible there is some index swap in there?

**Comment by stuarteberg** [comment]
Thanks for the bug report, Carsten.  Somehow I managed to commit a garbage line in 0a413b15559b47acb21c7702526e46c204e4d0fe, after the merge feature was originally implemented and tested.  Now fixed!
