### ISSUE TITLE
Stack across c should be an option too

### ISSUE THREAD

**Issue by akreshuk** [ilastik/ilastik#1202]
We have those helpful radio buttons below the stack file selection. We should also make it possible to stack by channel.

**Comment by stuarteberg** [comment]
There are two separate operators that are used for reading stacks and copying them into the project file:

- For TIFF files: [`OpTiffSequenceReader`](https://github.com/ilastik/lazyflow/blob/master/lazyflow/operators/ioOperators/opTiffSequenceReader.py#L11)
- For all other formats (png, jpeg, etc.): [`OpStackLoader`](https://github.com/ilastik/lazyflow/blob/master/lazyflow/operators/ioOperators/ioOperators.py#L41)

Both of them have a slot for `SequenceAxis`, but at the `OpStackLoader` [doesn't currently allow](https://github.com/ilastik/lazyflow/blob/master/lazyflow/operators/ioOperators/ioOperators.py#L98) `c` for that value.  (`OpTiffSequenceReader` [allows anything](https://github.com/ilastik/lazyflow/blob/master/lazyflow/operators/ioOperators/opTiffSequenceReader.py#L88).)

So, somebody needs to either enhance `OpStackLoader` to allow stacking across `c`, or the UI needs to prevent the user from selecting `c` for TIFF stacks.

**Comment by akreshuk** [comment]
All fixed.
