### ISSUE TITLE
Make sure we compress all data to reduce the size of an ilastik project file

### ISSUE THREAD

**Issue by chaubold** [ilastik/ilastik#1205]
... which could be useful when only the trained classifiers and settings are needed for batch processing. If the project needs to be distributed to several compute nodes so they can parallelize e.g. Object Classification of a new dataset over blocks of data, only the classifiers e.t.c. are needed, but not the cached label images of the dataset originally used for training.

**Comment by akreshuk** [comment]
If the label images are in a  compressed cache, they shouldn't take any space at all. And there is something positive about being able to retrain if needed. But, of course, if it takes too much space in your experience, we should get rid of it. And we shouldn't store it separately for each object classifier, if it's happening now.

**Comment by chaubold** [comment]
After some more investigation I found out that the problem is mainly in tracking, where the label images displaying the resulting tracks are cached, together with a new label image after merger resolving. This quickly adds up to a lot of memory.

- [ ] check whether the data type of the cached label images is the right one and whether they are stored compressed
- [ ] should we store the resulting re-colored label images at all, as they can be recomputed from the stored tracking results? Resolving mergers is a time consuming process though, which would slow down project loading if this needs to be done at startup.

**Comment by JaimeIvanCervantes** [comment]
You could store the colored label image of the first frame for display purposes only, since of the rest of the labels can be recomputed.

**Comment by chaubold** [comment]
I've just noticed that if I compress my 600mb tracking `ilp` file, it reduces to 5mb! We must be doing something wrong when it comes to compression, probably of the label images. 

One pecularity about tracking is that we store the `coordinateMap` (a C++ object), serialized as binary string from C++ and then saved as python string. We should make sure that this is not huge.
