### ISSUE TITLE
Unable to load .tiff files in Ilastik 1.1.8 and 1.1.9

### ISSUE THREAD

**Issue by AnnaGallis** [ilastik/ilastik#1209]
Hello everyone,
maybe someone else has reported this, because I remember we commented it before, but I cannot find the thread, so sorry if I am duplicating a report.
Normally, the images I acquire are .stk files that I convert to .tiff and crop in Fiji. Loading these processed images has always worked for any Ilastik version, but now I get always the same message: "Wasn't able to load your dataset into the workflow. See error log for details". I have tried in all the versions from 1.1.7.

Is there a way to circumvent this problem? I need to analyze four videos by end of next week :(
Thank you very much!

AG
[Log text.txt](https://github.com/ilastik/ilastik/files/214979/Log.text.txt)

**Comment by AnnaGallis** [comment]
Update: Also not working if I convert the file to .hdf5

**Comment by stuarteberg** [comment]
Thanks for attaching the error log.  I just sent you an email with a patch I'd like you to try.  Let me know if the error goes away, or if a different error occurs in its place.

**Comment by AnnaGallis** [comment]
Hello Stuart,
thanks a lot for your fast answer and your e-mail. The same error is persisting with the new patch, however I have found some funny things: my old .tiff files can still be opened... it's only the new ones I generated yesterday that are giving this error. This could mean that the source of the problem is Fiji and not Ilastik (?).
A colleague suggested a workaround to avoid conversion to .tiff: save the .stk as .png sequence (although I don't like this idea a lot) and then save the .png sequence as .hdf5. If it works, I let you know and we can decide what to do next?

Thanks again!
I wish you a nice day,

AG

**Comment by AnnaGallis** [comment]
Hi again Stuart,
I tried what my colleague told me and I can load the files in Ilastik now, all the workflows I use (pixel classification, automatic tracking) are working. The problem seems not to be in Ilastik but in Fiji... I wonder what could be happening so that the new .tiff files are different. Anyway, I guess we could close the issue.
Sorry for bothering you! But thanks a lot for your support and patience!

All the best,

AG
