### ISSUE TITLE
carving: "unsaved changes"...

### ISSUE THREAD

**Issue by FredHamprecht** [ilastik/ilastik#1218]
The warning message is not wrong, but unclear. To reproduce: 
- Carve an object, but do not save it. 
- Save project. 
- Close project. 

The warning pops up. It can only be circumvented by saving the latest object, then saving the project, then closing the project. 

It would be good if the warning gave more precise instructions.

**Comment by k-dominik** [comment]
this seems to have been resolved somewhere already - following the described steps, not error message would pop up, but the seeds are saved. Reopening shows the same "in progress" annotations. The only thing lost is the carving result (so one has to click on segment again).
