### ISSUE TITLE
Carving: Showing 3D mesh in reopened project results in KeyError

### ISSUE THREAD

**Issue by nielsbuwen** [ilastik/ilastik#1224]
In the Carving workflow -> `Labeling` applet:
After reopening a previously saved project any direct attempt to show the 3D mesh of an object results in a `KeyError`

```
INFO 2016-06-01 15:29:20,575 opCarving 3624 140668271998784 click on (136, 152, 100), supervoxel=69507: [u'test']
INFO 2016-06-01 15:29:23,094 opCarving 3624 140668271998784 click on (139, 151, 100), supervoxel=69507: [u'test']
ERROR 2016-06-01 15:29:24,444 excepthooks 3624 140668271998784 Unhandled exception in thread: 'MainThread'
ERROR 2016-06-01 15:29:24,444 excepthooks 3624 140668271998784 Traceback (most recent call last):
  File "/home/nbuwen/software/ilastik/ilastik-meta/ilastik/ilastik/workflows/carving/carvingGui.py", line 406, in onShow3D
    self._update_rendering()
  File "/home/nbuwen/software/ilastik/ilastik-meta/ilastik/ilastik/workflows/carving/carvingGui.py", line 594, in _update_rendering
    objectSupervoxels = op.MST.value.objects[name]
KeyError: u'test'
```

`test` is the name of the saved object.

To reproduce:
1. Create carving project.
2. Do preprocessing etc.
3. Carve at least on object and save it `Save current object`.
4. Save the project.
5. Reopen ilastik and load the project.
6. Right-click where the object is and select `<name of object>` -> `Show 3D <name of object>`.
7. KeyError popup is shown and the menu item changes to `Remove <name of object> from 3D view` as if it was successfully added to the view.
8. Removing and showing results in the same KeyError everytime.

Even loading the object (`Browse objects` -> `load` or right click and load) before trying to show it does not prevent the error.

The only way to get rid of the error is to load the object and save it again (same name is fine). After that everything works fine until the project is closed and reopened again.

**Comment by k-dominik** [comment]
closed in @1644
