### ISSUE TITLE
ConservationTracking (master) fails in Object Classification applet (URGENT)

### ISSUE THREAD

**Issue by ilastikdev** [ilastik/ilastik#1225]
@JaimeIvanCervantes

InputData and Threshold applet work fine, so is saving the project after these two applets.

Division Detection and Object Count Classification are both broken:
clicking on an object does not "paint" the object, but paints with brush strokes for any of the classes chosen

**Comment by JaimeIvanCervantes** [comment]
I'm looking into this right now, I can see the problem in the Division Classification Applet, but not in the Count Classification Applet. The problem is not present in the latest binaries so it must be a recent commit. Working on it.

**Comment by ilastikdev** [comment]
Just as info, the problem did occur in the count classification also, but not on every run.
However, it seems the fix addressed both issues.
