### ISSUE TITLE
Binaries are not working on Ubuntu 16.04

### ISSUE THREAD

**Issue by DerThorsten** [ilastik/ilastik#1227]
Hi,

When I start the ilastik **binaries** on Ubuntu 16.04 I get the following prints in the shell

```
./run_ilastik.sh 
Starting ilastik from "/home/tbeier/bin/ilastik-1.1.9-Linux".
/home/tbeier/bin/ilastik-1.1.9-Linux/lib/python2.7/site-packages/PyQt4/../../../libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /usr/lib/x86_64-linux-gnu/libproxy.so.1)
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiolibproxy.so
tbeier@friedchicken:~/bin/ilastik-1.1.9-Linux$ ./run_ilastik.sh 
Starting ilastik from "/home/tbeier/bin/ilastik-1.1.9-Linux".
/home/tbeier/bin/ilastik-1.1.9-Linux/lib/python2.7/site-packages/PyQt4/../../../libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /usr/lib/x86_64-linux-gnu/libproxy.so.1)
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiolibproxy.so
libGL error: unable to load driver: nouveau_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: nouveau
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
X Error: GLXBadContext 172
  Extension:    155 (Uknown extension)
  Minor opcode: 6 (Unknown request)
  Resource id:  0x2600028
X Error: BadValue (integer parameter out of range for operation) 2
  Extension:    155 (Uknown extension)
  Minor opcode: 3 (Unknown request)
  Resource id:  0x0
X Error: GLXBadContext 172
  Extension:    155 (Uknown extension)
  Minor opcode: 5 (Unknown request)
  Resource id:  0x2600028
X Error: 0 0
  Extension:    155 (Uknown extension)
  Minor opcode: 26 (Unknown request)
  Resource id:  0x0
QGLContext::makeCurrent(): Failed.
```

But it still starts. I can load data, and can look at the data as long as only **one** viewer is open.
As soon as ilastik tries to show the **three** viewers, the gui starts to gray-out, and it does not recover.

@svenpeter42 mentioned that this could happen if not all things are compiled with the same compiler.

here is also the .ilastik_log.txt, but there is no interesting stuff in it I guess.

```
INFO 2016-06-02 10:42:53,164 ilastik_main 30028 140370677245696 Starting ilastik from "/home/tbeier/bin/ilastik-1.1.9-Linux".
WARNING 2016-06-02 10:42:53,506 urllib 30028 140370677245696 urllib.py(107): ImportWarning: Not importing directory '/home/tbeier/bin/ilastik-1.1.9-Linux/ssl': missing __init__.py
INFO 2016-06-02 10:42:54,230 opThresholdTwoLevels 30028 140370677245696 Using 'vigra' labeling implemetation
WARNING 2016-06-02 10:42:54,326 __init__ 30028 140370677245696 Failed to import automatic tracking workflow (conservation tracking). For this workflow, see the installationinstructions on our website ilastik.org; check dependencies: libconcert.so: cannot open shared object file: No such file or directory
WARNING 2016-06-02 10:42:54,327 __init__ 30028 140370677245696 Failed to import automatic tracking workflow (conservation tracking). For this workflow, see the installationinstructions on our website ilastik.org; check dependencies: libconcert.so: cannot open shared object file: No such file or directory
WARNING 2016-06-02 10:43:04,568 imagesources 30028 140368835274496 imagesources.py(193): FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
```

**Comment by svenpeter42** [comment]
Some library outside of the anaconda env and compiled with a different libstdc++ is loaded but the libstdc++ from inside anaconda is used. I didn't look very closely but this could be the ABI change happening with gcc 5+ which is used in ubuntu 16.04

**Comment by stuarteberg** [comment]
Thanks for the report @DerThorsten and the diagnosis, @svenpeter42.  I knew this issue was going to affect us eventually:

https://github.com/conda/conda-recipes/issues/558

...but I haven't actually done anything about it yet.

@DerThorsten, if you delete `/home/tbeier/bin/ilastik-1.1.9-Linux/lib/libstdc++.so.6`, does the error disappear?

**Comment by stuarteberg** [comment]
@DerThorsten -- Or perhaps type `conda remove -p /home/tbeier/bin/ilastik-1.1.9-Linux libgcc` instead of manually removing the file.

**Comment by stuarteberg** [comment]
@DerThorsten, if you can try the fix mentioned above and report back, I will see what I can do about modifying our gcc package to better handle this case.  (I'll implement option 1 as described in conda/conda-recipes#558.)

**Comment by javaworms** [comment]
I am running Kubuntu 16.04 and ran into the same problem. I deleted the ilastik libstdc++.so.6 file as mentioned above, but I also made a link to the libstdc++.so.6 file already installed on my machine:

`ln -s /usr/lib/x86_64-linux-gnu/libstdc++.so.6 /home/yourusername/ilastik-1.1.9-Linux/lib/python2.7/site-packages/PyQt4/../../../libstdc++.so.6`

**Comment by stuarteberg** [comment]
>I deleted the ilastik libstdc++.so.6 file as mentioned above, but I also made a link to the libstdc++.so.6 file already installed on my machine

Thanks for the report... did that work?

**Comment by javaworms** [comment]
Oops, sorry! Yes it did.

**Comment by stuarteberg** [comment]
Ah, good to know.  Thanks!

**Comment by erexhepa** [comment]
Hi  I had the same issue as javaworms on an ubuntu 16.10 and did remove the libstc library and created the link from the one in the ubuntu python and get the following error

./run_ilastik.sh 
Starting ilastik from "/home/osboxes/Downloads/ilastik-1.2.0rc10-Linux".
/home/osboxes/Downloads/ilastik-1.2.0rc10-Linux/bin/python: symbol lookup error: /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0: undefined symbol: FcWeightFromOpenType

**Comment by stuarteberg** [comment]
Thanks for the report, @erexhepa.  It sounds like that error is related to the `fontconfig` package.  Perhaps the same trick will work.  Please try this:

```bash
$ mv /home/osboxes/Downloads/ilastik-1.2.0rc10-Linux/lib/libfontconfig.so* /tmp/
```

**Comment by alxbour** [comment]
- Operating system Ubuntu18.04LTS
uname -a 
Linux Latitude 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

- Desktop environment
CINNAMON 
- Steps to reproduce
open terminal, type gvim or  gedit
- Expected behavior
opened editor window
- Actual behavior
no window pops up

**Comment by k-dominik** [comment]
Hey @alxbour , i assume you mean `ilastik` and not `gvim` oder `gedit` or `vim`. And there is a known issue with `ilastik` on ubuntu 18.04 : https://github.com/ilastik/ilastik/issues/1768

the workaround for now is to add

```
export QT_STYLE_OVERRIDE=gtk2
```

to your `.bashrc` file

**Comment by alxbour** [comment]
Hello k-dominik. I mean **gedit, gvim,vim**, not ilastik.Just double checked, see below:
$ gvim
gvim: symbol lookup error: /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0: undefined symbol: hb_glib_get_unicode_funcs
$ vim
vim: symbol lookup error: /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0: undefined symbol: hb_glib_get_unicode_funcs

**Comment by k-dominik** [comment]
I have to admit that I do not really understand why you are reporting your issue in the ilastik issue tracker.

**Comment by alxbour** [comment]
Hello k-dominik, speaking honestly, 1st of all, because google leads me to this page, then there are certain similarities in error messages. But, actually the report belongs to ubuntu 18.04 issues tracker, which I failed to find, sorry.
