### ISSUE TITLE
Qt5 discussion

### ISSUE THREAD

**Issue by stuarteberg** [ilastik/ilastik#1228]
Eventually we'll want to port to Qt5.  Let's use this issue for any notes/discussion on this topic.  I'm just opening this thread now before I forget these notes.

We should wait for nice Qt5 packages before starting.  Keep an eye on this thread:
https://github.com/conda-forge/staged-recipes/pull/606

BTW, I did experiment with porting volumina to Qt5 recently.  I didn't get very far, but here are the notes I took a the time:
- First replace `PyQt4` with `PyQt5` everywhere
- In most cases,  `QtGui` -> `QtWidgets`
- `QString`/`QStringList` was removed from `PyQt5`.  Use `unicode` instead, I guess
- `qimage2ndarray` can support `PyQt5`, but we don't have a package for that yet
- `PyQt5` docs mention issue with plugins, blaming `@rpath`.  Apparently this is fixed in Qt 5.6.  When using Darren Dale's qt5 packages, I see errors about the "cocoa" plugin, just as the `PyQt5` docs say.

**Comment by ccordoba12** [comment]
@stuarteberg, you could consider using [qtpy](https://github.com/spyder-ide/qtpy), an abstraction package that we use in Spyder to support PyQt4 and PyQt5 at the same time.

I think it'd ease your transition :-)

**Comment by stuarteberg** [comment]
Very interesting. Thanks for the tip, Carlos!

**Comment by k-dominik** [comment]
qt5 transition done :)
