### ISSUE TITLE
Conservation tracking test fails

### ISSUE THREAD

**Issue by akreshuk** [ilastik/ilastik#1229]
Just tried the new conservation tracking test and it does not run for me:

```
Traceback (most recent call last):
  File "/home/akreshuk/miniconda2/envs/ilastik-devel/ilastik-meta/lazyflow/lazyflow/operator.py", line 107, in __call__
    instance = ABCMeta.__call__(cls, *args, **kwargs)
  File "/home/akreshuk/miniconda2/envs/ilastik-devel/ilastik-meta/ilastik/ilastik/workflows/tracking/conservation/conservationTrackingWorkflow.py", line 67, in __init__
    name="Object Feature Computation")
  File "/home/akreshuk/miniconda2/envs/ilastik-devel/ilastik-meta/ilastik/ilastik/applets/trackingFeatureExtraction/trackingFeatureExtractionApplet.py", line 8, in __init__
    self._serializableItems = [ TrackingFeatureExtractionSerializer(self.topLevelOperator, projectFileGroupName) ]
  File "/home/akreshuk/miniconda2/envs/ilastik-devel/ilastik-meta/ilastik/ilastik/applets/trackingFeatureExtraction/trackingFeatureExtractionSerializer.py", line 19, in __init__
    compression_level=1),
TypeError: __init__() got an unexpected keyword argument 'compression_level'
```

**Comment by JaimeIvanCervantes** [comment]
It looks like there is a serialization problem, but it works on my machine so I have to find a way to recreate the problem. Did you ran into this problem on the master branch or the learning branch?

**Comment by akreshuk** [comment]
This is on master, with everything up-to-date. Could that be some h5py version conflict? I just noticed I have h5py and hdf5 from the default channel, not ilastik:
h5py                      2.5.0                np19py27_2    defaults
hdf5                      1.8.14                        0    defaults
 Which version do you have?

**Comment by stuarteberg** [comment]
I'm totally stumped here.  The error is complaining about [this line](https://github.com/ilastik/ilastik/blob/master/ilastik/applets/trackingFeatureExtraction/trackingFeatureExtractionSerializer.py#L19), but I don't see anything wrong there.  The `compression_level` argument is part of the [`SerialBlockSlot.__init__()` signature](https://github.com/ilastik/ilastik/blob/master/ilastik/applets/base/appletSerializer.py#L347-L350).  (It was added in [April](https://github.com/ilastik/ilastik/commit/32102e58cf92066d6356d1148eeefbf4ef0a5859).)

Are you sure that your copy of `appletSerializer.py` matches the version on github? (Specifically, line 350)?

**Comment by JaimeIvanCervantes** [comment]
Stuart is right, `compression_level` should be a valid argument. I ran the tests successfully,and my versions of h5py and hdf5 seem to be exactly the same:

h5py  2.5.0   np19py27_2  defaults
hdf5  1.8.14  0  defaults

**Comment by akreshuk** [comment]
And sure enough, it's different and there is no compression level. Looks like long ago I was testing something with manual patching, since I also have changes in conservation tracking, which I for sure never touched by myself. Sorry for the false alarm, I'll ditch all that.
