### ISSUE TITLE
object CSV export dialog does not remember your settings

### ISSUE THREAD

**Issue by stuarteberg** [ilastik/ilastik#1261]
Every time you open that window, it resets all the settings to the defaults, which is annoying.

**Comment by stuarteberg** [comment]
Also, the defaults are weird (bad default path).
Also, we should let the user choose the CSV separator character.

**Comment by chaubold** [comment]
fun fact: it has better default settings and remembers what you choose inside the conservation tracking workflow. I think this depends on how the data export applet is instantiated from the workflow.

**Comment by JaimeIvanCervantes** [comment]
I fixed this problem on the tracking workflow a while back, here: feb992a.

**Comment by stuarteberg** [comment]
How hard would it be to port your fix to work in the Object Classification Workflow, too?

**Comment by JaimeIvanCervantes** [comment]
I'll try to fix it today
