### ISSUE TITLE
HUD buttons (?) for 3D data not working properly in pixel classification: training tab on windows 

### ISSUE THREAD

**Issue by FredHamprecht** [ilastik/ilastik#1262]
![clipboard02](https://cloud.githubusercontent.com/assets/899006/16733980/14756f94-4784-11e6-932a-395b8cb18108.jpg)

**Comment by stuarteberg** [comment]
Probably due to OpenGL in the ImageViewer2D.

**Comment by stuarteberg** [comment]
In the current binary, I disabled OpenGL support on Windows (as it was in 1.1.9).  Did that fix the issue?

**Comment by stuarteberg** [comment]
Actually, Ullrich already tested this.  Fixed via ilastik/volumina@d17db4548955df42de412e62d0d5c32a36b44575
