### ISSUE TITLE
pixel classification block size is way too large 

### ISSUE THREAD

**Issue by FredHamprecht** [ilastik/ilastik#1263]
Open a 3D data set, run pixel classification.
Press CTRL-D to show the block size; or alternatively 

zoom in far 
start live update 
(wait for a long time...) 
stop live update 
zoom out far to confirm that far more than needed was computed.

**Comment by stuarteberg** [comment]
Fixed via ilastik/volumina@6ca501dad764727ba259473192f2c14961852054
