### ISSUE TITLE
Carving "Export All Meshes" exports empty obj files

### ISSUE THREAD

**Issue by braxtonj** [ilastik/ilastik#1265]
I am using version 1.1.9 
![ilastikversion](https://cloud.githubusercontent.com/assets/7331755/16742625/bed19d9c-4765-11e6-8453-2a0b034f458a.png)

When using the Carving workflow, the option to "Export All Meshes" results in a .obj for every mesh as expected.  However, each of the .obj files created are 0 bytes in size with absolutely no information in the file.  I imagine this is not the intended behavior.
![ilastikparticlemeshfiles](https://cloud.githubusercontent.com/assets/7331755/16742792/8f7fa420-4766-11e6-98d5-fa9b661a1be7.png)
![ilastikparticleobjfile](https://cloud.githubusercontent.com/assets/7331755/16742825/c8738ed6-4766-11e6-8b34-18ff138fe998.png)

A little background on how I am operating Ilastik when I run into this error.  I am using the Carving workflow in a slightly nonstandard way.  Basically, I am using it to isolate particles in an extremely dense 2D image.  The user input combined with the underlying watershed segmentation allows for extremely fast and accurate particle segmentation.  The only issue I am running into is exporting the 2d meshes.  I plan on using ImageJ's particle analyzer to gain statistical information on the morphology of the resulting meshes.  However, right now I can't get any information out of the exported meshes and am having to export the segmentation layer and then threshold to redefine the mesh ROI's in ImageJ.

**Comment by k-dominik** [comment]
closing this in favor of #2131
