### ISSUE TITLE
Structured Learning Tracking: retraining a classifier removes tracking annotations

### ISSUE THREAD

**Issue by chaubold** [ilastik/ilastik#1276]
While presenting the structured learning workflow today I went back to the division classifier and object count classifiers, added the "2 objects" class to the latter, added labels and retrained both. Then I went to go to the "Tracking -SL" applet again and tried to compute weights, and only when the results looked weird (negative transition weight) I noticed that the training annotations were completely gone.

The annotations should persist unless one changes the threshold/segmentation, and then it should warn about the annotation invalidation (probably already does, because that also invalidates the labels for the classifiers).

**Comment by ilastikdev** [comment]
This bug is fixed and was tested on pre rc7 release master.
To test it on current master I need to have a working development environment, 
but conda build fails - see #1311.
This is the only bug that needed to be fixed urgently for the Tracking with Learning.
