### ISSUE TITLE
website / publications: outdated / wrong link 

### ISSUE THREAD

**Issue by FredHamprecht** [ilastik/ilastik#1285]
The "applications by ilastik users" are outdated. Either update or delete. If update, would be good to have a link to the respective publications. 

The link to "google scholar" on the same page lands on page 5 of the references to the ilastik paper.

**Comment by akreshuk** [comment]
Google scholar link has been changed in ilastik/ilastik.github.io@63ff3cfc452bf746fdfb0cedced2c750f070cd27. I'm closing this issue now and opening another one in ilastik.github.io.
