### ISSUE TITLE
Window leveling too sensitive

### ISSUE THREAD

**Issue by maierl** [ilastik/ilastik#1294]
when I move my mouse only a single pixel left/right for Window leveling, the image is _very_ bright. the next brightness level is black/white only. tested on win 10, with a 31x5x512x512 zcyx image.
it is not as bad when I have a 299x512x512 zyx image, there I have a few more reachable brightness levels, but it is still too sensitive.

**Comment by KasparP** [comment]
I see the same problem, window leveling is unusable (single pixel mouse movement results in almost complete saturation) for an 11x400x400 volume on a win7 machine. The default (right-click) window level is somewhat useable but still saturates a large fraction of the pixels.

**Comment by k-dominik** [comment]
the problem is that the interaction takes into account the maximum possible range of the datatype, not the data-range, we should really fix this
