### ISSUE TITLE
Export fails in Pixel+Object Classification

### ISSUE THREAD

**Issue by ilastikdev** [ilastik/ilastik#1305]
when two datasets are imported in the input applet:

```
Failed to generate export file: 
/home/jales/data/david/Meeting Fred Hamprecht/Macrophages/MDM D3 +4059 INeGFP EdU CA NM 36h DMSO/test_3_Object Predictions.h5/exported_data
index 1 is out of bounds for axis 0 with size 0
```

Using Object Information Export OR Export button

**Comment by stuarteberg** [comment]
Hey there,

Please include a full traceback (it can found in `ilastik_log.txt`).  When doing so, paste the traceback within triple-backticks (```) , so it is formatted more nicely, like this:

```
ERROR 2016-07-21 11:49:49,395 excepthooks 76275 140735288824576 Traceback (most recent call last):
  File "/miniconda/envs/ilastik-release/ilastik-meta/ilastik/ilastik.py", line 111, in <module>
    main()

...bla
...bla
...bla

```

**FOR BONUS POINTS:** Use the `pytb` format specifier, so github will apply syntax highlighting!  (Click the "Edit comment" button on this post to see what I mean.)

```pytb
ERROR 2016-07-21 11:49:49,395 excepthooks 76275 140735288824576 Traceback (most recent call last):
  File "/miniconda/envs/ilastik-release/ilastik-meta/ilastik/ilastik.py", line 111, in <module>
    main()

...bla
...bla
...bla

```

**Comment by ilastikdev** [comment]
there is no traceback for this error

**Comment by akreshuk** [comment]
I can't reproduce it, Object Information Export works fine for me. Reopen if it still appears for you.
