### ISSUE TITLE
Selecting a neighbourhood feature in Standard Region Features in Object Feature Selection fails

### ISSUE THREAD

**Issue by ilastikdev** [ilastik/ilastik#1306]
with an error:

"Feature computation failed due to the following error:
'module' object has no attribute 'distanceTransform'"

on master
831e372059d8dd2ed37013456ce2fdd647226653

**Comment by stuarteberg** [comment]
You're using an old version of vigra.  We now require vigra 1.11.  The ObjectExtraction applet was updated to use the new `distanceTransform()` function name in 3c4f0e5b0673c5594a382ae06c732968c0db7f20.

Side note: Please include the full traceback when reporting errors like this.  It is often difficult to track down the cause of an error without it.
