### ISSUE TITLE
ilastik dev. env. works with ilastik-meta, but ilastik fails 

### ISSUE THREAD

**Issue by ilastikdev** [ilastik/ilastik#1311]
when replacing the ilastik-meta directory with the full git repo (all master branches).

First, one needs to install wsdt (conda install wsdt -c ilastik), 
then pandas (conda install pandas -c ilastik)

Finally, ./ilastik.py fails with:

```pytb
Original exception was:
Traceback (most recent call last):
  File "/home/jales/software/miniconda/envs/ilastik-master/ilastik-meta/ilastik/ilastik/shell/gui/startShellGui.py", line 91, in launchShell
    from ilastik.shell.gui.ilastikShell import IlastikShell
  File "/home/jales/software/miniconda/envs/ilastik-master/ilastik-meta/ilastik/ilastik/shell/gui/ilastikShell.py", line 54, in <module>
    from volumina.utility import PreferencesManager, ShortcutManagerDlg, ShortcutManager, decode_to_qstring, \
  File "/home/jales/software/miniconda/envs/ilastik-master/ilastik-meta/volumina/volumina/__init__.py", line 42, in <module>
    import api
  File "/home/jales/software/miniconda/envs/ilastik-master/ilastik-meta/volumina/volumina/api.py", line 25, in <module>
    from pixelpipeline.imagepump import ImagePump
  File "/home/jales/software/miniconda/envs/ilastik-master/ilastik-meta/volumina/volumina/pixelpipeline/imagepump.py", line 30, in <module>
    from volumina.pixelpipeline.imagesourcefactories import createImageSource
  File "/home/jales/software/miniconda/envs/ilastik-master/ilastik-meta/volumina/volumina/pixelpipeline/imagesourcefactories.py", line 24, in <module>
    from volumina.layer import GrayscaleLayer, RGBALayer, ColortableLayer, \
  File "/home/jales/software/miniconda/envs/ilastik-master/ilastik-meta/volumina/volumina/layer.py", line 32, in <module>
    from volumina.utility import decode_to_qstring, encode_from_qstring, SignalingDefaultDict
  File "/home/jales/software/miniconda/envs/ilastik-master/ilastik-meta/volumina/volumina/utility/__init__.py", line 30, in <module>
    from volumina.utility.edge_coords import edge_coords_along_axis, edge_coords_nd
  File "/home/jales/software/miniconda/envs/ilastik-master/ilastik-meta/volumina/volumina/utility/edge_coords.py", line 8, in <module>
    import pandas as pd
  File "/home/jales/software/miniconda/envs/ilastik-master/lib/python2.7/site-packages/pandas/__init__.py", line 25, in <module>
    from pandas import hashtable, tslib, lib
  File "pandas/src/numpy.pxd", line 157, in init pandas.hashtable (pandas/hashtable.c:38364)
ValueError: numpy.dtype has the wrong size, try recompiling. Expected 88, got 96

```

Seems that things were compiled against different versions of numpy.

**Comment by stuarteberg** [comment]
Interesting, I haven't seen that before.  What is the output of `conda list -n ilastik-master`?

**Comment by ilastikdev** [comment]
(ilastik-master) jales@seagul:~/software/miniconda/envs/ilastik-master$ conda list -n ilastik-master
# packages in environment at /home/jales/software/miniconda/envs/ilastik-master:
#
cairo                     1.12.18                       6  
cloog                     0.18.0                        0  
cycler                    0.10.0                   py27_0  
decorator                 3.4.0                    py27_0  
faulthandler              2.4                      py27_0  
fontconfig                2.11.1                        6  
freetype                  2.5.2                         2  
futures                   3.0.2                    py27_0  
gmp                       5.1.2                         2  
greenlet                  0.4.6                    py27_0  
h5py                      2.6.0               np111py27_1  
hdf5                      1.8.16                        0  
ann                       1.1.2                         2    ilastik
armadillo                 6.500.5                       0    ilastik
boost                     1.55.0                        5    ilastik
cplex-shared              0.1                           7    ilastik
dlib                      18.16                         3    ilastik
fftw                      3.3.4                         1    ilastik
iiboost                   0.2.post2       27_0_76140cd985ab301749395bb47cbc8f8d88cdd257    ilastik
ilastik-deps-carving      1.1.6a7                       1    ilastik
ilastik-deps-pc           1.1                      py27_3    ilastik
ilastik-deps-pc-headless  1.1                      py27_4    ilastik
ilastik-deps-pc-iiboost   1.1                           1    ilastik
ilastik-deps-tracking     1.1                           1    ilastik
ilastik-feature-selection 0.123.post9     py27_0_g4010122    ilastik
ilastik-launch            0.1                           4    ilastik
ilastik-versions          1.2                 np111py27_4    ilastik
ilastiktools              0.1             np111py27_6_gf68665d    ilastik
itk-seg-conv-only         4.6.1                         4    ilastik
jbig                      2.1                           0    ilastik
lemon                     1.2.4                         2    ilastik
libtiff                   4.0.6                         1    ilastik
mlpack                    1.0.8.99                      7    ilastik
opengm                    2.3.7.post29    np111py27_2_ga00f995    ilastik
pgmlink                   1.3             np111py27_4_g24f872e    ilastik
qimage2ndarray            1.4                 np111py27_5    ilastik
tifffile                  0.4.1           np111py27_2_g05b51f3    ilastik
vigra                     1.11.0.post36   np111py27_1_g6fcc71f    ilastik
vtk                       5.10.1.99           with_pyqt_6    ilastik
wsdt                      0.2.post2       py27_0_gc0f7913    ilastik
yapsy                     1.10.423                 py27_0    ilastik
isl                       0.12.2                        0  
jpeg                      8d                            1  
jsonschema                2.4.0                    py27_0  
libgcc                    4.8.5                         1  
libgfortran               3.0.0                         1  
libpng                    1.6.17                        0  
libxml2                   2.9.0                         0  
matplotlib                1.5.1               np111py27_0  
mkl                       11.3.3                        0  
mpc                       1.0.1                         0  
mpfr                      3.1.2                         0  
networkx                  1.9.1                    py27_0  
nose                      1.3.6                    py27_0  
numpy                     1.11.1                   py27_0  
openblas                  0.2.14                        4  
openssl                   1.0.1k                        1  
pandas                    0.18.1              np111py27_0  
patchelf                  0.9                           0  
pillow                    3.0.0                    py27_1  
pip                       6.1.1                    py27_0  
pixman                    0.32.6                        0  
psutil                    2.2.1                    py27_0  
pycairo                   1.10.0                   py27_0  
pyparsing                 2.0.3                    py27_0  
pyqt                      4.11.3                   py27_1  
python                    2.7.9                         3  
python-dateutil           2.4.2                    py27_0  
pytz                      2015.4                   py27_0  
qt                        4.8.6                         3  
readline                  6.2                           2  
scikit-image              0.12.3              np111py27_1  
scikit-learn              0.17.1              np111py27_2  
scipy                     0.17.1              np111py27_1  
setuptools                23.0.0                   py27_0  
sip                       4.16.5                   py27_0  
six                       1.9.0                    py27_0  
sqlite                    3.8.4.1                       1  
system                    5.8                           2  
tk                        8.5.18                        0  
xz                        5.0.5                         1  
zlib                      1.2.8                         3

**Comment by stuarteberg** [comment]
I'm still stumped.  What is the output of the following command?

```
/home/jales/software/miniconda/envs/ilastik-master/bin/python -c "import pandas"
```

**Comment by ilastikdev** [comment]
(ilastik-master) jales@seagul:~/software/miniconda/envs/ilastik-master$ /home/jales/software/miniconda/envs/ilastik-master/bin/python -c "import pandas"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jales/software/miniconda/envs/ilastik-master/lib/python2.7/site-packages/pandas/__init__.py", line 25, in <module>
    from pandas import hashtable, tslib, lib
  File "pandas/src/numpy.pxd", line 157, in init pandas.hashtable (pandas/hashtable.c:38364)
ValueError: numpy.dtype has the wrong size, try recompiling. Expected 88, got 96

**Comment by stuarteberg** [comment]
I wonder if somehow one of our many dependencies is screwing things up (though I can't figure out how).  What if you create an environment with *only* pandas in it?

```
conda create -n test-pandas pandas
source activate test-pandas
python -c "import pandas"
```

If that fails, then we need to ask for help from the conda guys.  If that succeeds, then you should add dependencies to that environment one-by-one until `import pandas` starts to fail.  Then we'll investigate the package that broke the environment.

**Comment by ilastikdev** [comment]
(master) jales@seagul:~/software/miniconda$ source ${CONDA_ROOT}/bin/activate root
(root) jales@seagul:~/software/miniconda$ conda create -n test-pandas pandas
Fetching package metadata .......
Solving package specifications: ..........

Package plan for installation in environment /home/jales/software/miniconda/envs/test-pandas:

The following NEW packages will be INSTALLED:

    mkl:             11.3.3-0          
    numpy:           1.11.1-py27_0     
    openssl:         1.0.2h-1          
    pandas:          0.18.1-np111py27_0
    pip:             8.1.2-py27_0      
    python:          2.7.12-1          
    python-dateutil: 2.5.3-py27_0      
    pytz:            2016.6.1-py27_0   
    readline:        6.2-2             
    setuptools:      23.0.0-py27_0     
    six:             1.10.0-py27_0     
    sqlite:          3.13.0-0          
    tk:              8.5.18-0          
    wheel:           0.29.0-py27_0     
    zlib:            1.2.8-3           

Proceed ([y]/n)? y

Linking packages ...
[      COMPLETE      ]|##################################################################################################################################################################| 100%
#
# To activate this environment, use:
# $ source activate test-pandas
#
# To deactivate this environment, use:
# $ source deactivate
#
(root) jales@seagul:~/software/miniconda$ source activate test-pandas
(test-pandas) jales@seagul:~/software/miniconda$ cd envs/test-pandas/
(test-pandas) jales@seagul:~/software/miniconda/envs/test-pandas$ python -c "import pandas"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jales/software/miniconda/envs/test-pandas/lib/python2.7/site-packages/pandas/__init__.py", line 25, in <module>
    from pandas import hashtable, tslib, lib
  File "pandas/src/numpy.pxd", line 157, in init pandas.hashtable (pandas/hashtable.c:38364)
ValueError: numpy.dtype has the wrong size, try recompiling. Expected 88, got 96

**Comment by stuarteberg** [comment]
Argh, SO FRUSTRATING. :-)

What about this?

```
python -c "import numpy; print numpy.__file__; print numpy.__version__"
```

**Comment by ilastikdev** [comment]
Yes, here is the problem:

(test-pandas) jales@seagul:~/software/miniconda/envs/test-pandas$ python -c "import numpy; print numpy.__file__; print numpy.__version__"
/home/jales/software/miniconda/lib/python2.7/site-packages/numpy/__init__.pyc
1.9.2

**Comment by stuarteberg** [comment]
Ah-ha!  There must be something in your environment that is putting that directory on your python import path.  Make sure that environment variables like `PYTHONPATH`, ` PYTHONNOUSERSITE`, `PYTHONUSERBASE` are all empty.  Also, make sure that `~/.local/lib/python2.7` does not exist.  It will only cause more problems like this.

**Comment by ilastikdev** [comment]
it was ~/.local/lib/python2.7

**Comment by stuarteberg** [comment]
OK, good.  Now I've added a cautionary note about this in the ilastik-build-conda readme:

https://github.com/ilastik/ilastik-build-conda#0-prerequisite-install-miniconda
