### ISSUE TITLE
could not open project file (cant locate attribute blockslice)

### ISSUE THREAD

**Issue by sgtsmg** [ilastik/ilastik#1353]
Im getting this error trying to open my project 'could not open project file (cant locate attribute blockslice)'

Anyone had this before?

Where is the Ilastik error log file aswell?

**Comment by akreshuk** [comment]
Haven't seen this one before, thanks for the report. The ilastik log file can be found in your home directory, it's called ilastik_log.txt.

**Comment by sgtsmg** [comment]
No problem and thanks. Its Ross from the barcelona course by the way. Thanks for running that it was very helpful.

**Comment by akreshuk** [comment]
Glad you liked the course! Once you find the log file, could you attach it here or send it to use by e-mail? Which workflow were you trying?

**Comment by k-dominik** [comment]
was there any followup on this issue? if not we should maybe close this. I don't see any actionable item coming from this right now.
