### ISSUE TITLE
Toggle Labels Layer Visibility As Keyboard Shortcut

### ISSUE THREAD

**Issue by unidesigner** [ilastik/ilastik#1358]
It would be extremely useful to be able to choose a Keybord Shortcut to Toggle the Visibility of the Labels Layer, similar to what is possible with the Prediction/Segmentation/Live Prediction layer. Being able to toggle the Label layer is very useful for instance during labeling. How difficult would it be to add this feature to Ilastik?

**Comment by stuarteberg** [comment]
Good point; now added.  It will be in the next release.  If you don't want to wait for that, replace ` ilastik-meta/ilastik/ilastik/applets/labeling/labelingGui.py ` with the [latest version from github](https://github.com/ilastik/ilastik/blob/master/ilastik/applets/labeling/labelingGui.py).

The shortcut is "0" (zero) by default, but you can change it via Settings > Keyboard Shortcuts.
