### ISSUE TITLE
Pixel classification:  how to label a complete dataset

### ISSUE THREAD

**Issue by mrali92** [ilastik/ilastik#1360]
I use a stack of 2D  image consist of 520 images taken by  different wavelength(it represent the complete information of the Image) as Input Data across the Z axis in Pixel Classification, the problem is when I use the training mode and start to label a single Image of the complete stack, it appears that I don’t get the label in the other Images in the same spot.

I would be grateful for a quick response.

**Comment by akreshuk** [comment]
This issue has been discussed in the mailing list. To summarize, loading a 520-channel dataset should be possible. However, there is no convenient way to load a stack across 'c' (only present for 't' and 'z' for now). If all channels are saved in a multipage tiff or h5, ilastik should be able to handle it. Please re-open the issue if it doesn't work.
