### ISSUE TITLE
Carving: Segmentation fault while pushed button of Labeling

### ISSUE THREAD

**Issue by shaker6691** [ilastik/ilastik#1362]
I use the build version: ilastik-1.2.0rc10-Linux
but with the ilastik-devel and the git repository the same error occurs as well.
I work on: (uname -a)
`Linux COMPUTER-NAME 4.6.5-1-t460s #1 SMP PREEMPT Wed Aug 24 20:48:49 CEST 2016 x86_64 GNU/Linux`

Procedure: 
1. Open ilastik with carving
2. I add the all_walls.hdf5 file, that can be found in the  [file.zip](https://github.com/ilastik/ilastik/files/529100/file.zip).
These data are self produced and shall show some good membranes. Other data-sets from biologists have the same issue. 
3. Preprocessing works with 2500 and the default of 1600. 
4. Clicking of the Applet: Labeling leads to the following error:
- error in the terminal: [carving_terminal_log.txt](https://github.com/ilastik/ilastik/files/529097/carving_terminal_log.txt)
- error in the ilastik log file: 
  [ilastik_log.txt](https://github.com/ilastik/ilastik/files/529077/ilastik_log.txt)

**Comment by shaker6691** [comment]
I found a solution for that problem. 
In fact, the main Problem was a libGL problem:

When I run ilastik an read in images, I got the following message:

```
libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965
libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
```

The following workaround worked for me:
```
cd ~/miniconda2/envs/ilastik-devel/lib/
mv libstdc++.so{,.bak}
mv libstdc++.so.6{,.bak}
mv libstdc++.so.6.0.19{,.bak}
ln -s /usr/lib/libstdc++.so .
```

So I linked my libstdc++.so to ilastik and it worked now. 

If other people have this issue as well, there should be another libstdc++.so linked in.

**Comment by stuarteberg** [comment]
Thanks for reporting your fix.  It sounds like this is the same issue as #1227.  I will prioritize fixing this as soon as possible.

**Comment by shaker6691** [comment]
Yes, totally the same issue, sorry for that. It had just other effects on my work than discussed on #1227.

**Comment by akreshuk** [comment]
close as duplicate
