### ISSUE TITLE
Pixeld Classification + Object Classification fails repeatedly due to error conda3

### ISSUE THREAD

**Issue by mugel2110** [ilastik/ilastik#1366]
Hi

 everyone,
I am using Ilastik for segmenting by cells. Great tool. Since a couple of day on two different machines a error is coming up over and over again.
Everything works fine for the Training and thresholding. 
But when I want to do the Object feature selection or anything downstream of this step the error:
```
Failed to generate export files: Prediction violation! symmetricEigensystem(): symmetric input matrix required (c:(cond3/conda-bld/include/vigra/egensystem.hxx:1012)
```
Any ideas for a solution?
Would be very helpful for me.
Thanks

**Comment by stuarteberg** [comment]
I've never seen that error before.

In your home directory, there will be a log file named `ilastik_log.txt`.  Can you please attach it here or send it to team@ilastik.org?  Also, if you're able to share your project (`.ilp`) file with us, that might help us figure out what's causing this error.

**Comment by mugel2110** [comment]
Hi,
thanks for your answer. Attached the log file. Strangely, the l.lip file is 120MB. The others are around 14MB. Here is a link to the file. 
[https://drive.switch.ch/index.php/s/W1XvrqCFkhzH3qC](url) 
[ilastik_log.txt](https://github.com/ilastik/ilastik/files/578173/ilastik_log.txt)

Thanks for your help

**Comment by k-dominik** [comment]
We haven't seen this error again. Most likely this was something in the conda-build chain and got fixed.
