### ISSUE TITLE
Project menu does not show

### ISSUE THREAD

**Issue by ilastikdev** [ilastik/ilastik#1374]
click on Project only displays boundary box for the Project menu

![dsc_0381](https://cloud.githubusercontent.com/assets/9413215/20558827/4ca2cc42-b172-11e6-8d97-6946fcda0c5b.jpg)

**Comment by stuarteberg** [comment]
What OS was this on?  Ubuntu 16, by any chance?  Are there any suspicious messages in the log, similar to those found in #1227?

**Comment by ilastikdev** [comment]
Ubuntu 14.04
no errors were recorded on ilastik_log.txt

**Comment by ilastikdev** [comment]
This may be an Ubuntu problem - my system slowly stop responding to any user interaction the next day, including freezing the clock etc. after closing ilastik.
Before the reboot I could reproduce the bug numerous times but could not reproduce it after reboot.

**Comment by akreshuk** [comment]
Closing for now, please re-open if it happens again.
