### ISSUE TITLE
Learning in tracking

### ISSUE THREAD

**Issue by ilastikdev** [ilastik/ilastik#1392]
needs ilastik/pgmlink 821c10e

it seems we are using an older version in the current test release 1.2.0

**Comment by stuarteberg** [comment]
OK, I've updated our recipes to use today's latest master commit (cf4d3da9c72312a3c2076b7af4b95d8e8344b1f2).  The test binaries on Dropbox have been updated, too.

**Comment by ilastikdev** [comment]
Works on linux

**Comment by ilastikdev** [comment]
works on windows

**Comment by chaubold** [comment]
works on OSX
