### ISSUE TITLE
Object feature names are not displayed correctly in the tracking csv configuration dialog

### ISSUE THREAD

**Issue by JaimeIvanCervantes** [ilastik/ilastik#1393]
The full object feature names for the default features are not being displayed correctly on the csv configuration dialog of the data export applet. Here's a screenshot of the problem:

![screenshot](https://cloud.githubusercontent.com/assets/5825034/21241783/520d40b2-c2df-11e6-9b4c-1567646fe172.png)

**Comment by k-dominik** [comment]
closing - this dialog doesn't exist anymore in tracking
