### ISSUE TITLE
ilastik1.2 is by default installing into ilastik-1.1.9

### ISSUE THREAD

**Issue by ilastikdev** [ilastik/ilastik#1394]
... on windows

**Comment by FredHamprecht** [comment]
on my machine, it wants to install into 1.2.0rc10 (instead of 1.2.0) 
Could it be that it always picks the name of the last installation?

**Comment by ukoethe** [comment]
> Could it be that it always picks the name of the last installation?

Probably. I first used the official "uninstall ilastik" in the start menu to remove the existing installation. Then installation worked for me as expected, i.e. installed into ilastik-1.2.0.

**Comment by k-dominik** [comment]
haven't heard of any related issues since more than two years. Seems to be fixed
