### ISSUE TITLE
Structured Learning Tracking: unlabeled object count is not updated when using "remove label" from the context menu

### ISSUE THREAD

**Issue by chaubold** [ilastik/ilastik#1396]
The frame shown is still part of the active crop, and all 4 objects got their labels removed by using the "remove label X" option from the context menu. Yet the labeled object count says 15, which **should** be wrong if the labels are actually removed. From the annotations that are considered in structured learning this seems to be the case, so probably just displayed number is wrong.

![screen shot 2016-12-20 at 16 10 28](https://cloud.githubusercontent.com/assets/16854/21355625/08fa24f0-c6cf-11e6-8947-ba7fbac491d9.png)

**Comment by ilastikdev** [comment]
fixed in 
hytra-learning d42ab9b
