### ISSUE TITLE
Add user labels to the exported csv table

### ISSUE THREAD

**Issue by Fritze** [ilastik/ilastik#1405]
Hi,

I would like to generate a confusion matrix based on my current labeling in the object classification mode. This would be very helpful to evaluate the performance of the model.

As a workaround: Is there any possibility to extract a table of features but only from the labels used for training ?

**Comment by akreshuk** [comment]
You are right, for some reason we don't export he information on which objects have been labeled in the csv table. We'll fix that, thanks for the report.

For your evaluation, would out-of-bag error be of any help? You can find it in the log file (ilastik_log.txt).
