### ISSUE TITLE
Make stage 2 RGB again!

### ISSUE THREAD

**Issue by Steffen-Wolf** [ilastik/ilastik#1410]
Setting: auto context with RGB input data

Problem: In the second stage of the auto-context worklfow, the input data channel dimension becomes larger than 3 and can therefore not be displayed in RGB anymore. This makes it hard to label images, where the colour is the distinguishing feature.

Solution suggestion: Make the original input image layer available in second stage viewer (in addition to the augmented input data)

**Comment by jjerphan** [comment]
Related to #2174.

**Comment by k-dominik** [comment]
closed via #2866
