### ISSUE TITLE
Export of tracking results fails with error 'max_nearest_neighbours'

### ISSUE THREAD

**Issue by VolkerH** [ilastik/ilastik#1411]
Windows 10 64 bit. Ilastik version 1.2.0

Using the workflow tracking with raw data and probility map.
Divisible objects is not checked. After clicking the Track button there is no error and the tracking results are visualized.
When trying to export the tracking results (doesn't matter whether as table or h5) I receive an error 'max_nearest_neighbours'.
Traceback see below:

```

 10:58:18.578 INFO: FeatureStore created
make new graph
- 10:58:18.625 INFO: using border-aware appearance and disappearance costs, with absolute margin: 10
- 10:58:18.625 INFO: Using classifier prior
- 10:58:18.625 INFO: ConservationTracking::perturbedInference: generating tracklet graph
- 10:58:18.640 INFO: ConservationTracking::perturbedInference: number of iterations: 1
- 10:58:18.640 INFO: ConservationTracking::perturbedInference: perturb using method with Id 1
- 10:58:18.640 INFO: number_of_transition_nodes_ = 393
- 10:58:18.640 INFO: number_of_appearance_nodes_ = 214
- 10:58:18.640 INFO: number_of_disappearance_nodes_ = 214
- 10:58:18.640 INFO: number_of_division_nodes_ = 0
- 10:58:18.656 INFO: [ConsTrackingInferenceModel] add_constraints
- 10:58:18.656 INFO: [ConstraintPool]: Adding 214 hard constraints for Incoming
- 10:58:18.656 INFO: [ConstraintPool]: Adding 0 hard constraints for Outgoing
- 10:58:18.672 INFO: [ConstraintPool]: Adding 214 hard constraints for Outgoing
- 10:58:18.672 INFO: [ConstraintPool]: Adding 214 hard constraints for Detection
- 10:58:18.672 INFO: [ConstraintPool]: Adding 0 hard constraints for FixNodeValue
- 10:58:18.672 INFO: [ConsTrackingInferenceModel] add_constraints
Tried aggregator 2 times.
Aggregator did 1249 substitutions.
Reduced MIP has 1137 rows, 1677 columns, and 3635 nonzeros.
Reduced MIP has 821 binaries, 0 generals, 0 SOSs, and 0 indicators.
Presolve time = 0.01 sec. (4.18 ticks)
Found incumbent of value 35368.346376 after 0.01 sec. (5.54 ticks)
Probing time = 0.00 sec. (0.77 ticks)
Tried aggregator 1 time.
Reduced MIP has 1137 rows, 1677 columns, and 3635 nonzeros.
Reduced MIP has 821 binaries, 0 generals, 0 SOSs, and 0 indicators.
Presolve time = 0.02 sec. (2.28 ticks)
Probing time = 0.00 sec. (0.77 ticks)
Clique table members: 281.
MIP emphasis: balance optimality and feasibility.
MIP search method: dynamic search.
Parallel mode: none, using 1 thread.
Root relaxation solution time = 0.00 sec. (2.95 ticks)

        Nodes                                         Cuts/
   Node  Left     Objective  IInf  Best Integer    Best Bound    ItCnt     Gap

*     0+    0                        35368.3464      416.8868            98.82%
*     0     0      integral     0    13797.0081    13797.0081      336    0.00%
Elapsed time = 0.09 sec. (14.04 ticks, tree = 0.00 MB, solutions = 2)

Root node processing (before b&c):
  Real time             =    0.09 sec. (14.14 ticks)
Sequential b&c:
  Real time             =    0.00 sec. (0.00 ticks)
                          ------------
Total (root+branch&cut) =    0.09 sec. (14.14 ticks)
- 10:58:18.781 INFO: conclude MAP
ILP model eval: 13797
-> storing state of detection vars
-> constructing unresolved events
- 10:58:18.797 INFO: -> resolving mergers
- 10:58:18.797 INFO: Nothing to resolve in ConstTracking::resolve_mergers:
- 10:58:18.797 INFO: max_number_objects = 1
- 10:58:18.797 INFO: -> done resolving mergers3
ERROR 2017-01-26 10:58:26,625 log_exception 12780 8320 Traceback (most recent call last):
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\ilastik\ilastik\applets\dataExport\dataExportGui.py", line 386, in exportSlots
    self.parentApplet.prepare_lane_for_export(lane_index)
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\ilastik\ilastik\workflows\tracking\conservation\conservationTrackingWorkflow.py", line 351, in prepare_lane_for_export
    max_nearest_neighbors = parameters['max_nearest_neighbors'],
KeyError: 'max_nearest_neighbors'
```

**Comment by JaimeIvanCervantes** [comment]
Hello @VolkerH, I will try to recreate this problem and get back to you soon. In the meantime I would suggest you to run the tracking workflow on either linux or mac OS, since the new tracking pipeline is disabled on Windows.

**Comment by VolkerH** [comment]
Hi Jaime,

thanks for looking into this. I will try and install ilastik on a linux/mac machine and have a look.
I have successfully exported tracking results from the windows verion in the past,  so I will also try and go back to an older release candidate version on Windows and see whether I run into the same issue.

**Comment by VolkerH** [comment]
same problem on Mac OS unfortunately

**Comment by VolkerH** [comment]
Went back to 1.2.0rc7  on OS X, which I still had in the download folder on my Mac. Track export is working that version.

**Comment by VolkerH** [comment]
Meanwhile I also tried this on the latest Linux release version. The max_nearest_neighbor error shows up there as well ...

**Comment by chaubold** [comment]
Hi @VolkerH, 
That is very unfortunate, but thanks for the extensive testing! We'll try to fix that as soon as possible. Unfortunately I'll only have time for that on Tuesday.

@JaimeIvanCervantes or @ilastikdev, if you have time before that, could you please try exporting when there are no mergers (note the `max_number_objects=1` in the log above), and see whether we've broken that case while fixing the feature recomputation for the resolved mergers? Thanks.

If it is not that simple to reproduce, @VolkerH, could you provide us with your project file (or a minimal crashing example)?

**Comment by VolkerH** [comment]
Thanks, I can live with using an older release candidate version for a while, I was just introducing one of our microscope users to the tracking workflow (not that I'm terribly experienced using it myself). 
Happy to provide the .ilp - file, but I guess you need the image data as well and that is a fairly large file (I will also have to ask the user for permission).

**Comment by JaimeIvanCervantes** [comment]
@VolkerH I managed to get a similar error which is probably related:

```
ERROR 2017-01-27 10:21:20,259 log_exception 16088 140141174888192 Traceback (most recent call last):
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/ilastik/ilastik/applets/dataExport/dataExportGui.py", line 386, in exportSlots
    self.parentApplet.prepare_lane_for_export(lane_index)
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/ilastik/ilastik/workflows/tracking/conservation/conservationTrackingWorkflow.py", line 329, in prepare_lane_for_export
    size_range = parameters['size_range'],
KeyError: 'size_range'
```
I got this error when trying to export my results without running tracking first. The missing key occurs because some parameters (including the max_nearest_neighbors) are stored only after the `Track!` button is pressed. I will fix the issue, but in the meantime could you make a favor: Could you run tracking first, and then try to export the results, and check if it works? 

NOTE: For this test you don't have to run tracking for the whole video, you can also run tracking on a few frames by selecting the time range from 0 to N frames.

**Comment by VolkerH** [comment]
I had run Tracking (successfully I believe) when I originally encountered the error on Windows.
I didn't when trying on Mac/Linux though.
