### ISSUE TITLE
Error when starting feature selection in object classification

### ISSUE THREAD

**Issue by alexanderbrown** [ilastik/ilastik#1432]
Hi, 

I'm running Ilastik 1.2.0. When I try to select features in object classification I get the following error message

`Python argument types in
    vigra.analysis.extract2DConvexHullFeatures(VigraArray)
did not match C++ signature:
    extract2DConvexHullFeatures(vigra::NumpyArray<2u, vigra::Singleband<unsigned int>, vigra::StridedArrayTag> labels, boost::python::api::object ignoreLabel=None, bool list_features_only=False)
 (Advanced information about this error may be found in the log file: /home/abrown/ilastik_log.txt)`

Is this related to an undocumented requirement or is it a bug?
I can send the log file if that's useful.
Running Ubuntu 16.04

**Comment by msschwartz21** [comment]
I am also experiencing this problem on my computer running Windows 10.

**Comment by akreshuk** [comment]
We are planning a new release later this week, this problem should be gone.

**Comment by imagejan** [comment]
Is there a new release available somewhere already? We just stumbled upon this very same issue as well 🙂

**Comment by chaubold** [comment]
We are currently testing our release candidate, it will be out *very* soon!
