### ISSUE TITLE
The new Tracking Plugin system is also exporting labeled volumes

### ISSUE THREAD

**Issue by JaimeIvanCervantes** [ilastik/ilastik#1456]
When I was exporting a CSV table using the new Plugin system, I realized that the Object-Identities volume was also exported. It would be a good idea to disable exporting volumes, since most of the times it's not necessary, and exporting volumes is expensive when it comes to the running-time. 

Also, if we are going to end up exporting labelled volumes when using the Plugin system, it would be nice to export the `Tracking-Results` instead of the `Object-Identities`, since the object identities are only useful for debugging purposes.

**Comment by chaubold** [comment]
> When I was exporting a CSV table using the new Plugin system, I realized that the Object-Identities volume was also exported.

Hmm. That should not be the case, it should actually **only** export the CSV table, and I'm sure it behaved that way at some point.

> Also, if we are going to end up exporting labelled volumes when using the Plugin system, it would be nice to export the Tracking-Results instead of the Object-Identities, since the object identities are only useful for debugging purposes.

No, in combination with the CSV table the `Object-Identities` are much more useful, as the table references every object in each frame by it's label ID. For your animal tracking scenario the tracking result might suffice, but once there are divisions, the `Tracking-Result` assigns the same lineage ID to all progenitors of the same mother cell, making a mapping of rows in the table to objects in the frame ambiguous.
