### ISSUE TITLE
Website: Update installation instructions for Ubuntu

### ISSUE THREAD

**Issue by habi** [ilastik/ilastik#1461]
On the [page with the Installation instructions](http://ilastik.org/documentation/basics/installation.html) you tell the user to *extract its contents* with

    tar xzf ilastik-1.0-Linux.tar.gz

This does not work with a current download (I got `ilastik-1.2.0-Linux.tar.bz2` today).
The command sould probably be somethins like 

    tar xzf ilastik-*.tar.gz

**Comment by akreshuk** [comment]
Done in ilastik/ilastik.github.io@3a73eaf5c25e19e69d68f43ee8e75bf855cbdc11. Thanks for the report!

**Comment by habi** [comment]
> Thanks for the report!
> 
Very welcome!
