### ISSUE TITLE
Error with checkOverwriteFiles on dataExportGui

### ISSUE THREAD

**Issue by JaimeIvanCervantes** [ilastik/ilastik#1466]
I created a new `pixel classification` project and as I was trying to export the pixel probabilities, I got this error:

```
ERROR 2017-04-12 21:18:49,871 log_exception 23195 139669920544512 Traceback (most recent call last):
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/ilastik/ilastik/applets/dataExport/dataExportGui.py", line 396, in exportSlots
    exportStatus = self.parentApplet.post_process_lane_export(lane_index, checkOverwriteFiles=True)
TypeError: post_process_lane_export() got an unexpected keyword argument 'checkOverwriteFiles'
```
@chaubold and @LetiP do you think this might be related to the plugin system? Maybe you added the `checkOverwriteFiles` parameter only to the overrided `post_process_lane_export` function of the tracking operator, and you forgot to add it to the rest of the workflows.

**Comment by chaubold** [comment]
Ooh good catch. We'll fix that.
