### ISSUE TITLE
Tracking with Learning does not load on Windows because ProgressBar is hytra-only

### ISSUE THREAD

**Issue by chaubold** [ilastik/ilastik#1482]
@ukoethe is just building the new Windows binary and we noticed that the `Tracking with Learning` workflow does not show up due to an `ImportError: no module named hytra`.
I assume that this is because the new progress bar imports hytra without any checks,
 and doesn't have fallback behaviour for the non-hytra case, but there might be even more cases where it breaks (see e.g. https://github.com/ilastik/ilastik/blob/289c7f92044e8e4e931b6705e7ab64779fdf948b/ilastik/applets/tracking/structured/structuredTrackingGui.py#L23-L23)

@ilastikdev: could you please make sure that Structured Learning (with or without ProgressBar, whatever is easier) works without hytra by moving the `hytra` folder out of `site-packages`, but while having `pgmlink` available?

**Comment by ilastikdev** [comment]
done in https://github.com/ilastik/ilastik/pull/1481
