### ISSUE TITLE
Tracking Export: check for overwriting files not continuing on "yes"

### ISSUE THREAD

**Issue by chaubold** [ilastik/ilastik#1490]
We wanted to make the tracking plugin export convenient for users and ask whether they want to overwrite existing files, by introducing the following lines in [DataExportGui](https://github.com/ilastik/ilastik/blob/2fb916c5424d7bb652f00f5a31d2d86fca7c10a2/ilastik/applets/dataExport/dataExportGui.py#L396-L402)

```py
if self.parentApplet.postprocessCanCheckForExistingFiles():
    exportStatus = self.parentApplet.post_process_lane_export(lane_index, checkOverwriteFiles=True)
    if exportStatus == False:
        if self.showOverwriteQuestion():
            self.parentApplet.post_process_lane_export(lane_index, checkOverwriteFiles=False)
else:
    self.parentApplet.post_process_lane_export(lane_index)
```

Where `showOverwriteQuestion` pops up a message box to the user asking if files should be overwritten, and should continue accordingly.
But because `showOverwriteQuestion` is `@threadRouted`, **it doesn't return anything**.

@stuarteberg @akreshuk is there an elegant way to get the *answer* to a message box basically by something like a `blocking thread routed` call?

Right now, the only way to get files output from the plugin if they are already there from a previous run is if you delete them manually. If there is no straightforward solution then I'll remove that check for existing files completely for this new binary.

**Comment by stuarteberg** [comment]
>is there an elegant way to get the answer to a message box basically by something like a blocking thread routed call?

There is no elegant way that I can think of, but that's not to say it's difficult, per se.  One hacky solution is to "return" the value via a mutable parameter, (similar to using an out-parameter in C++).

```python
if self.parentApplet.postprocessCanCheckForExistingFiles():
    exportStatus = self.parentApplet.post_process_lane_export(lane_index, checkOverwriteFiles=True)
    if exportStatus == False:
        shouldShow = [None]
        self.showOverwriteQuestion(shouldShow)
        if shouldShow[0]:
            self.parentApplet.post_process_lane_export(lane_index, checkOverwriteFiles=False)
else:
    self.parentApplet.post_process_lane_export(lane_index)


    @threadRouted
    def showOverwriteQuestion(self, shouldShow):
        assert isinstance(shouldShow, list)
        reply = QMessageBox.question(self, 'Warning!',
                                         'This filename already exists. Are you sure you want to overwrite?',
                                         QMessageBox.Yes, QMessageBox.No)
        if reply == QMessageBox.Yes:
            shouldShow[0] True
shouldShow[0] = False
```

**Comment by chaubold** [comment]
Oh yeah thanks, now that you point out this solution it's kind of obvious 😄 .
