### ISSUE TITLE
Window Levelling for Object Classification

### ISSUE THREAD

**Issue by votti** [ilastik/ilastik#1500]
The Windows leveling function is really nice for the pixel classification workflow on images with multiple color planes and not nicely normalized ranges. Having the 'Window levelling' function also available in the Object Classification pipeline would be really a crucial addition to make  also this workflow useful for people with not nicely normalized images.

**Comment by k-dominik** [comment]
Hey votti, sorry for the late reply. Thank you for this valid suggestion. Until we unify the UIs for the different workflows, you could right click the `Raw Data` layer in the layer panel (left bottom) and click on `adjust thresholds` in the context menu to adjust the data range for visualization.

**Comment by votti** [comment]
Awesome, thanks for this hint, it works well this way!
Cheers!

**Comment by k-dominik** [comment]
closed in favor of #1754
