### ISSUE TITLE
track() got an unexpected keyword argument 'detWeight'

### ISSUE THREAD

**Issue by FynnBe** [ilastik/ilastik#1503]
Hi!

I was going through the Animal Tracking tutorial and encountered the following bug after clicking 'Track!':

```
ERROR 2017-05-17 14:40:27,622 log_exception 10708 13000 Traceback (most recent call last):
  File "C:\conda\envs\ilastik-dev\ilastik-meta\ilastik\ilastik\applets\tracking\conservation\conservationTrackingGui.py", line 315, in _track
    solverName=solver
TypeError: track() got an unexpected keyword argument 'detWeight'

ERROR 2017-05-17 14:40:27,624 log_exception 10708 13000 Error during tracking.  See above error traceback.
```

Uncommenting `detWeight=10,` in line 298, as well as `numFramesPerSplit=self._drawer.numFramesPerSplitSpinBox.value(),` in line 314 (similar Error) fixed the issue.

**Comment by chaubold** [comment]
Thanks for finding that! This is again due to the diverging backends between Windows and Linux/Mac. I'll prepare a fix and will ask you to double check on windows before we merge it, ok?
