### ISSUE TITLE
Error encountered during batch processing...

### ISSUE THREAD

**Issue by blaiseMibeck** [ilastik/ilastik#1515]
Hi, this was in the command window when I tried to batch process files: 
log exception 3904 3908 Error encountered during batch processing. 
I am not sure how to troubleshoot this. I uninstalled and reinstalled the last stable version (1.2.0rc10). I have  tried starting the project from scratch, restating the computer (Win7). I have been successfully using this program on this computer for a while and have not encounter this error before.

**Comment by blaiseMibeck** [comment]
Just wanted to add that I am just doing pixel classification.

**Comment by stuarteberg** [comment]
There should be a file in your home directory named `ilastik_log.txt`.  Can you locate it and upload it here?

**Comment by blaiseMibeck** [comment]
I am not able to find ilastik_log.txt 
I searched in C:\Program Files\ilastik-1.2.0rc10\

**Comment by stuarteberg** [comment]
Please look in your home directory.  Depending on your username, it will be something like `C:\Users\Blaise\ilastik_log.txt`.

**Comment by blaiseMibeck** [comment]
Ok, I've looked there and see no log file.

**Comment by stuarteberg** [comment]
Hmm, that's not good.  Is there a console window open in the background while ilastik is running?  If so, what are the contents of that window?

**Comment by blaiseMibeck** [comment]
I just tried to run into the same problem again so I could capture an image of the console window, but the program stalls before opening the project. I would like to do a fresh install -- is there a proper way to do this? I uninstalled the previous install and then downloaded and ran the windows installer. My project and images are a different hard drive from the program, but that shouldn't matter, right? Like I said, this is the first time I have had this problem. I will try to move this project to a different computer.

**Comment by blaiseMibeck** [comment]
Thank you for your kind help!

**Comment by blaiseMibeck** [comment]
I installed Ilastik 1.2.2 on my home computer and ran into the same problem as earlier. This time however there was a log file saved. Any help would be greatly appreciated. This new computer is windows 7 as well. 
<img width="417" alt="ilastik_counsole" src="https://cloud.githubusercontent.com/assets/8353721/26382564/b005be84-3ff2-11e7-8b49-5a412f6faa16.PNG">
[ilastik_log.txt](https://github.com/ilastik/ilastik/files/1024135/ilastik_log.txt)

**Comment by blaiseMibeck** [comment]
Any ideas? I have no idea what I did. Like I said I used to have no issues with batch process.

**Comment by stuarteberg** [comment]
Apparently the software is having trouble reading your TIFF files.  This is not uncommon, since there are many variations of TIFF metadata.

1. What software did  you use to generate the TIFF file?
2. How many channels does it have?  What are the image dimensions?
3. If you can send us an example TIFF file, it will help us figure out what the problem is.  (You can upload it here if you put it into a zip file, or send it to team@ilastik.org)

Meanwhile, if you are able to convert your input data to some other format (e.g. PNG or HDF5), then you can work around this TIFF-reading issue.  The recently released "ilastik import/export" plugin for Fiji might be of use:

http://ilastik.org/documentation/fiji_export/plugin

**Comment by blaiseMibeck** [comment]
Ahhh. I have recently been exporting tifs differently so that they contain coordinates in the metadata. 

I have been training on cropped sections of these tifs which is why the problem only shows itself when I do batch processing. 

So cool there is a fiji plugin. I will totally check that out. THANKS!!

**Comment by blaiseMibeck** [comment]
I removed the metadata from the tiffs and now everything works like before! Thanks so much for the help.

**Comment by stuarteberg** [comment]
Cool.  Thanks for the update.
