### ISSUE TITLE
headless mode for tracking needs documentation

### ISSUE THREAD

**Issue by gcharvin** [ilastik/ilastik#1519]
Hello 
first, thanks for this very nice software. 
I was wondering whether you plan to release a headless mode for object tracking, similarly to the headless mode for pixel classification ? 
Thanks for your reply, 
Best
Gilles Charvin

**Comment by chaubold** [comment]
Hi @gcharvin, thanks for the kind words.

We do have a headless mode for tracking, but it is not properly documented yet. See http://ilastik.org/documentation/animalTracking/animalTracking#tocAnchor-1-1-4 for a glimpse of how headless mode for tracking works in the latest Linux and Mac binary (the Windows interface is still a little different).

In general, you specify a previously trained tracking project, add raw (`--raw_data=`) and a binary segmentation (`--segmentation_image=`) or probability maps from a pixel classification workflow (`--prediction_maps=`) and select which kind of export you want (`--export_source=`), which can be any of those that you can select in the *Tracking Result Export* applet in the GUI. If you select `Plugin` there (Linux+Mac only for now), you can specify the same name as we show for the Plugins in the GUI. It will then track the the provided dataset with the same trained classifiers and specified weights as you used in the GUI.

I'm changing this issue into a request for more documentation.
Let us know whether you need any further guidance!

**Comment by gcharvin** [comment]
Thanks for your swift reply ! 
I will try this right away. 
Best
Gilles

**Comment by jbychang** [comment]
I just experimented a bit on running tracking in headless mode and wanted to share my code. I'm not sure if I'm doing everything correctly, but it's giving reasonable output.

I'm running it as a Windows .bat file (which explains the "call" in front of each line). I have three lines here, which each output to a different type of output file. (I tried running it with all the export flags in a single command, but that didn't work.) The commands take in a .tif sequence (as a glob string) as well as the probabilities from a pixel classification project (the .h5 file).

One notable and less-than-ideal thing is that the tracking has to run three times. Aside from the time cost, I hope that it's deterministic. :)


```
call "c:\Program Files\ilastik-1.3.0b1\run-ilastik.bat" --headless --project="E:\2017_11_10_expt_15\JC_171031_expt_15_SK_dose_response\Training_images_CEF\2017_11_17_track_cyx_rows_CEF_bf_nucleus_ilastik13b.ilp" --raw_data="E:\2017_11_10_expt_15\JC_171031_expt_15_SK_dose_response\C02\Well_C02_t*_0000-bf-bfp.tif" --prediction_maps="E:\2017_11_10_expt_15\JC_171031_expt_15_SK_dose_response\C02\Well_C02_t________________0000_bf_bfp_probs.h5" --export_source="Tracking-Result"

call "c:\Program Files\ilastik-1.3.0b1\run-ilastik.bat" --headless --project="E:\2017_11_10_expt_15\JC_171031_expt_15_SK_dose_response\Training_images_CEF\2017_11_17_track_cyx_rows_CEF_bf_nucleus_ilastik13b.ilp" --raw_data="E:\2017_11_10_expt_15\JC_171031_expt_15_SK_dose_response\C02\Well_C02_t*_0000-bf-bfp.tif" --prediction_maps="E:\2017_11_10_expt_15\JC_171031_expt_15_SK_dose_response\C02\Well_C02_t________________0000_bf_bfp_probs.h5" --export_source="Object-Identities"

call "c:\Program Files\ilastik-1.3.0b1\run-ilastik.bat" --headless --project="E:\2017_11_10_expt_15\JC_171031_expt_15_SK_dose_response\Training_images_CEF\2017_11_17_track_cyx_rows_CEF_bf_nucleus_ilastik13b.ilp" --raw_data="E:\2017_11_10_expt_15\JC_171031_expt_15_SK_dose_response\C02\Well_C02_t*_0000-bf-bfp.tif" --prediction_maps="E:\2017_11_10_expt_15\JC_171031_expt_15_SK_dose_response\C02\Well_C02_t________________0000_bf_bfp_probs.h5" --export_source="Plugin" --export_plugin="CSV-Table" 
```


Best,
Jeremy
