### ISSUE TITLE
ilastik-1.2.2rc3: Failed to import fast filters: No module named fastfilters

### ISSUE THREAD

**Issue by AVKazak** [ilastik/ilastik#1522]
Greetings, dear community members!

How do I fix this issue on Windows 7 and Windows Server 2012 R2?

> C:\Program Files\ilastik-1.2.2rc3>run-ilastik.bat --headless
> Loading ilastik from "C:\Program Files\ilastik-1.2.2rc3\ilastik-meta"
> INFO ilastik_main: Starting ilastik from "C:\Program Files\ilastik-1.2.2rc3".
> Starting ilastik from "C:\Program Files\ilastik-1.2.2rc3".
> WARNING 2017-05-30 07:24:24,171 vigraOperators 17004 3180 Failed to import fast filters: No module named fastfilters

**Comment by chaubold** [comment]
This warning is not limiting you at all in terms of functionality, it only means that you do cannot use the fastest implementation of features (for Pixel Classification) that we have available.

@ukoethe, @svenpeter42: do we ship `fastfilters` on Windows at all?

**Comment by svenpeter42** [comment]
It certainly build on windows, no idea if it is already included in the releases though.

**Comment by AVKazak** [comment]
Thank you for the insight --- I am a newbie with _ilastik_.
I noticed that _ilastik_ does not use all power of my current workstation (20 % of CPU and RAM at most).
Is there a way to turn on fastfilters on Windows or anyhow tell _ilastik_ to use all available CPU and memory resources?
Thank you.

**Comment by AVKazak** [comment]
Can you an update for the topic please?
Thank you.

**Comment by k-dominik** [comment]
@AVKazak there is a new release candidate available for download at http://ilastik.org/download.html . Could you tell us if this is still an issue with this version? @ukoethe, @fynnbe do you see this issue on your Windows machines?

**Comment by k-dominik** [comment]
Hi @AVKazak , I have just confirmed with @ukoethe , that we currently do not ship fast filters with the windows build (so also not in the latest 1.2.2rc4), due to some windows related problems on which we are working on.

**Comment by AVKazak** [comment]
@k-dominik ,
OK, I see that I should move to Linux.
What Linux distribution works best with ilastik?

Thank you.

**Comment by k-dominik** [comment]
A lot of people here are on Ubuntu 16.04 LTS.

**Comment by akreshuk** [comment]
Any reasonably recent distribution should be ok, but 16.04 is indeed the safest bet.

**Comment by AVKazak** [comment]
@k-dominik @akreshuk 
Thank you for the suggestion.
I will try it out on Ubuntu 16.04 LTS.
