### ISSUE TITLE
Axes reordering: going from t to spatial dimension disables scrolling

### ISSUE THREAD

**Issue by chaubold** [ilastik/ilastik#1529]
When you loaded a 3D dataset and used one axis as time `t`, but then decide to switch it to a spatial interpretation, _e.g._ `z`, the corresponding slicing view in which one would scroll over that axis doesn't allow scrolling along that axis at all.

**Comment by chaubold** [comment]
More detailed steps to reproduce:

* open a 3D dataset
* configure its axes such that `x`, `y`, and `t` are present (hence, implicitly `z=1`)
* close the dialog so that the viewer shows the time scrolling bar
* change the axes to represent `x`, `y`, and `z`.
* try to scroll in the XY-view. It stays at `0` all the time.

The problem is that in this function: https://github.com/ilastik/volumina/blob/a129fe3260250127ce1044257f5407d32acc2baa/volumina/sliceSelectorHud.py#L192-L202, the `maxValue` for the `z` axis extracted from the `CroppingMarkers.crop_extent_model` is wrong and still thinks that the `z` axis only has shape `1`.

We need to make sure that the `crop_extent_model` gets updated when the shape/axes order changes.

**Comment by ilastikdev** [comment]
fixed

needs volumina
https://github.com/ilastik/volumina/pull/187

and ilastik
https://github.com/ilastik/ilastik/pull/1558
