### ISSUE TITLE
Knime integration for autocontext, multicut

### ISSUE THREAD

**Issue by akreshuk** [ilastik/ilastik#1546]
One can already run headless pixel classification on a pre-trained project as a knime node. Users are requesting other ilastik workflows which produce segmentation - autocontext and multicut - to be available in this manner as well.
The same could stand for CellProfiler integration, the issue here: https://github.com/CellProfiler/CellProfiler/issues/2393.

**Comment by chaubold** [comment]
See also https://github.com/ilastik/ilastik4ij

**Comment by k-dominik** [comment]
I'd say with #2900 and `ilastik4ij` we can close this
