### ISSUE TITLE
CPU usage...

### ISSUE THREAD

**Issue by blaiseMibeck** [ilastik/ilastik#1548]
I have 24 logical cores (12 physical) and my CPU usage doesn't go above ~33% during pixel classification. It looks like only half the cores are running at any given time. 

Should I run Ilastik with hyper-threading turned off? I read that Ilastik will use all available cores... do I have to do anything to Ilastik? or is this a windows problem? 

The image I am classifying is a tif.

**Comment by akreshuk** [comment]
Is that the usage in batch mode/headless or interactive? How big is the image? ilastik works on image tiles of 512x512, perhaps there are not enough tiles to fill all cores?

**Comment by blaiseMibeck** [comment]
Interactive. The image is 2560x1920, so that should be about 18 or 19 tiles... That is about how many are running -- thanks!
