### ISSUE TITLE
left-click into image view (in manual tracking) is interpreted as double left-click

### ISSUE THREAD

**Issue by FynnBe** [ilastik/ilastik#1557]
Project file: [manualTracking-doubleClickBug.zip](https://github.com/ilastik/ilastik/files/1112881/manualTracking-doubleClickBug.zip)
Example after clicking on a cell at time 0:
![manualtracking-doubleclickbug](https://user-images.githubusercontent.com/15139589/27700567-45acffce-5cfe-11e7-9435-ed27a0708ab9.png)

**Comment by chaubold** [comment]
This is actually not a bug (ignore my commit above if it still shows up).

In manual tracking, a *click* is interpreted as a connection of the clicked-on object to the object in the previous frame with the same color. But as in frame 0 there is no such object in the previous frame, it connects the objects from frames 0 and 1 and immediately jumps to frame 2 (see the lower right in your screenshot).

So it is not doing anything wrong, but it is indeed a little unintuitive.
