### ISSUE TITLE
Qt5 detects deadlock in GuiProgressBar

### ISSUE THREAD

**Issue by chaubold** [ilastik/ilastik#1559]
Using `python=3.6` and `Qt5`, running the `qt5py3` branch, it seems that Qt has become more intelligent and notices some invalid connection of signals in the Tracking GuiProgressBar, and exits with the message below when one clicks on the `Track` button:

```
Qt: Dead lock detected while activating a BlockingQueuedConnection: Sender is TrackProgress(0x7fd905f3ee40), receiver is PyQtSlotProxy(0x7fd9071db840)
```

For now (see https://github.com/ilastik/ilastik/commit/d35f08a54b41d171d4ec85106363664b00756360) I made the *ConservationTrackingWorkflow* fall back to the `CommandLineProgressBarVisitor`, but we should figure out what is going on there.

**Comment by ilastikdev** [comment]
this runs  in the ilastik branch
no_crops_qt5py3
which will be erged into master as soon as qt5py3 becomes master
