### ISSUE TITLE
Missing dependencies in linux binary

### ISSUE THREAD

**Issue by david-hoffman** [ilastik/ilastik#1561]
I'm getting the following error when starting ilastik. I downloaded the binary from: http://files.ilastik.org/ilastik-1.2.2rc4-Linux.tar.bz2.

```
~/ilastik-1.2.2rc4-Linux/lib/python2.7/site-packages/PyQt4/../../../libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/lib/x86_64-linux-gnu/libproxy.so.1)
```

Perhaps something is missing from the installation instructions?

```
hoffmand@hoffmand-VirtualBox:~$ uname -a
Linux hoffmand-VirtualBox 4.10.0-26-generic #30-Ubuntu SMP Tue Jun 27 09:30:12 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by stuarteberg** [comment]
Hi David,

Please replace the following file in your ilastik binary:

```
/ilastik-1.2.2rc4-Linux/bin/remove-obsolete-libstdcxx.sh
```

with the attached version.  (Unzip it first.)
[remove-obsolete-libstdcxx.sh.gz](https://github.com/ilastik/ilastik/files/1162892/remove-obsolete-libstdcxx.sh.gz)

Let me know if that works.

**Comment by david-hoffman** [comment]
Looks good to me
