### ISSUE TITLE
`Multiple extensions` Error being raised by mistake, Linux

### ISSUE THREAD

**Issue by david-hoffman** [ilastik/ilastik#1562]
This is the output of my log file:

```
ERROR 2017-07-20 10:28:27,990 excepthooks 15240 139766296368896 Unhandled exception in thread: 'MainThread'
ERROR 2017-07-20 10:28:27,990 excepthooks 15240 139766296368896 Traceback (most recent call last):
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/ilastik-meta/ilastik/ilastik/applets/dataSelection/dataSelectionGui.py", line 723, in addStack
    info = DatasetInfo(os.path.pathsep.join(files), cwd=cwd)
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/ilastik-meta/ilastik/ilastik/applets/dataSelection/opDataSelection.py", line 119, in __init__
    "Supplied multiple files with multiple extensions"
AssertionError: Supplied multiple files with multiple extensions
```

All the files are `.tif` extensions and I've loaded the same files in my windows installation just fine.

**Comment by k-dominik** [comment]
Hi @david-hoffman ,

how did you select the files? Using the GUI and the `Add single 3D/4D volume from sequence` button?

**Comment by david-hoffman** [comment]
Yes that is correct.

**Comment by k-dominik** [comment]
Okay, and which of the options did you select? `Select Files`, `Whole Directory`, or `Specify Pattern`. Also could you please confirm that all files listed in the File List in the Create volume from image stack widget have the `.tif` extension?

**Comment by david-hoffman** [comment]
I tried both `Select Files` and `Whole Directory` both failed. All files have the `.tif` extension.

**Comment by k-dominik** [comment]
Ok the only way I can trigger that exception is when I have a with a different extension in the folder. Could you select your dataset via `Whole Directory` and paste the resulting glob string here (which will appear after selection of the directory)? You can copy it by activating the `Specify Pattern` radio button.

**Comment by david-hoffman** [comment]
`/run/user/1000/gvfs/smb-share:server=dm11,share=hesslab/Cryo_data/EM_data/17-7_20170220_CS2_Cell6/Cell6_Fiji_Align_bin2_Align_bin2 For Ilastik/Cell6_Fiji_Align_bin2_Align_bin2_crop*.tif`

**Comment by k-dominik** [comment]
Hi @david-hoffman , we cannot really reproduce your setup here (samba share mounted via gvfs?). In order to resolve this bug, it would be helpful to give you some slightly modified files to get some more debug output. Would you be willing to help us debug that problem in that way?
