### ISSUE TITLE
Excessively slow and buggy GUI experience

### ISSUE THREAD

**Issue by JRose1** [ilastik/ilastik#1569]
Hello!

I recently discovered this app while searching for graphic programs for training computer vision classification models and was blown away by the near real-time feedback of probability and classification mapping onto the image you're sampling from. However, whenever I work on a library of more than a few images (each <1 Mb) it gets to be extremely slow and basically unworkable. I have a feeling there's some fundamental aspect of interacting with the program I am misunderstanding, but could find limited documentation online.

How would I best train a model for binary or 3 class classification in ilastik's GUI, ideally having more than 10 images to sample from (Or as many as possible, scaling up to hundreds or thousands)? I figure the best way would involve training on small numbers of images and then exporting the classification on a larger number of images. If possible I would love to be able to port this GUI into other applications of ours (Likely in python) to utilize the graphical sampling potential for other models and pipelines.

Looking forward to the responses,
Thanks,
Jacob

**Comment by stuarteberg** [comment]
Hi Jacob,

Our interactive training mode can only be used with a handful of images.  As you've discovered, the internal architecture of the program is not suited for more more than that.  If you can train a sufficient classifier on relatively few images, then you can process many more using the 'batch mode' UI (or the headless command-line interface).

If you need to train interactively on many images, there is a trick you can use as a workaround, assuming your images are 2D.  Stack your images into a volume and load them as a time sequence in ilastik.  Then ilastik will treat them as a single image, and the overhead penalties you would normally pay for loading many images are not incurred.  (To label the data, you'll have to scroll through the "time steps" of your image sequence.)

For details on loading stacks and how to tell ilastik to interpret  your data as a `tyx` volume, see this page:
http://ilastik.org/documentation/basics/dataselection

-Stuart

**Comment by JRose1** [comment]
Ah thank you,

This helped quite a bit, I didn't go this route before because some of my images differed by a pixel or two. 

I'm curious what causes the difference in computation time between stacking on the time axis and the Z axis? Does this benefit also apply to HDF5 files if I initially stack the images in that format?

Lastly, where could I go for more in depth documentation on ilastik or the underlying code other than the main ilastik website or this github?

Thanks so much,
Jacob

**Comment by akreshuk** [comment]
The main difference b/w z and time stacking is that ilastik interprets z-stacks as 3D data and computes 3D features for this case. In general, it's always better to use HDF5 (with chunks), but if you activate the "save to project file" for the storage option in the same dialogue, it will happen automatically. 

Our source code is all in this github, but additional developer documentation can be found here: http://ilastik.org/development.html. We are trying to improve it as we go, but it's not really complete. If you find something interesting is missing, just ask us and we'll update the docs with the reply. The viewer in particular is mostly contained in the volumina repository, but the you'd also need the individual applet GUIs to bring it all together.

Increasing the amount of labels also increases the computational load. Think about it this way: for every brush stroke you make, we extract the block around it, compute features for it, update the random forest training input and train. If you stay within the same block/image, ilastik doesn't need to compute features again, so such a training iteration will take less time. It doesn't matter if some images do not contain all classes, but it's important that all classes are labeled somewhere in the stack with at least one pixel.

**Comment by k-dominik** [comment]
closing this as too generic. It wouldn't be clear to me when at what point of improvement this issue could be closed.
