### ISSUE TITLE
Headless Documentation - command line pixel classification w/ GUI trained model?

### ISSUE THREAD

**Issue by JRose1** [ilastik/ilastik#1573]
Hello,

I'm struggling to find adequate documentation on how to take a trained pixel classification model from the GUI workflow and apply it to new images solely using command line or python code. Does this documentation exist or can someone provide a brief explanation?

Thanks

**Comment by k-dominik** [comment]
Dear JRose1,

we have restructured our documentation a bit and obviously produced some glitches. Thank you for pointing that out. I have fixed the links to point to the proper location in the pixelClassification documentation.

You can find info about it here:  http://ilastik.org/documentation/basics/headless.html

and there are also a few examples given in the [animal tracking documentation](http://ilastik.org/documentation/animalTracking/animalTracking#tocAnchor-1-1-4)

Please let us know if the documentations is detailed enough for you, and please feel free to reopen this issue if it is not the case.

Cheers
Dominik
