### ISSUE TITLE
Curious why loading bar seems to pause on 80%

### ISSUE THREAD

**Issue by JRose1** [ilastik/ilastik#1575]
It seems every time I have ilastik reclassify in the pixel classification workflow by adding new samples of a class (Painting in a different color), ilastik seems to spend most of its time displaying an 80% loaded bar, then after a while finishes to 100% in a short instant. There's very little transparency about what is taking so long, so interested in getting the perspective of those who've spent time developing it.

Thanks,
Jacob

![80percent_ilastik](https://user-images.githubusercontent.com/25290174/29337087-ebfc5a7e-81c4-11e7-822e-e01d19a33335.PNG)

**Comment by akreshuk** [comment]
There are 2 different progress bars in pixel classification. The one with percents is for training, the one just going back and forth is for prediction. Everything up to 80% is constructing the input features/labels matrix for the classifier and afterwards it's actually training. There is no progress from training, so it jumps from 80 to 100. I suppose you are adding labels to areas which held labels before, so the features for those are already computed and this part passes very fast.

**Comment by k-dominik** [comment]
@akreshuk, should we close this, or reformulate into "add finer grained progress bars"?

**Comment by akreshuk** [comment]
Let's close and if @JRose1 has more questions it can always be re-opened
