### ISSUE TITLE
How to open Drosophila 3D+t HD5 file

### ISSUE THREAD

**Issue by lmiroslaw** [ilastik/ilastik#1580]
Dear Team,

I would like to run Ilastik in a headless mode in the Azure cloud and have no access to GUI.

Could you instruct me how to open 3D+tdrosophila_00-49.h5 file from the Drosophila.zip available on the Download page? I tried Fiji-> Import RAW (LUT) and the image gets displayed corrupted. Maybe I have to set the number of images in a stack?

I would like to visualize it and compare it with the segmentation results.

Thanks!
Lukasz

**Comment by chaubold** [comment]
You can import the files to Fiji for instance using our Import/Export plugin, see http://ilastik.org/documentation/fiji_export/plugin.

The file extension `.h5` does not describe a raw file, but one stored in HDF5 format. There are other importers for Fiji as well, but using our plugin should be the easiest way.
