### ISSUE TITLE
Deleting Label raises error about ListModel, but continues

### ISSUE THREAD

**Issue by chaubold** [ilastik/ilastik#1586]
When one has created some labels in Object Classification (or the object count classifier in tracking), and removes the last label by clicking the red cross button, ilastik pops up this nice error message:

![screen shot 2017-08-31 at 13 21 23](https://user-images.githubusercontent.com/16854/29920798-864a1350-8e4f-11e7-9421-d1317b6f0946.png)

Fun fact: the log file does not contain any more information than this message box shows.
ilastik continues without any noticeable problems, the label also disappears from the GUI.

Is there maybe something that changed in Qt5's list view?

**Comment by k-dominik** [comment]
I have just observed the same behaviour with Density Counting when deleting a box:

```
TypeError: invalid result from BoxListModel.flags(), NoneType cannot be converted to PyQt5.QtCore.ItemFlags in this context
```
