### ISSUE TITLE
"--export_object_probability_img" flag doesn't seem to do anything

### ISSUE THREAD

**Issue by markemus** [ilastik/ilastik#1590]
I'm following the instructions [here](http://ilastik.org/documentation/basics/headless#tocAnchor-1-1-3) for headless operation of an object classification workflow. The command I'm using is:

`bash ~/dev/ilastik-1.2.2-Linux/run_ilastik.sh \
--headless \
--project=./ilastik-storage/projects/hematoxylin-dab-main/segmentation.ilp \
--export_object_probability_img \
--output_format=tif \
--output_filename_format=./ilastik-storage/out/{nickname}_out.tif \
--raw_data ./ilastik-storage/in/$1 \
--prediction_maps ./ilastik-storage/out/$PROB`

According to the documentation this should export a probability image for the object classes, but instead it outputs a _prediction_ image. It does this whether I include the flag or not. I can export a probability image from this project just fine through the GUI.

I notice that the documentation is for 1.1.3- does this flag still work the way it used to? If not, is there a new way to do this? I wasn't able to find any more info about it online.

**Comment by k-dominik** [comment]
Hi @markemus ,

thank you for your report. I can reproduce the behavior. As you have pointed out, the documentation is outdated there. Although, with just a quick glance at the code, it seems that this syntax should still work.

However, in order to specify object probabilities as the output, please use the following command line by specifying `--export_source="Object Probabilities"` or any of the other layers that can be selected in the export applet:

```bash
~/dev/ilastik-1.2.2-Linux/run_ilastik.sh \
  --headless \ --project=./ilastik-storage/projects/hematoxylin-dab-main/segmentation.ilp \
  --export_source="Object Probabilities" \
  --output_format=tif \
  --output_filename_format=./ilastik-storage/out/{nickname}_out.tif \
  --raw_data ./ilastik-storage/in/$1 \
  --prediction_maps ./ilastik-storage/out/$PROB
```

please let us know if that produces the output you expect

cheers

**Comment by markemus** [comment]
Hi k-dominik, thanks for answering so quickly. 

1. It did give me a different output, but it's blank- all the intensity values in all 3 RGB channels are 0. I checked some higher channels and got an IndexError, so it's definitely blank.

Just to be sure I tried your command line input again with --export_source="Object Predictions", and it gave me the same object predictions as it did in my original attempt- ie that command works, at least.

2. I played with some settings under "Choose Export Image Settings" for the project in the ilastik GUI, and when I choose the "convert to data type: unsigned 8 bit" it exports a blank image as well. If I leave it unchecked, it exports the proper probability image. 

Is it possible that this is what the command line ilastik is doing, and if so, is there some way to tell it not to?

3. Also, is there somewhere in the code where I can see the command line options? I tried following them down the rabbit hole but they seem to go quite a long ways down. --help only includes some of them.

**Comment by k-dominik** [comment]
Hi again,

really sorry that you still don't get the output you want. May I ask what you are going to do with the data? In general we suggest exporting to `.h5` as it is the most versatile file format. If you leave the settings at default, you can import the data to ImageJ with the ilastik import/export plugin as described [here](http://ilastik.org/documentation/fiji_export/plugin). Also it would be really easy to read into python for further processing with `h5py`.

> Also, is there somewhere in the code where I can see the command line options? I tried following them down the rabbit hole but they seem to go quite a long ways down. --help only includes some of them.

If you are interested in the command line code you can find it in dataExportApplet.py:

https://github.com/ilastik/ilastik/blob/5e93792995cd989a9d2b6179bd5107718b57604e/ilastik/applets/dataExport/dataExportApplet.py#L108-L128

> It did give me a different output, but it's blank- all the intensity values in all 3 RGB channels are 0. I checked some higher channels and got an IndexError, so it's definitely blank.

> I played with some settings under "Choose Export Image Settings" for the project in the ilastik GUI, and when I choose the "convert to data type: unsigned 8 bit" it exports a blank image as well. If I leave it unchecked, it exports the proper probability image.

So the object probability image that is exported will have as many channels as object classes. They would map by coincidence to RGB if there were 3 object types. If you tell me what software you are using for further viewing I might be able to help you to find the right export settings.

Also consider the flags for `--export_dtype`, `--pipeline_result_drange`, and `--export_drange` as documented [here](http://ilastik.org/documentation/basics/headless)

If all fails and you are willing to share your project-file and some data with us, we could try it on our side.

Cheers

**Comment by markemus** [comment]
Well, I added a third object class, and that seemed to solve the problem- the headless command is now able to export a multichannel tif for the probability image with all 3 channels. 

However, there is another bug with the project that are leading me to think that it might be the particular project that has the problem- I'm getting out of bounds errors when trying to mark objects at the bottom edge of some of my images, and the predictions for those objects aren't updating. They do show up in the binary image overlay, though.

It may be my fault- I've been updating the pixel prediction images in the pixel identifier that are being used by the object classifier. Is this recommended? 

(I can open a new issue if it's a real bug and not just me being an idiot.)

--

To answer your question, we're importing the images into cellprofiler and then using them to identify objects. Unfortunately we're on Linux and don't have direct integration with ilastik. Exporting the images through the GUI was working fine- only the headless versions were coming out with zero intensity. Not the same problem as the FAQ (1.0 intensity if channels aren't separated).

Thank you for pointing me to the optional flags, those will definitely be useful. And thank you for all your help!

**Comment by k-dominik** [comment]
Hey @markemus,

the out of bounds thing sounds interesting - do you have a simple setup for us to reproduce that behavior? I don't think I have seen that one yet.

**Comment by markemus** [comment]
It's only happening with the one object identification project, as far as I can tell. But I don't think it was happening when I first made it. 

It's too large to upload here, but here's a Drive link, if you're comfortable with that.

https://drive.google.com/open?id=0B_tKDrerUtV0NTNJTENEWGQzZUk

Sorry for the delay, I've been out of the office.

**Comment by k-dominik** [comment]
Hi, thank you very much for the effort, I'll look into it.

**Comment by k-dominik** [comment]
original reported issue is fixed by updating the documentation in https://github.com/ilastik/ilastik.github.io/commit/11945720005139ba6386683c780fde2b920e1ce0

Please make a open up a new issue if these other problems still persist
