### ISSUE TITLE
Division event in manual tracking broken in 1.2.2 

### ISSUE THREAD

**Issue by jjmetzger** [ilastik/ilastik#1596]
After clicking on mother cell, clicking on daughter cell in next frame causes this error:

> Error: There is already an object with this track id in this time step

Works fine in 1.2.1.

**Comment by k-dominik** [comment]
@ilastikdev / @chaubold : is this related to the recently fixed clicking issue?

**Comment by ilastikdev** [comment]
Yes, it is working on master now.

**Comment by k-dominik** [comment]
Ok, i'll cherry-pick it into the python-2-hotfixes branch.

**Comment by chaubold** [comment]
Remember to cherry pick both, ilastik/volumina#188 and ilastik/volumina#191.

**Comment by k-dominik** [comment]
thank you @chaubold
