### ISSUE TITLE
"Supplied multiple files with multiple extensions" error

### ISSUE THREAD

**Issue by aditik37** [ilastik/ilastik#1604]
Hi, 

I just started using Ilastik, and I keep running into an error when I try to add new images to my input data that says "Supplied multiple files with multiple extensions." I tried converting to HDF5, and that didn't change anything. When I move the file to a new folder without the rest of the files, it sometimes works. For reference, the file names look like this: 
<img width="324" alt="screen shot 2017-09-27 at 12 31 22 pm" src="https://user-images.githubusercontent.com/32337594/30925431-d5b21718-a37f-11e7-9eaf-d3093a40a9c6.png"> 

Are the file names too similar? I have no computer science experience, so any help is appreciated!

**Comment by k-dominik** [comment]
Hi @aditik37 ,

are you adding files with the `Add single 3D/4D volume from sequence` button?

**Comment by aditik37** [comment]
@k-dominik I would like to add them separately

**Comment by k-dominik** [comment]
Setting aside the issue, we do not recommend adding so many images during training, [@stuartberg's comment](https://github.com/ilastik/ilastik/issues/1569#issuecomment-319205796) gives an explanation on a similar issue might help you.

Back to your original issue: How did you try to add those images? Via `Add new - add separate image(s)`?

**Comment by aditik37** [comment]
Yes, I added them through the add separate images. And I'm not planning on training on all of those images, but the images I'm training on come from the same folder as the images that I will be using the program on.

**Comment by k-dominik** [comment]
Hmmm, I tried to reproduce it couldn't really do it. Could you please give me a bit more details on your setup:

* what operating system are you using (Windows, MacOS, Linux(which flavor))
* What version of ilastik are you using?
* is the data you are working on maybe publicly available?

**Comment by NBaileyNCL** [comment]
Hi thanks for getting back so quickly.

I'm on Ubunutu Linux
Ilastik version 1.3.0
It's not publicly available data but happy to sent it if that helps

**Comment by k-dominik** [comment]
This would be very helpful indeed. Could you please make a minimal set of images available for download (e.g. via dropbox) that cause the issue and send us the dowload link to team@ilastik.org ?

**Comment by NBaileyNCL** [comment]
Yep, no problem. Link has been sent, named after issue #1604

**Comment by k-dominik** [comment]
Okay, for reference this issue seems to be related to using special characters, in particular file separators in file names.
* On _windows_ this is the semicolon `;` character,
* on _linux_ and on _mac_ this is the colon `:` character

ilastik supports those characters in file names in order to denote a list of file names. That means that those should not be used in file/folder names intended for the use in ilastik. I would even argue that it is good practice not to use them in general.

Thanks to @NBaileyNCL for providing the files that made it possible to debug.
