### ISSUE TITLE
Feature Selection: Segmentation colors don't match labels

### ISSUE THREAD

**Issue by imoutsatsos** [ilastik/ilastik#1605]
Using ilastik 1.2.2 on Windows 7 .
Segmentation colors in the 'Feature Selection' applet do not match the training labels
For example, Given the following labels and colors in live update:
![image](https://user-images.githubusercontent.com/3408226/31131858-4f972d0e-a829-11e7-93e9-3c71278dd064.png)

the applet displays them as:
![image](https://user-images.githubusercontent.com/3408226/31131891-64d4f700-a829-11e7-8b4e-c5cb21228136.png)

**Comment by akreshuk** [comment]
This is, in a way, a feature :) We contemplated switching to more colorblind-friendly label colors for a long time and the dev who did the feature selection workflow just went ahead thinking the rest will follow. But it didn't. But I hope it's still clear what the results are for different feature sets?

**Comment by imoutsatsos** [comment]
Good intentions! Thanks for the explanation, Hopefully at some point these features will no longer look like bugs ;-)
