### ISSUE TITLE
Carving function - Export Meshes error on Mac(10.11.6): global name 'vtkPolyDataWriter' is not defined

### ISSUE THREAD

**Issue by sweisernovak** [ilastik/ilastik#1613]
Hi all,

Thanks for a wonderful tool! I have been using Ilastik successfully for segmenting/carving FIB-SEM datasets on my PC without issue.

My labmate on a Mac computer has trouble exporting meshes using the carving tool. Specifically, when exporting meshes, the following error is thrown:

> global name 'vtkPolyDataWriter' is not defined

From the error log:
 
> INFO 2017-10-13 14:07:25,792 carvingGui 12950 140735116947456 Mesh generation complete.
> INFO 2017-10-13 14:07:25,793 carvingGui 12950 140735116947456 Saving meshes to /Volumes/LAB HD/SBEM from untitled folder/Ilastic projects/meshes/mitochondria.obj
> ERROR 2017-10-13 14:07:25,794 excepthooks 12950 140735116947456 Unhandled exception in thread: 'MainThread'
> ERROR 2017-10-13 14:07:25,795 excepthooks 12950 140735116947456 Traceback (most recent call last):
>   File "/Applications/ilastik-1.2.2post1-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/workflows/carving/carvingGui.py", line 524, in onMeshesComplete
>     w = vtkPolyDataWriter()
> NameError: global name 'vtkPolyDataWriter' is not defined

Do you have any ideas for resolving this issue?

Best,
Sammy WN

**Comment by stuarteberg** [comment]
I see you are using the latest stable version (1.2.2post1).  I wonder if this is recent regression, or if the previous build suffered from this problem, too.  Would you mind trying out the previous version (1.2.2)? It's also available on the [ilastik download page](http://ilastik.org/download).

As a temporary workaround, it should be possible for your labmate to share his/her project file (`.ilp` file) with you, and export the meshes on your machine, assuming it works there.

**Comment by sweisernovak** [comment]
Thanks for replying. We tried the previous version - same error.

I'll use the workaround for now.

Thanks again!
Sammy

**Comment by chaubold** [comment]
We have released a beta version 1.3 on our download page, which does not use VTK any more, so the error should no longer persist. Feel free to give it a try!
