### ISSUE TITLE
Object Classification per Region : including multilabel masks in the classification pipeline

### ISSUE THREAD

**Issue by ChrCoello** [ilastik/ilastik#1620]
HI Ilastik Team,

This issue reflects some fruitful discussions during the HBP Summit. For our application, we combine the Pixel classification (or Object classification) images with multilabel images (see attached, often RGB uint8 images) defining different subregions of the segmented image. The idea is to get statistics per region as an output. 
Cheers 
Christopher

![761_3165_4247_tg2576_m287_1d1_s022_segmentation](https://user-images.githubusercontent.com/11834181/31882435-1039dd00-b7e7-11e7-8aef-e66f7689321c.png)

**Comment by k-dominik** [comment]
Hey Chris,

thank you for taking the time to submit this issue. We'll discuss the idea and keep you posted.

Cheers
Dominik

**Comment by ChrCoello** [comment]
Thanks Dominik. This is not urgent as we have some routines doing this job in house. But if enough requests come to you for this feature, we would appreciate it to be included in Ilastik.

**Comment by akreshuk** [comment]
See also #1647

**Comment by k-dominik** [comment]
done in https://github.com/ilastik/ilastik/pull/1973
