### ISSUE TITLE
Track! unexpected keyword argument

### ISSUE THREAD

**Issue by dfberenson** [ilastik/ilastik#1628]
When I press Track! to track my image stack, I get an error: "track() got an unexpected keyword argument 'progressWindow'" that prevents it from running the tracking.

The traceback is:

ERROR 2017-10-24 16:58:10,211 log_exception 2136 7700 Traceback (most recent call last):
  File "C:\Program Files\ilastik-1.2.2post1\ilastik-meta\ilastik\ilastik\applets\tracking\conservation\conservationTrackingGui.py", line 349, in _track
    progressVisitor=self.progressVisitor
TypeError: track() got an unexpected keyword argument 'progressWindow'

ERROR 2017-10-24 16:58:10,211 log_exception 2136 7700 Error during tracking.  See above error traceback.

**Comment by chaubold** [comment]
Hi @dfberenson,
Thanks for the report! We've noticed that error already, and there is a fix in #1614, but we haven't created a new binary yet. We're planning to do that soon, we'll keep you posted!
Best,
Carsten

**Comment by jbychang** [comment]
Just wanted to give this a +1. I got the same error:

ERROR 2017-11-17 16:41:16,069 log_exception 13868 8024 Traceback (most recent call last):
  File "C:\Program Files\ilastik-1.2.2\ilastik-meta\ilastik\ilastik\applets\tracking\conservation\conservationTrackingGui.py", line 349, in _track
    progressVisitor=self.progressVisitor
TypeError: track() got an unexpected keyword argument 'progressWindow'

ERROR 2017-11-17 16:41:16,071 log_exception 13868 8024 Error during tracking.  See above error traceback.

**Comment by ilastikdev** [comment]
This has been fixed and is availabl in the new beta download,

Janez.

**Comment by chaubold** [comment]
@jbychang, thanks for the update, good to know it works for you!
