### ISSUE TITLE
Incompatibility with CPLEX 12.7.1

### ISSUE THREAD

**Issue by dfberenson** [ilastik/ilastik#1629]
I downloaded CPLEX 12.7.1 to accompany Ilastik 12.2.2 because that version of CPLEX is the only one currently available from IBM's OnTheHub store.

Ilastik failed to load the CPLEX-dependent tracking workflows, I assume due to looking for and failing to find CPLEX 12.6.3. I managed to work around this by renaming the CPLEX dll files and the Windows environment variables from 1271 to 1263 and the tracking workflows now appear, but it seems there ought to be a better solution.

**Comment by chaubold** [comment]
Hi @dfberenson, yes this is a very unfortunate situation. IBM removed the old CPLEX version from their website and changed some internals of CPLEX, which prevents us from simply re-building ilastik with CPLEX 12.7. 

We have finally updated our whole dependency stack, making life for tracking on windows a lot easier:
* most features are even available without CPLEX, it is only required if you want to learn the optimal weighting parameters from a few tracking annotations (see sections 3 and 4 at http://ilastik.org/documentation/structuredLearningTracking/structuredLearningTracking#tocAnchor-1-1-8)
* we finally build against CPLEX 12.7, and I am currently trying to also support Gurobi as an alternative on windows, which already works on Linux and Mac.

We have a first _alpha_ build that we're testing internally right now, and will hopefully release that very soon.

**Comment by k-dominik** [comment]
Similar issue: https://github.com/ilastik/ilastik/issues/1403

**Comment by chaubold** [comment]
As mentioned in #1403, we have a new ilastik beta version available for download which is built against CPLEX 12.7.1 but also allows you to run tracking completely without CPLEX (it then relies on a very good approximation).
