### ISSUE TITLE
autocontext: suggestFeatures fails to execute @ Stage 2

### ISSUE THREAD

**Issue by ilastikdev** [ilastik/ilastik#1631]
```
  File "/home/jales/software/miniconda/envs/p3-ilastik/ilastik-meta/ilastik/ilastik/applets/pixelClassification/pixelClassificationGui.py", line 489, in show_feature_selection_dialog
    self.featSelDlg.exec_()
  File "/home/jales/software/miniconda/envs/p3-ilastik/ilastik-meta/ilastik/ilastik/applets/pixelClassification/FeatureSelectionDialog.py", line 238, in exec_
    self._add_grayscale_layer(self.raw_xy_slice, "raw_data", True)
  File "/home/jales/software/miniconda/envs/p3-ilastik/ilastik-meta/ilastik/ilastik/applets/pixelClassification/FeatureSelectionDialog.py", line 554, in _add_grayscale_layer
    self.editor.dataShape = list(data_shape)
  File "/home/jales/software/miniconda/envs/p3-ilastik/ilastik-meta/volumina/volumina/volumeEditor.py", line 136, in dataShape
    self.parent.volumeEditorWidget.quadview.ensureMinimized(i)
AttributeError: 'FeatureSelectionDialog' object has no attribute 'volumeEditorWidget'

```

suggestFeatures does execute @ Stage 1

**Comment by ilastikdev** [comment]
fixed in 
https://github.com/ilastik/ilastik/pull/1632

**Comment by chaubold** [comment]
I cannot reproduce that error. I created a new autocontext workflow and ran feature selection in both stages and there was no problem at all. Is there anything special that I need to do?

I assume your `volumina` branch is up to date as it hasn't changed for over a month.

**Comment by ilastikdev** [comment]
Run a 3d+t dataset

**Comment by chaubold** [comment]
I tried 2D, 3D and 3D+t now, and it works perfectly everywhere, even without your fix...

**Comment by ilastikdev** [comment]
Lines that fail are 135-136:

            for i in range(3):
                self.parent.volumeEditorWidget.quadview.ensureMinimized(i)

in volumeEditor.py

which clearly fail if called from FeatureselectionDialog.py

because of conflicting

            self.viewer = volumeEditorWidget.VolumeEditorWidget()

The error is triggered when dataShape is called.

**Comment by chaubold** [comment]
Yes, I saw that in your traceback. But it just doesn't occur for me, so I was wondering when you ran into this issue, or basically: what did you have to do as a user so that `dataShape` is called?

**Comment by ilastikdev** [comment]
resize the view - zoom in and out

**Comment by chaubold** [comment]
Nope, works fine all the time.

Another thing I don't get is why `dataShape` would be called only in the 2nd stage of autocontext? I think this should either fail all the time, or not at all.

**Comment by ilastikdev** [comment]
another problem is

**Comment by chaubold** [comment]
Hmm, `feature selection dialog` doesn't even show a quadview for me, and it doesn't allow me to switch to the quadview because that HUD-button is missing. @akreshuk is that the way it's supposed to be?

**Comment by ilastikdev** [comment]
sorry, the data was 2d+t and the feature dialog displays it as 2d+t at the first stage and
3d (xyz) in the second stage, which also problem 
see #1633

**Comment by akreshuk** [comment]
@chaubold , yes, it's supposed to be like this to avoid predicting too much. I think it always shows the xy view. We could probably customize it to show any of the 3d views, but i'm not sure it's worth the trouble.

**Comment by k-dominik** [comment]
Just fyi, I can reproduce the issue. All you need is a 2D image an train more than 3 classes in the first stage.
