### ISSUE TITLE
display problem in batch prediction

### ISSUE THREAD

**Issue by czhci** [ilastik/ilastik#164]
![batch_display](https://f.cloud.github.com/assets/3789738/249417/79f7f38a-8b2d-11e2-89eb-307cfec02b34.png)

The above screenshot shows the display after batch prediction started. The same pattern was observed in both Linux and Windows versions. But this seemed to be resolved after a LONG while, i.e. the strip pattern was gone, which might be a refreshing bug??

However, the enable/disable functionality of displaying different layers of the batch predicted results seems to be dis-activated.

**Comment by stuarteberg** [comment]
The "simple pattern" shown and explained above has been removed from the UI.  If the on-disk data isn't ready, that layer is simply omitted from the layerstack.
