### ISSUE TITLE
Atlas Registration/ Region-Specific Quantification Support 

### ISSUE THREAD

**Issue by JLluck** [ilastik/ilastik#1647]
Hellow ilastik team, 

I got a walkthrough of your software from the QuickNII team at SfN and loved what I saw. I request that you work with them to implement the ability for atlas region-specific cell counting as a part of the pipeline. This is a huge issue in neuroscience research and combining your two platforms to allow for region-specific quantification of cells will be an important tool for many neuroscientists by increasing the repeatability of their work and dramatically increasing the throughput of histological processing of regions outside of a researcher's expertise.

**Comment by akreshuk** [comment]
Thanks for your feedback, this project is on our todo list!

**Comment by k-dominik** [comment]
done in https://github.com/ilastik/ilastik/pull/1973
