### ISSUE TITLE
Warnings when creating a PixelClassification project

### ISSUE THREAD

**Issue by holstgr-kaust** [ilastik/ilastik#1655]
Warnings when creating a PixelClassification project (after loading Volume / Sequence from a Z ordered stack of PNGs):
```
QObject::connect: Cannot queue arguments of type 'QVector<int>'
(Make sure 'QVector<int>' is registered using qRegisterMetaType().)
QObject::connect: Cannot queue arguments of type 'QVector<int>'
(Make sure 'QVector<int>' is registered using qRegisterMetaType().)
QObject::connect: Cannot queue arguments of type 'QVector<int>'
(Make sure 'QVector<int>' is registered using qRegisterMetaType().)
```
Other than that, PixelClassification appeared to work fine.

ilastik-1.3.0b2-Linux on CentOS 7 (installed via Downloaded tarball)

**Comment by k-dominik** [comment]
Thanks for reporting that issue.

I looked into it and could not find the cause. However I want to document that this error only occurs if an internal dataset (internal to the project file) is loaded (stacks are first imported to the project file and then loaded from there).
