### ISSUE TITLE
2D data from h5 files

### ISSUE THREAD

**Issue by k-dominik** [ilastik/ilastik#1662]
When trying to read data from `h5` files, we only look for datasets with `3 <= dimenisonality <= 5` (see snippet from `DataSelectionGui`below).
Sure this is easily altered, but I was wondering if we had a reason exclude data with `dimensionality == 2`.

https://github.com/ilastik/ilastik/blob/d23d3e5e708fe2a72aa83b9ae566e05f14d894df/ilastik/applets/dataSelection/dataSelectionGui.py#L699-L700

for further reference, there is a function with similar functionality in `lazyflow.utility.pathHelpers.lsHdf5`

**Comment by akreshuk** [comment]
I believe vigra always adds channels, even when reading 1-channel data from pngs and such. So there can be assumptions about data having channels all over the place. If we allow for reading 2D (and I think we should), we should also add a singleton channel dimension upon reading.
