### ISSUE TITLE
Example script for hdf5 export from python

### ISSUE THREAD

**Issue by votti** [ilastik/ilastik#1682]
As part of our python based image processing pipeline we would like to export our data directly into the hdf5 format to increase the Ilastik performance. In the Documentation you suggest to "Write a custom script in Python using the h5py library" to do so - would you have an example script to share how to do this around or more detailed specifications about the hdf5 file format Ilastik uses as an input?
Maybe I looked at the wrong places but I couldn't find this anywhere.

**Comment by jbychang** [comment]
I've been cribbing off of the scripts available in [https://github.com/ilastik/ilastik/tree/master/bin]. In particular, [https://github.com/ilastik/ilastik/blob/master/bin/combine_channels_as_h5.py] may be useful.

**Comment by votti** [comment]
Awesome, thanks for pointing me to these scripts! They explain the process well enough.
I was quite sure that there should be some good example around but just did not look at the right places.
Cheers!
