### ISSUE TITLE
Error headless mode Windows 10

### ISSUE THREAD

**Issue by ricaliari** [ilastik/ilastik#1683]
Hello,
First of all thanks for the very nice software.
It's maybe a newbie question but I could not find any similar issue with a reply.
I am running a pixel classification/animal tracking pipeline which works quite well in GUI mode in a test run and I'd like to run headless for my entire experiment.
However, I cannot run ilastik in headless mode with Windows 10. Even just calling  "C:\PROGRA~1\ilastik-1.3.0b4\run-ilastik.bat --headless" will not run and return:

Loading ilastik from "C:\PROGRA~1\ILASTI~1.0B4\ilastik-meta"
INFO ilastik_main: Starting ilastik from "C:\PROGRA~1\ILASTI~1.0B4".
WARNING __init__.py(15): UserWarning: Couldn't import IIBoost classifier.
Starting ilastik from "C:\PROGRA~1\ILASTI~1.0B4".
INFO lazyflow.operators.vigraOperators: Using fast filters.
WARNING _bootstrap.py(219): ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
WARNING _bootstrap.py(219): ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
WARNING _bootstrap.py(219): ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
WARNING func_inspect.py(53): DeprecationWarning: invalid escape sequence \<
WARNING _memory_helpers.py(10): DeprecationWarning: invalid escape sequence \s

Any ideas on what is causing the error is much appreciated.
thanks!

**Comment by jbychang** [comment]
It doesn't immediately seem like something's wrong to me. I think Ilastik is starting and quitting because it doesn't have anything to do. 

Check out the docs here:

http://ilastik.org/documentation/basics/headless

Also, I put up some example commands to run an Ilastik tracking project in headless mode here:

https://github.com/ilastik/ilastik/issues/1519

**Comment by ricaliari** [comment]
Hi @jbychang . Thanks for the reply.
I was getting the same while trying to run the pixel classification, but It was indeed a mistake of mine. I was running from R and had problems with the correct syntax. Running from cmd works like a charm.
thanks again.
