### ISSUE TITLE
Any way to obtain area of image that is being sent through density counting workflow?

### ISSUE THREAD

**Issue by nbachelder** [ilastik/ilastik#1694]
I am using the density counting workflow to quantify cells in about 40 slides. The end goal; having uniform comparable measurements(area which I could then calculate and compare density) from the different samples in order to compare and rank the 40 images. The tissue slice on each slide is a different size and I was wondering if there was any way through this workflow, or another in the program that would be able to measure the area of the sample being counted. If not, is there another program people would suggest to measure the area of an image?

**Comment by k-dominik** [comment]
Hi,

I am not sure I understand you correctly, but it seems you could do foreground (Tissue Slice) vs Background (everything else) classification using the [Pixel Classification Workflow](http://ilastik.org/documentation/pixelclassification/pixelclassification) and then count the foreground pixels in the resulting image.

Do you think that would do the trick? Or did I misunderstand your problem? In that case an example image might help.

Cheers

**Comment by k-dominik** [comment]
Hey @nbachelder ,

i'm closing this issue for now, but feel free to reopen it if you need more input
