### ISSUE TITLE
Option to embed raw data

### ISSUE THREAD

**Issue by nickholway** [ilastik/ilastik#1695]
It would be nice to have the option to be able to embed raw data in project files. This would make it much easier to pass projects onto collaborators and make it a bit easier to keep your files in order.

**Comment by k-dominik** [comment]
Hey @nickholway,

this is already possible in the "Data Selection Applet" (the first one in the worklfow). After adding your data, right click on the row in the table to open the dataset properties. Under "Storage" you can select "Copied to Project File". Note, that the project has to be saved after that.

See also http://ilastik.org/documentation/basics/dataselection

**Comment by nickholway** [comment]
Great, thank you :)

**Comment by k-dominik** [comment]
np
