### ISSUE TITLE
Can't click "calculate tracking weights" button in tracking with learning

### ISSUE THREAD

**Issue by jbychang** [ilastik/ilastik#1708]
Hi folks,

I've now managed to train about 18 tracks using the tracking with learning workflow, but when I get to the "Tracking – Structured Learning" applet, the "Calculate Tracking Weights" button is grayed out. Any ideas on why this is?

Do I perhaps have to manually label every object in my file?

Thanks,
Jeremy

**Comment by akreshuk** [comment]
Hi Jeremy,
You don't have to manually label every object. Sometimes (rarely :)) the graying out part misfunctions, try just saving the project and opening it again, maybe the button will re-enable itself. But the most likely explanation is the lack of solvers, do you have CPLEX or Gurobi installed with steps as described here: http://ilastik.org/documentation/basics/installation.html#cplex-setup? The learning part requires commercial solvers, but once it's trained you can use it on a machine without solvers too. Also, regular automatic tracking, without learning, works without solvers.

Hope this helps, 
Anna

**Comment by jbychang** [comment]
Thanks, Anna. I suspect the problem, then, is that I have CPLEX 12.6.3 installed. I believe you guys are using 12.7.1. Amazingly, IBM has already upgraded their CPLEX version to 12.8, and 12.7.1 is no longer available for download (at least that I could find). 

Here's a related thread for reference:
https://github.com/ilastik/ilastik/issues/1629

I will contact IBM to see if they will let me download 12.7.1. They've helped me in the past.


Best,
Jeremy

**Comment by ilastikdev** [comment]
gurobi 752
