### ISSUE TITLE
Label import dialog error

### ISSUE THREAD

**Issue by anjalitaneja94** [ilastik/ilastik#1713]
@stuarteberg was showing me some ilastik basics, and we ran into the following error when attempting to use the label import UI:

```
ERROR 2018-02-23 17:19:11,925 excepthooks 6949 140371587098368 Unhandled exception in thread: 'MainThread'
ERROR 2018-02-23 17:19:11,925 excepthooks 6949 140371587098368 TypeError: invalid result from _QAxesValidator.validate()
```

He says this is probably related to some difference between Qt4 and Qt5.

Steps to reproduce:

Export a 3D `tyx` label volume, and then attempt to import those labels into a different project, this time as `zyx`.

**Comment by stuarteberg** [comment]
Note: The error occurs when you attempt to edit the axis-order box in that label import window.

**Comment by stuarteberg** [comment]
Update: @erhanbas just ran into this issue, too.

**Comment by akreshuk** [comment]
It got so annoying I fixed it myself
