### ISSUE TITLE
Need to upgrade CI files

### ISSUE THREAD

**Issue by stuarteberg** [ilastik/ilastik#1715]
Circle-CI is sunsetting their support for their old '1.0' API.  We need to upgrade to 2.0 (or switch to Travis-CI):

https://circleci.com/sunset1-0/

**Comment by k-dominik** [comment]
Okay, thank you for raising this issue. We need to switch until end of August 2018

**Comment by k-dominik** [comment]
Does anyone (@akreshuk ?) still remember why we have switched from travis to circleci? We might as well switch back if we have to touch or CI.

**Comment by k-dominik** [comment]
Apparently they have a [tool](https://circleci.com/docs/2.0/config-translation/) to help with switching. I gave it a go and arrived at a [running configuration](https://github.com/k-dominik/ilastik/blob/circle-switch-to-2/.circleci/config.yml) within 10-20 minutes. Of course this does not use any of the new features of circlCI2.0, but it keeps us in the game

**Comment by akreshuk** [comment]
I really have no idea why we switched. I guess it was more convenient. Let's switch back then.

**Comment by k-dominik** [comment]
done
