### ISSUE TITLE
3D volume slices out of order??

### ISSUE THREAD

**Issue by blaiseMibeck** [ilastik/ilastik#1718]
I am just beginning to use Ilastik on 3D data sets. After loading a microCT scan as a image sequence of 16bit tifs, I believe Ilastik is swapping sections of silices out of order. I am opening up my .dcm images in imageJ, cropping the volume and exporting as a tif sequence. In Ilastik I am loading as either a directory with images or selecting the images and being sure to use the z- projection choice. It doesn't happen every time so it is most likely my computer. I am in the process of freeing up memory to see if that helps. Is there anything I should be doing differently?

**Comment by akreshuk** [comment]
Hi, I thought I replied, but looks like it only went by e-mail and not here. Make sure you are saving your slice sequence with enough value numbers. Remember that by most automatic ordering schemes "slice10.png" will come before "slice2.png", so make sure you save it as "slice 02.png". If that is not the problem, could you send us the list of file names? Perhaps there is some other ordering malfunction.

**Comment by blaiseMibeck** [comment]
Sorry for the delay -- I decided to install the latest version of Ilastik and have not experienced the same problem. I will let you know if it happens again. Thanks!

**Comment by blaiseMibeck** [comment]
I know it was not a numbering issue as I use the original file names, and this weirdness looked like four large continuous blocks were swapped. I should have tried to duplicate it, but had no time.

**Comment by k-dominik** [comment]
okay, not sure this issue is still relevant. The stack import images out of order (depending on click sequence
