### ISSUE TITLE
CircleCI build not working

### ISSUE THREAD

**Issue by k-dominik** [ilastik/ilastik#1724]
This issue will also pop up in lazyflow and volumina. Since our rebuild with gcc5 we require a newer version of glibcxx. So, on circleci, with ubuntu 14.04 the following error occurs:

See [here](https://packages.ubuntu.com/search?keywords=libstdc%2B%2B6) for ubuntu/gcc versions

```
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/ubuntu/miniconda/envs/test-env/lib/python3.6/site-packages/vigra/vigranumpycore.so)
```

Possible solution: we need to install/ship gcclib from conda. Currently the latest version available there is `7.2.0`. I gave it a go on circleCI and it seems to work.

@stuarteberg do you see any potential harm in doing that?
And am I wrong if I assume that adding this dependency to our packages (meh!) would also make the release run on older linux distro versions?

**Comment by stuarteberg** [comment]
>Possible solution: we need to install/ship gcclib from conda. ... do you see any potential harm in doing that?

It should work, unless someone's system includes a NEWER version of `libgcc`, in which case our version might "hide" that newer version.  This has bitten us in the past:

https://github.com/ilastik/ilastik-build-conda/issues/24

But version `7.2.0` sounds quite recent, so maybe it's not an issue.  When it eventually becomes a problem, i suppose we can try this old script we used previously for this problem:
https://github.com/ilastik/ilastik-build-conda/blob/python-2/libgcc/remove-obsolete-libstdcxx.sh

>And am I wrong if I assume that adding this dependency to our packages (meh!) would also make the release run on older linux distro versions?

No, I think you're right; it would work, as long as `glibc` is not an issue.  That one can't be installed via `conda`, so the only option is to build on an old OS (in a container), using "new" compilers (from conda).

But! In the case of Ubuntu 14 specifically, there may be a fix that can be applied by the user that avoids this whole issue.  Apparently the specific missing symbol error you referenced above (`GLIBCXX_3.4.20`) can be fixed via `apt-get`.

https://askubuntu.com/questions/575505/glibcxx-3-4-20-not-found-how-to-fix-this-error

So if there aren't any other "old" distros we care about, maybe that will suffice?
