### ISSUE TITLE
AssertionError during automatic tracking merger resolution

### ISSUE THREAD

**Issue by jbychang** [ilastik/ilastik#1726]
Hi folks,

Commonly, when I run an automatic tracking project in Ilastik 1.3.0, I get an Assertion Error during the merger resolution phase. I'm attaching the error message below.

I've noticed also that if I update the division classifier, it changes which files produce a tracking error. E.g. I have two movies I want to track, and depending on the division classifier, neither/one/both of the movies will produce the error.

Best,
Jeremy

INFO 2018-04-03 17:13:23,205 opConservationTracking 13360 19588 Resolving mergers.
ERROR 2018-04-03 17:13:25,145 log_exception 13360 19588 Traceback (most recent call last):
  File "C:\Program Files\ilastik-1.3.0\ilastik-meta\ilastik\ilastik\applets\tracking\conservation\conservationTrackingGui.py", line 346, in _track
    progressVisitor=self.progressVisitor
  File "C:\Program Files\ilastik-1.3.0\ilastik-meta\ilastik\ilastik\applets\tracking\conservation\opConservationTracking.py", line 504, in track
    resolvedMergersDict = self._resolveMergers(hypothesesGraph, model)
  File "C:\Program Files\ilastik-1.3.0\ilastik-meta\ilastik\ilastik\applets\tracking\conservation\opConservationTracking.py", line 297, in _resolveMergers
    mergerResolver = IlastikMergerResolver(originalGraph, pluginPaths=self.pluginPaths, withFullGraph=withFullGraph)
  File "C:\Program Files\ilastik-1.3.0\lib\site-packages\hytra\core\ilastikmergerresolver.py", line 44, in __init__
    self._createUnresolvedGraph(divisionsPerTimestep, self.mergersPerTimestep, mergerLinks, withFullGraph)
  File "C:\Program Files\ilastik-1.3.0\lib\site-packages\hytra\core\mergerresolver.py", line 102, in _createUnresolvedGraph
    addNode(n)
  File "C:\Program Files\ilastik-1.3.0\lib\site-packages\hytra\core\mergerresolver.py", line 94, in addNode
    assert(not division)
AssertionError

ERROR 2018-04-03 17:13:25,145 log_exception 13360 19588 Error during tracking.  See above error traceback.

**Comment by ilastikdev** [comment]
Hi Jeremy,

Our tracking code does not allow dividing mergers.
So one (or more) of your mergers are classified as dividing cells.
Go back to your division classifier and make sure your mergers have a low probability of being a division. Recently added Uncertainty Layer should help you with this, you can also right click on an object and display probabilities for it in the shell you are running ilastik from.

In general, you should use the Uncertainty Layer to classify well both, the division and object count classifier, as explained in the documentation.

Having probabilities [not a division, division]=[.49,.51]
for a merger will throw this assert.

We will expand on the feedback here in the future releases...

**Comment by jbychang** [comment]
Thank you for the information! I will try it out and get back to you/close the issue.


Best,
Jeremy

**Comment by jbychang** [comment]
I trained the division classifier (and object count classifier) more, and this resolved the issue. Thanks!

**Comment by ilastikdev** [comment]
solved in hytra PR:
https://github.com/chaubold/hytra/pull/33

**Comment by k-dominik** [comment]
closing this as indeed a more informative error message is now presented to the user. Not that it is particularly good UX...
