### ISSUE TITLE
Failed to export - No conversion path for dtype: dtype('<U')

### ISSUE THREAD

**Issue by taebong** [ilastik/ilastik#1730]
Hello,

I'm writing as I have an issue with exporting Object classification results. When I try to export, ilastik gives me the following error:

![image](https://user-images.githubusercontent.com/14115580/38571330-335729bc-3cbe-11e8-8073-5ed3478bd184.png)

May I ask for a solution for this issue?

Thank you,
Tae

**Comment by akreshuk** [comment]
Closing, please re-open if the issue reappears

**Comment by Xqua** [comment]
I have a similar issue when using Tiff or h5 files with uint16 on 1.3.0
