### ISSUE TITLE
Discard redundant channels in gray RGB images

### ISSUE THREAD

**Issue by FredHamprecht** [ilastik/ilastik#174]
Gray images are often stored as RGB, using three channels instead of one. This leads to too many features being computed. I suggest checking input in that sense. 

In a similar vein, a purely monochrome (say, red) image also wastes two channels; however, this is a rare use case compared to the former; and users may want to see their "red" raw data as "red".

**Comment by akreshuk** [comment]
This shouldn't be done automatically, but presented as an option to select only one channel
