### ISSUE TITLE
Cannot Export All Using Pixel Classification + Object Classification Module

### ISSUE THREAD

**Issue by caticoa3** [ilastik/ilastik#1745]
Running on Ubuntu 16.04
#### Pixel Classification + Object Classification Module
Input Data: Multiple grayscale fluorescent microscopy images.
Feature Selection: All selected from 0.7 to 1.6 sigma
Trained Pixel Classification: 2 labels - background and cells
Thresholding: Simple, default settings, except size min. was set to 250
Performed Object Feature Selection with two labels. 

Object Information Export failed with default settings and exporting to tiff. 

"Failed to generate export file: 
/mnt/....Hippocampal Astro/ML/3a.1  CY3 2_IC_Pixel Probabilities.h5/exported_data
list index out of range"

Followed by one message for each image's data that was to be exported:

"Failed to generate export file: 
/mnt/....Hippocampal Astro/ML/3a.1  CY3 2_IC_Pixel Probabilities.h5/exported_data
No conversion path for dtype: dtype('<U')"

**Comment by mthaak** [comment]
I got this "list index out of range" error only for images in which no objects could be detected. It works for me in images where there are objects visible. Perhaps the cause is that after the Thresholding step not a single pixel is classified as positive for images without objects.

**Comment by k-dominik** [comment]
Thank you for the hint @mthaak !
