### ISSUE TITLE
opening a project that worked before the last PR (yesterday)

### ISSUE THREAD

**Issue by ilastikdev** [ilastik/ilastik#1751]
... leaves views white (for all applets) in the pixel classification workflow.

**Comment by ilastikdev** [comment]
Symptoms are the same in tracking with learning, so it is most likely workflow independent.

**Comment by k-dominik** [comment]
uh wow, how could that not be picked up by the tests... log is also silent about it. Good that you found it that early!

**Comment by ilastikdev** [comment]
volumina was not properly updated
it works now

**Comment by k-dominik** [comment]
even better!
