### ISSUE TITLE
Unable to read tracking results with Mamut

### ISSUE THREAD

**Issue by wolny** [ilastik/ilastik#1755]
After exporting the tracking results with the Fiji/Mamut XML format (Source: Plugin -> Fiji/Mamut), Mamut is not able to correctly parse the XML file:
![trackingmamutexpot](https://user-images.githubusercontent.com/706781/40058464-80c5e180-5851-11e8-92a9-e044b8696b0a.png)

**Comment by chaubold** [comment]
Mamut does properly parse the XML file, but BigDataViewer doesn't know how to load the `ilastik.hdf5` format. I wrote an extension to BigDataViewer to make it understand our single-volume HDF5 (they store different mipmap levels, timesteps etc in separate volumes). That bit is contained in the old ilastik-Filji-Plugin (see https://github.com/Beinabih/ilastik-Fiji-Plugin/tree/master/src/main/java/org/ilastik/bdvextension). I meant to port that folder over to ilastik4ij, but never got to do it. Maybe that's a good next step for Ashis?

**Comment by wolny** [comment]
Fixed: https://github.com/ilastik/ilastik/pull/1831

**Comment by k-dominik** [comment]
normaly, you can just write
fixes #1755
in your __PR__. Once this is merged (and thus, the issue really fixed) the issue will be closed autogically

**Comment by hoffmannjordan** [comment]
I am having this problem. What is the protocol for fixing it?

**Comment by wolny** [comment]
@hoffmannjordan you can either wait for the new ilastik release, where the problem has been fixed (see: https://github.com/ilastik/ilastik/pull/1831) or alternatively you can edit the `*_mamut.xml` you've exported from ilastik and change the following line:
```
<ImageData filename="<path_to_MaMuT_bdv.xml_file_exported_from_ilastik>" folder="<export_dir>" height ="0" ...  />
```
to
```
<ImageData filename="<path_to_bdv.xml_file_exported_from_fiji>" folder="<export_dir>" height ="0" ...  />
```
Where `path_to_bdv.xml_file_exported_from_fiji` is the path to your BigDataViewer XML file.
If you don't have your dataset exported in BigDataViewer format you may do so with `Plugins > Fiji > Export Current Image as XML/HDF5` in Fiji.
