### ISSUE TITLE
Object classification: changing the colors of the labels is not reflected in the central widget

### ISSUE THREAD

**Issue by wolny** [ilastik/ilastik#1759]
After changing the label coloring in the 'Object Classification' applet, it's not reflected in the central widget while labeling the objects, see below:
![objclasslabels](https://user-images.githubusercontent.com/706781/40059732-27117c90-5855-11e8-9a7f-eafc4a13e31c.png)

**Comment by m-novikov** [comment]
Resolved by https://github.com/ilastik/ilastik/pull/1723
