### ISSUE TITLE
Error when importing different flavors of nifty (plane/cplex/gurobi)

### ISSUE THREAD

**Issue by FynnBe** [ilastik/ilastik#1764]
The error `generic_type: type "LogLevel" is already registered!` is raised, when different flavors of nifty are imported. In carving (plane) nifty is used, in multicut nifty_with_cplex or nifty_with_gurobi or (plane) nifty.
This is the same behavior was previously observed when importing nifty_with_cplex fails (due to missing CPLEX) and then trying to import nifty_with_gurobi (fixed by testing import in subprocess)

Reproduce the error with any two of the following lines:
```
import nifty
import nifty_with_cplex 
import nifty_with_gurobi 
```

Suggestions to fix it:
- use same nifty flavor in carving (requires some code changes. due to different defaults? directed vs undirected graph?)
- update nifty to allow for mutliple flavor imports
- update nifty in a way that makes different flavors compatible (if that is not already the case)

**Comment by k-dominik** [comment]
we have removed the solver variants of nifty, closing.
