### ISSUE TITLE
QGtkStyle could not resolve GTK -- Ubuntu 18.04

### ISSUE THREAD

**Issue by memphizz** [ilastik/ilastik#1768]
menus missing text when running v1.3.0 on ubuntu 18.04. Here is the error message:
QGtkStyle could not resolve GTK. Make sure you have installed the proper libraries.

**Comment by akreshuk** [comment]
we haven't tried 18.04 yet, thanks for the report!

**Comment by memphizz** [comment]
I got the same error on xfce4 desktop manager.

loading themes seems to be the issue? I found this:
https://github.com/NixOS/nixpkgs/issues/15926
does it apply to ilastik? let me know if there is a workaround

**Comment by k-dominik** [comment]
I see the same error message running ilastik on vanilla ubunutu 18.04.

You could try adding

```
export QT_STYLE_OVERRIDE=gtk2
```

in your `.bashrc` file. That way the text in the menus is readable again. We'll further investigate this to come up with a proper fix

**Comment by memphizz** [comment]
The text is now readable. Thank you.

**Comment by alimoges42** [comment]
Hi all, any updates on this? I encountered the same error when trying to run a python script for a QT-based GUI. The script crashed initially with the same error, so I modified my .bashrc file as suggested. The modifications at least restored some functionality, but my machine's GUI is nowhere near as clean as my colleague who is running Ubuntu 16.04.

**Comment by NDJV** [comment]
I'm also having this issue

**Comment by leoyip** [comment]
> Hi all, any updates on this? I encountered the same error when trying to run a python script for a QT-based GUI. The script crashed initially with the same error, so I modified my .bashrc file as suggested. The modifications at least restored some functionality, but my machine's GUI is nowhere near as clean as my colleague who is running Ubuntu 16.04. I realize my issue is not ilastik-specific, just curious if anyone has found the perfect workaround, and also curious if this issue has been passed on to the appropriate team. Thanks.

Same problem in Ubuntu 18.04, when I tried to run a software named "synergy".

**Comment by juliomateoslangerak** [comment]
Same issue when running on Fedora 29.
I get twice the error:
QGtkStyle could not resolve GTK. Make sure you have installed the proper libraries

Running 'export QT_STYLE_OVERRIDE=gtk2' befor eexecution solves the problem of showing the contents of the menus and the error message is shown only once.
