### ISSUE TITLE
Pixel classification: Exporting labels only exports some (very few) of the labeled pixels

### ISSUE THREAD

**Issue by markemus** [ilastik/ilastik#1784]
I've tried this in ilastik 1.3.0 and 1.2.2. The images I'm posting are from 1.2.2, but they are very similar to what happened in 1.3.0. I also tried using both the "labels" option in the Prediction Export applet as well as right clicking on the "labels" layer in the Training applet and selecting "export".

![real labels](https://user-images.githubusercontent.com/28574774/41311643-d5391afe-6e52-11e8-85d7-2f7218291c75.png)

Real labels' appearance in ilastik.

![exported labels according to ilastik](https://user-images.githubusercontent.com/28574774/41311647-dbb8cc44-6e52-11e8-81d8-7526338b5f14.png)

Exported labels according to Ilastik- hard to see but those few pixels match the actual export.

![appearance of the exported labels](https://user-images.githubusercontent.com/28574774/41311397-271bba9e-6e52-11e8-876d-0b0b3795bd10.png)

After normalization and with a colormap applied in matplotlib.

![labels image export](https://user-images.githubusercontent.com/28574774/41311253-bd361f84-6e51-11e8-83d4-1e169298e16e.jpg)

Actual exported labels (as jpg, I tried png as well).

**Comment by k-dominik** [comment]
Hey @markemus, I quickly tried this out with 1.3.0 on linux. and it seems to work for me. Apart from that, _png_, and especially _jpg_ are not ideal export formats for further processing. We always suggest exporting to _hdf5_, which can easily be read in python with `h5py`. But this is just a side note. The question now is, how we can solve your problem.

* Does something notable show up on the command-line, or in the log during the export?
* Could you send us a project-file to team@ilastik.org with which this kind of behaviour appears for you?

**Comment by markemus** [comment]
Nope, nothing on the command line. I tried recreating this in a new project file from the same ilastik install of 1.2.2 and it exported the labels without any issues. I'm attaching one of the projects with the issue here.

[MyProject2.ilp.tar.gz](https://github.com/ilastik/ilastik/files/2103376/MyProject2.ilp.tar.gz)

I just discovered by accident that it exports the labels just fine if you renormalize [min/max] from 0,2 to 0,255 (under Transformations in Choose Export Image Settings). Very strange.

**Comment by markemus** [comment]
Okay, I managed to recreate it by creating a project in 1.2.2, loading it in 1.3.0 and exporting the labels. Only a few pixels were exported, but normalizing made it export all of them. I must have done that by accident somehow. 

Mystery solved, sorry for the trouble :/
