### ISSUE TITLE
How does the pixel classification work on 3D image? 

### ISSUE THREAD

**Issue by hanginzer** [ilastik/ilastik#1787]
How does the pixel classification work on 3D images?  Does it use x, y, z planes separately to compute classification and then combine computed a probability value for a voxel?

**Comment by k-dominik** [comment]
Background: 2D images are composed of _pixels_, the (usually) square elements of digital images. In 3D there is the notion of [_voxels_](https://en.wikipedia.org/wiki/Voxel) - cubic elements of digital volumetric images.

For 3D images, we compute the features (input for the classifier) for each voxel (volumetric pixel). As we then classify 3D voxels directly, there is no need to handle the planes separately. You can read more about the feature computation in [Sommer2011](https://www.researchgate.net/profile/Christoph_Sommer2/publication/224241106_Ilastik_Interactive_learning_and_segmentation_toolkit/links/54098ff70cf2822fb7397f70/Ilastik-Interactive-learning-and-segmentation-toolkit.pdf).

**Comment by hanginzer** [comment]
Thank you very much for your answer.
Generally, I think the appearance of slices are widely changed if you change the angle of the plane to slice. So I was wondering if we tilt the 3D image and input them to Ilastik, the probability value of voxels changes? (But based on your explanation that 3D voxels are directly classified, the the probability value of voxels are not changed?)

**Comment by k-dominik** [comment]
yes, the probability value is the same no matter from which direction you look at an individual voxel. This is also true for the original image values.

**Comment by hanginzer** [comment]
thank you so much.
