### ISSUE TITLE
Read/write N5 format

### ISSUE THREAD

**Issue by clbarnes** [ilastik/ilastik#1788]
A few labs at Janelia have started using [N5](https://github.com/saalfeldlab/n5) for large tensor datasets. They're much more scalable than HDF5, especially with sparse data (e.g. realising only a small block of a much larger volume), and obviously better for volumetric processing than image stacks. There is a C++-backed python API rapidly approaching 1.0 release in [z5py](https://github.com/constantinpape/z5), the interface of which is largely consistent with `h5py`. Zarr is a similar format also supported by `z5py`.

**Comment by k-dominik** [comment]
Hey @clbarnes thanks for the heads-up! We have [experimented](https://github.com/ilastik/ilastik/pull/1677) with z5 in December last year. Seems like a good time now to add the reading/writing functionality!

**Comment by clbarnes** [comment]
I've just tried installing them in the same environment and ilastik depends on an older version of boost than z5py does, that's probably the first thing to look at.

**Comment by constantinpape** [comment]
Note that re-compiling with an older boost version is not an issue (though the version needs to be >= 1.63 for compatibility with boost::filesystem).
The boost version needs to be fixed though, otherwise the boost shared libraries will not be found properly.

**Comment by clbarnes** [comment]
It looks like ilastik is already using 1.63 so that's fine.

**Comment by constantinpape** [comment]
Just FYI, I fixed all the issues for release 1.0 (including fixing some performance issues and implementing support for all compression libraries supported by n5).
Now we only need to provide builds for mac and win ....
