### ISSUE TITLE
Is it possible to import label images to do pixel classification?

### ISSUE THREAD

**Issue by hanginzer** [ilastik/ilastik#1791]
Now I am manually labeling images to do pixel classification. But I would like to do it more automatically. Is it possible to import labeled images (binary images created using different software) to Ilastik?

**Comment by k-dominik** [comment]
Hello @hanginzer,

such functionality is available in ilastik! The process of "How to import labels from an external file" is outlined in the [ilastik documentation](http://ilastik.org/documentation/pixelclassification/pixelclassification#tocAnchor-1-1-5). Please note, that you have to add the desired number of classes in the labelling gui before the import.

Hope this helps!

**Comment by hanginzer** [comment]
Thank you so much. I will try it!

**Comment by k-dominik** [comment]
no problem!
