### ISSUE TITLE
Glob string doesn't conform to h5 stack glob string rules

### ISSUE THREAD

**Issue by nadjana** [ilastik/ilastik#1822]
While I'm trying to open a prediction map file, I get this error. I know that with an h5 file I need to specfy the pattern, but it's not very clear to me how I can do this. I'm very new with this software!
Thank you for your help!

<img width="1051" alt="screen shot 2018-08-29 at 16 10 08" src="https://user-images.githubusercontent.com/42810078/44795821-e71d1400-abab-11e8-86eb-53302eb45ba9.png">
<img width="464" alt="screen shot 2018-08-29 at 16 20 28" src="https://user-images.githubusercontent.com/42810078/44795841-f3a16c80-abab-11e8-8c46-30d6e373b4f0.png">

**Comment by k-dominik** [comment]
Hi @nadjana 

you can open this kind of file just by _Add new_ and then _add separate image(s)_ .

The stack import is mainly meant to be used if you have multiple images that you wish to combine into a single image.

**Comment by nadjana** [comment]
It worked! Thank you! I imaged that was something silly that I was missing :D Thank you again!

**Comment by k-dominik** [comment]
good to know. And we know that this is confusing - and already have some ideas how to improve there. But right now there are more pressing issues... Don't hesitate to contact us again once you run into anything else!
