### ISSUE TITLE
Multicut perpetually busy after "No gurobi license found"

### ISSUE THREAD

**Issue by snajder-r** [ilastik/ilastik#1828]
If you don't have a gurobi license, but forget to switch to a different solver in the Multicut window, you get the "No gurobi license found" message. Afterwards, you can't continue with multicut, even if you select another solver. The small progressbar at the bottom indicates ilastik is perpetually busy. Saving the project and re-loading it appears to work.

How to reproduce:

* Don't have gurobi installed
* Create "Boundary based Segmentation with Multicut" workflow
* Load input data and probabilities
* Run watershed
* In "Training and Multicut" assign a few edge labels and click "Live Predict"
* Select "Nifty_FMGurobi" solver if it isn't already selected
* Click "Update Now"

As expected, an error message pops up saying that no Gurobi license is installed. Afterwards, the "Live Multicut" and "Update Now" buttons are **grayed out** and the small progress bar at the bottom is in indeterminate mode. Switching to a different solver still won't activate the buttons. Only way I found to continue was to save and re-load the project.

**Comment by k-dominik** [comment]
Hi @snajder-r, sorry that you see this issue. And thank you very much for providing us with the steps to reproduce, this is always a huge help! I just tried to reproduce it and for me, I couldn't select the gurobi solver in the first place (not having installed gurobi).

Could you please provide us with a little more detail, specifically:
* which version of ilastik are you using
* on which OS [linux, osx, win] are you using ilastik
* did you maybe try to load a project that was trained while gurobi was installed?

**Comment by snajder-r** [comment]
Hi, @k-dominik, thanks for your reply!

I just realized there was a mistake in my steps-to-reproduce. The first one should be "Have gurobi installed, but don't have a gurobi license". Somehow I originally thought that wouldn't make a difference, but it probably explains why I am able to select gurobi in the first place. Sorry for that! (I originally tried to install gurobi, but then failed to get an academic license because I wasn't in an academic network)

Still, to answer your questions:

* Ilastik Version 1.3
* Windows 10
* No, this is a brand new project

**Comment by k-dominik** [comment]
Ah, okay, this makes sense! This is of course not how it should be, thank you very much for reporting this issue! :)
