### ISSUE TITLE
Removing labels in stage 2 of autocontext

### ISSUE THREAD

**Issue by snajder-r** [ilastik/ilastik#1838]
In pixel classification and in stage 1 of autocontext, if you add a label, then there is a little red "x" next to the label, which you can click to remove that label.

In stage 2 of autocontext, if you accidentally add another label, you can't remove it anymore. There is no red "x" next to the label, and the context menu (when right-clicking the label) only allows you to clear all labels from that label, but not to completely remove it from the list.

**Comment by k-dominik** [comment]
@paulhfu since you have done some work on the minimal labels stuff, could you look into it?

**Comment by snajder-r** [comment]
Sorry, I just realized that it had nothing to do with it being stage 1 or stage 2. It is that the button disappears once you are in "Live update" mode. That's probably intended behavior.

**Comment by k-dominik** [comment]
cool, thank you for letting us know!
