### ISSUE TITLE
Carving, MemoryError should be handled more gracefully, or even better: avoided alltogether

### ISSUE THREAD

**Issue by k-dominik** [ilastik/ilastik#1852]
**Describe the bug**

Preprocessing in carving will throw a `MemoryError` when data is too big for the RAM

**Expected behavior**

At least give a clear error message on what is happening, with maybe some suggestion on how to resolve it (use a subset of the data, get a machine with more RAM)

**To Reproduce**
Within the Carving workflow
1. Add some 3d data in the data selection applet, I have used good old `sample_A_20160501.hdf`
2. Go to the preprocessing applet, choose "dark lines" and go with the defaults, hit _run_

**Error message/traceback**
please add tracebacks with formatting, such as

```pytb
# Some longish stuff left out, should be easy to reproduce yourself
  File "/.../ilastik-meta/lazyflow/lazyflow/slot.py", line 887, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/.../ilastik-meta/ilastik/ilastik/workflows/carving/opPreprocessing.py", line 237, in execute
    reduce_to=self.ReduceTo.value)
  File "/.../ilastik-meta/ilastik/ilastik/workflows/carving/carvingTools.py", line 140, in simple_parallel_ws
    res = bincount = numpy.bincount(overseg.ravel().astype('int64'))
MemoryError
```

**Screenshots**
![error](https://user-images.githubusercontent.com/24434157/46536362-8d94bd00-c8ae-11e8-8ede-0c71fedd0aae.png)

**Desktop (please complete the following information):**
 - ilastik version: `1.3.2b3`
 - OS: `Ubuntu 18.04

**Comment by peq10** [comment]
Hi,
