### ISSUE TITLE
Error loading file in multicut when removing and adding lanes

### ISSUE THREAD

**Issue by snajder-r** [ilastik/ilastik#1857]
Hi!

The error was kinda weird because the message box that popped up was empty except for the title. See attached screenshot.

<img width="109" alt="error loading file" src="https://user-images.githubusercontent.com/42643043/46607867-da70d180-cb02-11e8-93d8-fa7146ec4acb.png">

What triggered the error was: 

* I opened an existing multicut project
* Removed some of the lanes completely
* Added several new images in the Raw Data tab
* Added a single probabilities image to one of the new lanes in the Probabilities tab

After I just confirmed the error, however, I could just add the image in a second try and everything worked fine afterwards.

This was found in the log:

```
ERROR 2018-10-08 13:47:03,137 log_exception 84285 140327745288000 Traceback (most recent call last):
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/ilastik/ilastik/applets/dataSelection/dataSelectionGui.py", line 399, in addFiles
    self.addFileNames(fileNames, roleIndex, startingLane)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/ilastik/ilastik/applets/dataSelection/dataSelectionGui.py", line 455, in addFileNames
    startingLane, endingLane = self._determineLaneRange(fileNames, roleIndex, startingLane)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/ilastik/ilastik/applets/dataSelection/dataSelectionGui.py", line 503, in _determineLaneRange
    assert startingLane < len(self.topLevelOperator.DatasetGroup)
AssertionError
```

**Comment by paulhfu** [comment]
I could not reproduce the error by the above recipe, but it occurred doing the following:

1. Add several complete lanes.
2. Delete the last position in rawData
3. Delete at least one complete lane
4. Add new Data to the position that was deleted in 2.

This behavior is not restricted to multicut.
