### ISSUE TITLE
Allow to export the "Objects" layer from object classification

### ISSUE THREAD

**Issue by akreshuk** [ilastik/ilastik#1868]
It is now not possible to save the segmentation resulting from thresholding other than by right-click --> export on the layer, which is not practical for multiple datasets and can't be used headless.

**Comment by k-dominik** [comment]
this is sort of wip here: https://github.com/ilastik/ilastik/pull/1716
We should pick this up again.

**Comment by k-dominik** [comment]
bumping this up again. we should just add it.
