### ISSUE TITLE
Carving: allow user to load boundary probability map

### ISSUE THREAD

**Issue by k-dominik** [ilastik/ilastik#1871]
In the Carving workflow, we currently generate a boundary probability map in the preprocessing applet based on some pre-defined filters. It would be really useful to be able to load boundary probability maps (as generated by, e.g. Pixel Classification) instead, as it is possible in Multicut.

**Comment by constantinpape** [comment]
I just noticed that this is possible already:
In the `Input Data`, `Overlays` can be added.
So the way to do this is to add the probability map as `Raw Data` and then add the actual raw data as `Overlap`.
