### ISSUE TITLE
Rois do not intersect, failed to load project file. What does it mean???

### ISSUE THREAD

**Issue by marcellopolesel** [ilastik/ilastik#1880]
![capture 2](https://user-images.githubusercontent.com/44767919/47988362-4cc4d980-e0e2-11e8-9961-1913275f781e.JPG)

"Could not load project file.
Rois do not intersect: (array([1040, 2360, 1480,  0]), array([1080, 2400, 1520,  1]) and ([0, 0, 0, 0], [1446, 2116, 3758, 1])"
I had this error message after trying to open a ilastik 1.2.2 pixel segmentation project, file path and axes size are correct. I can open other projects with ilastik, meaning that the software works. Anybody knows what this error means? Thank you.

**Comment by k-dominik** [comment]
Hi @marcellopolesel,

this is a bit hard to diagnose from afar, would you care sharing the project file and the data with us? If so, please send us a link to team@ilastik.org

**Comment by akreshuk** [comment]
closing for not reproducible

**Comment by kephale** [comment]
I get this error with the ilp file in https://zenodo.org/record/1002173#.X7lWscJ7m8g

![image](https://user-images.githubusercontent.com/400105/99885393-d9448500-2c34-11eb-90c1-e1cfc91109c2.png)
