### ISSUE TITLE
Sidebar link on Ubuntu not working

### ISSUE THREAD

**Issue by FynnBe** [ilastik/ilastik#1887]
ilastik works fine when started via command line.

**Comment by k-dominik** [comment]
Do you know how this side-bar link got there? We don't "install" it...

**Comment by FynnBe** [comment]
Oh.. Good to know. That will most likely be the issue then. I'll investigate

**Comment by k-dominik** [comment]
I'll close this, since this doesn't seem to be an ilastik issue. Feel free to reopen if it is.
