### ISSUE TITLE
ExportApplet: Output Image Description not updated/correct

### ISSUE THREAD

**Issue by aubreyghoward** [ilastik/ilastik#1894]
_edit: rename to act as a summary issue for problems related to the output image description display_

In the `ExportApplet`, the output of the image description is not updated. This is very confusing. Also the output is not correct in the first place:

**Not working**
* Number of output channels is not reflected
* Coutout Subregion is not reflected
* Transposed axes are not reflected

**working**
* Data type is updated correctly

_from #1915:_
> In Pixel Classification and Autocontext (probably other workflows too) I noticed that the output "Shape" in the Output Image Description is always displayed as (depth, height, width, 1), for example "(181,512,512,1)".
>
>When exporting probabilities, though, the last dimension should be the number of labels. If I trained pixel classification to distinguish 3 labels, then the output is of shape (181,512,512,3), the dialog however still tells me that it will be (181,512,512,1).
>
>Expected behavior: Either the Image Export Options dialog should know which "Source" (Probabilities, Segmentation, Uncertainty,...) I previously selected and display the shape accordingly, or it should display something generic like (181,512,512,output_channels).

_original issue description:_
>In the new version of Ilastik (1.3.2), when using the pixel classification workflow, I am attempting to change the axis order at export (from zxyc to xyzc). When I click on "Transpose to Axis Order," the preview Output image description does not update. Please advise. 
>
>Thanks.

**Comment by k-dominik** [comment]
The widget is not updated correctly, exported data seems to be transposed as set
