### ISSUE TITLE
Ilastik crashes on runnning on Win7 platform

### ISSUE THREAD

**Issue by pozegit** [ilastik/ilastik#1901]
Hi, i m trying to install the software but it fails in the beginning.
Launched as admin, tried to installed on different path. No success. Im using Win 7.
Installed the beta- ilastik-1.3.2b3
Any idea?
Thanks
![image](https://user-images.githubusercontent.com/16197267/49242924-4f2e0100-f40c-11e8-8fb6-f9fb56a8441f.png)
![image](https://user-images.githubusercontent.com/16197267/49242987-7e447280-f40c-11e8-85ae-2bd19859e841.png)

**Comment by k-dominik** [comment]
@cgohlke share his windows expertise in  the [image.sc forum](https://forum.image.sc/t/ilastik-wont-start-on-win8-1pro-since-1-3-0/20545/16?u=k-dominik) to my eye it seems like this could help you as well!

**Comment by k-dominik** [comment]
please reopen this if the above comment didn't help you
