### ISSUE TITLE
Headless PixelClassification produces BusError when more than ~30 images should be processed

### ISSUE THREAD

**Issue by chaubold** [ilastik/ilastik#1908]
I trained a pixel classification project on a single 2D tif image with one channel. 
If I predict in headless mode from the command line it works fine for a small number of images, but when I input 50 images it immediately crashes with a bus error

```
[1]    44324 bus error  /Users/chaubold/Applications/ilastik-1.3.2rc2-OSX.app/Contents/MacOS/ilastik
```

I once saw when processing 33 images that it did finish processing, but at the end crashed with a bus error as well. Ran with the 1.3.2rc binary on MacOS Mojave.

**Comment by k-dominik** [comment]
I'm closing this - have never seen this in the wild (again), might have been a temporary problem wiht one of our libraries
