### ISSUE TITLE
Image Export Settings: output shape displayed wrong

### ISSUE THREAD

**Issue by snajder-r** [ilastik/ilastik#1915]
In Pixel Classification and Autocontext (probably other workflows too) I noticed that the output "Shape" in the Output Image Description is always displayed as (depth, height, width, 1), for example "(181,512,512,1)".

When exporting probabilities, though, the last dimension should be the number of labels. If I trained pixel classification to distinguish 3 labels, then the output is of shape (181,512,512,3), the dialog however still tells me that it will be (181,512,512,1).

Expected behavior: Either the Image Export Options dialog should know which "Source" (Probabilities, Segmentation, Uncertainty,...) I previously selected and display the shape accordingly, or it should display something generic like (181,512,512,output_channels).

**Comment by k-dominik** [comment]
closing this in favor of #1894
