### ISSUE TITLE
Object Classification: ilastik tries to paint in pixel labels, causes error

### ISSUE THREAD

**Issue by snajder-r** [ilastik/ilastik#1921]
(Sorry, I must have pressed Ctrl+Enter or Shift+Enter or something like that, so the issue was submitted before I wrote the description)

I try to use the ObjectClassification workflow (with segmentation) on a bunch of 3d h5 volumes. I randomly seem to get an error when I try to label objects:

```
ERROR 2018-12-20 12:01:41,953 excepthooks 65377 140088163800896 Unhandled exception in thread: 'MainThread'
ERROR 2018-12-20 12:01:41,953 excepthooks 65377 140088163800896 Traceback (most recent call last):
  File "/g/kreshuk/snajder/ilastik-1.3.2rc1-Linux/ilastik-meta/volumina/volumina/brushingcontroller.py", line 296, in _writeIntoSink
    self._dataSink.put(slicing, labels.reshape(tuple(newshape)))
  File "/g/kreshuk/snajder/ilastik-1.3.2rc1-Linux/ilastik-meta/volumina/volumina/pixelpipeline/datasources.py", line 361, in put
    transposedArray = taggedArray.withAxes(*inputKeys)
  File "/g/kreshuk/snajder/ilastik-1.3.2rc1-Linux/lib/python3.6/site-packages/vigra/arraytypes.py", line 1120, in withAxes
    raise RuntimeError("VigraArray.withAxes(): cannot drop non-singleton axis '%s'." % self.axistags[k].key)
RuntimeError: VigraArray.withAxes(): cannot drop non-singleton axis 'x'.

```

This is on ilastik 1.3.2-rc1 on Centos7.

It seems to appear randomly for some volumes, but:

* If it doesn't appear the first time I try to draw labels on that volume, it won't appear at all (for that volume)
* If it does appear for that volume, it will keep appearing and I am unable to label that volume all together
* saving the project and reloading sometimes helps - then I am sometimes even able to label the volume that was problematic before

**Comment by snajder-r** [comment]
Just found a workaround: I believe ilastik is in "Brush" mode when the error occurs, so it tries to "paint in" pixel labels, instead of labeling objects. I can fix the issue by switching the tool from the brush to the eraser and back to the brush.

**Comment by k-dominik** [comment]
closefd in favor of #1894
