### ISSUE TITLE
Batch Processing does not work for large images (500mB-1GB)

### ISSUE THREAD

**Issue by mayaucsf** [ilastik/ilastik#1933]
I have been attempting to process large images in ilastik (500mB - 1GB) but ilastik stops responding whenever I try to batch process even a single image. When I attempted to run object predictions through headless mode, code started opening files and then appeared to stop (no error message) without generating an output file. When I attempted using the batch processing window, the status bar would never move past 0% and ilastik would stop responding and eventually crash. However, when I segmented the same images into 10 tiles (~50mb each), I was able to run all 10 tiles at the same time. 

Is there any way to run larger images through the program without the need to segment them?

**Comment by constantinpape** [comment]
Which image format are you using?
The best way to process larger images or volumes would be to load them as HDF5 and set an appropriate chunk size.
Ilastik has a data-conversion workflow that should enable you to copy your input data to HDF5.

**Comment by k-dominik** [comment]
closing with @constantinpape's sound advice
