### ISSUE TITLE
Explanation for data types missing in the export applet

### ISSUE THREAD

**Issue by FynnBe** [ilastik/ilastik#1934]
## Short Description

In the _Export Applet_ we allow users to export to various datatypes. Choices include `float`, `int`, `uint` of various widths. This might be confusing - users usually are not aware about differences e.g. between `uint` and `int`. Furthermore `int`s are rarely ever use in image analysis. ilastik doesn't produce negative integers in any of the workflows.

## Expected behavior

The choice of export datatypes should be reduced by excluding `int` datatypes. Additionally, it would be good to include descriptions of the other datatypes with e.g. tooltips.

## To Reproduce
Within the any of the workflows (except Carving)
1. Go through the workflow until you reach the export applet
4. Open the export settings and check available data types

## Error message/traceback

n/a

## Desktop (please complete the following information):
 - ilastik version: 1.3.3x, 1.4.0b27
 - OS: all
 
____

__original issue__

An ilastik user approached me to ask about the difference between int and uint, as they were confronted by this choice when exporting their data. We should provide some tooltips (or similar) to explain this briefly.

**Comment by akreshuk** [comment]
Why should we provide an option to export to int rather than uint?

**Comment by FynnBe** [comment]
We provide to export any data, also raw data. Sure, most users might not need this, but it requires very little overhead to support this. Who knows, maybe their downstream workflow requieres exactly int32 ...?

**Comment by k-dominik** [comment]
closed via https://github.com/ilastik/volumina/pull/293
