### ISSUE TITLE
Tracking with Learning workflow output 'Tracking-Result' does not contain lineage IDs

### ISSUE THREAD

**Issue by RaphaelThierry** [ilastik/ilastik#1943]
Hi,

I'm using the tracking with Learning workflow with success until the (last) result export step: I looked into the results of 2 output formats: the 'object-identities' and the 'Tracking-result'. The first should give an image with the tracking IDs of the objects, where as the tracking-result gives the lineage ID of each object. 
The two output format tried (images stacks in format hdf5 was chosen )are identical and refer to the object IDs. The output of the Tracking-result is referring therefore to object IDs and not lineage ID. Thank you for your help. Kind Regards, Raphael

**Comment by k-dominik** [comment]
Dear @RaphaelThierry,

sorry for getting back to you with such a delay.
I have tried to reproduce your error, but for me, `object-identities` and `tracking-result` yield different images. How did you compare the two images?

**Comment by RaphaelThierry** [comment]
Dear Dominik,

Thank you for coming back on my issue.
I used the Ilastik 1.3.0 version and tested it on Linux and Mac OS so far.
I compared the result images  (h5 files) from the ‘tracking with learning’ using the h5 readers
from Fiji and Matlab.

Which version of Ilastik did you use ? which tools do you use to visualize the h5?
Thank you for your help.

Best,
Raphael


Raphael Thierry PhD.
Novartis Institutes for Biomedical Research
Scientific Computing Group / WSJ-310.6.17.51
4057 Basel – Switzerland
Mobile: +41 794 00 46 39

**Comment by k-dominik** [comment]
Hey, I just used `h5py` in python and checked whether the volumes are identical. I have used `1.3.2`, but i'll check with `1.3.0`.

**Comment by RaphaelThierry** [comment]
Hi Dominik,

I was wondering: is anyone from the Iastik team joining the ISBI conference next week ? (Anna maybe?)
If so; I could hand you (via USB stick) an ilastik project with small dataset that triggers the issue in the tracking with learning workflow.

Best, Raphael

**Comment by akreshuk** [comment]
Hi Raphael,

We have a paper in, but I’m not going, and the first author who is going is not at EMBL anymore. Would dropbox or something similar be an option? How big is this file?

Cheers,
Anna

-----
Dr. Anna Kreshuk
Group Leader

Cell Biology and Biophysics Unit
European Molecular Biology Laboratory
Meyerhofstr. 1
69117 Heidelberg, Germany

Phone: +49 6221 3878572

On 1. April 2019 at 10:45:25, RaphaelThierry (notifications@github.com) wrote:

Hi Dominik,

I was wondering: is anyone from the Iastik team joining the ISBI conference next week ? (Anna maybe?)
If so; I could hand you (via USB stick) an ilastik project with small dataset that triggers the issue in the tracking with learning workflow.

Best, Raphael

**Comment by RaphaelThierry** [comment]
Hi Anna,

Congratulation for the paper.
I’m not going either, but a colleague of mine. In this case, I could share via dropbox.
A project file is usually > 2 GB.
I could build a smaller project with mini-stacks which should reduce the overall size
to 200 Mb. Would this be reasonable?
Cheers,
Raphael

**Comment by akreshuk** [comment]
Sounds reasonable to me, thanks!


On 1. April 2019 at 18:03:49, RaphaelThierry (notifications@github.com) wrote:

Hi Anna,

Congratulation for the paper.
I’m not going either, but a colleague of mine. In this case, I could share via dropbox.
A project file is usually > 2 GB.
I could build a smaller project with mini-stacks which should reduce the overall size
to 200 Mb. Would this be reasonable?
Cheers,
Raphael

**Comment by manelbosch76** [comment]
Hi,
I have the same problem when exporting the results as a multipage tiff. The Object-Identities file is fine but the Tracking-Result show the same object identities stack. I check files in Fiji.

Thanks for your help.

Regards,
Manel

**Comment by k-dominik** [comment]
Bumping this one, can reproduce it now.
