### ISSUE TITLE
Investigate pixel features exposed in ilastik

### ISSUE THREAD

**Issue by k-dominik** [ilastik/ilastik#1948]
@constantinpape made me aware (thx) that two of our pixel features look similar to a point of where changing layers between the to, is unnoticeable.

The two candidates are _Laplacian of gaussians_ and _Difference of gaussians_

Images with `sigma = 3.5`

_Laplacian of gaussians_:
<img height="200" src="https://user-images.githubusercontent.com/24434157/51973188-578ed080-247d-11e9-9073-a1a79daabd69.png">

_Difference of gaussians_:
<img height="200" src="https://user-images.githubusercontent.com/24434157/51973189-578ed080-247d-11e9-98c1-61ee9cfe773f.png">

A quick numerical investigation revealed that one is (almost) just a scaled version of the other. Maybe we should get rid of one of the two in the future.

**Comment by k-dominik** [comment]
closing this in favor of https://github.com/ilastik/ilastik/issues/17 (seventeen!)

**Comment by constantinpape** [comment]
Wow, this discussion really dates back a long time.
