### ISSUE TITLE
error exporting file

### ISSUE THREAD

**Issue by nadjana** [ilastik/ilastik#1984]
Hi everyone!

I'm trying to export a prediction map with object classification. I've already done this successfully and I'm following the same procedure. 
I suddenly get the following error:
<img width="476" alt="Screenshot 2019-04-05 at 17 36 33" src="https://user-images.githubusercontent.com/42810078/55714097-47055400-59f2-11e9-914c-b36700d658d9.png">

I din't move the folder and I didn't change the name.. I don't really know what to try.. I'm not that expert. 

I welcome any suggestion! 

Thank you for your help,
Nadja

**Comment by k-dominik** [comment]
Hi @nadjana, thank yuou very much for reporting this. Would it be possible for you to provide some additional information? I gather that you work on a Mac from the screenshot. What version of ilastik are you using? And is it really the same project that you are using, or is it a new one? If the project is small, could you maybe send it to us along with the data via email team@ilastik.org ?

**Comment by nadjana** [comment]
Hi Dominik,

thank you for your reply.

I do work with a Mac indeed and I use the Ilastik version 1.3.0. It isn't the same project, it's a new one but I'm following the same procedure and also the tiff files are generated in the same way. I sent you an email with google drive for the project and the data. I hope can help!

Thank you so much for your help!
Nadja

**Comment by k-dominik** [comment]
Hey Nadjana,

I think this error was fixed in version `1.3.2`. So could you give this a
go? https://www.ilastik.org/download.html

Cheers
Dominik

**Comment by nadjana** [comment]
Great! I thought there was an automatic update for the new versions. I'll give it a try and I keep you posted!

Cheers,
Nadja

**Comment by k-dominik** [comment]
I'm pretty sure this error should be gone now, please reopen/open a new issue if this is not the case.
