### ISSUE TITLE
R/W lock on `.ilp` file prevents parallel batch processing in cluster

### ISSUE THREAD

**Issue by riccardomurri** [ilastik/ilastik#1994]
## Describe the bug

We are using the `run_ilastik.sh` to process several batches of images in parallel on a SLURM cluster; each batch is dealt with by a different `run_ilastik.sh` process.

If the `.ilp` file is *writable* by the user running Ilastik, then the first Ilastik process to start running proceeds to open it read+write and puts an exclusive write lock on it: other jobs that start a little later will abort because they cannot obtain the lock.

If the `.ilp` file is *read-only*, then everything works perfectly (Ilastik seems to request a shared lock in this case, which many concurrent processes can obtain).

So there seems to be no reason to use exclusive locks in the first place.

## Expected behavior

I would expect multiple  `run_ilastik.sh` processes to be able to progress without locking each other out.

## To Reproduce

If you don't have a SLURM (or other batch system) cluster available, you can run multiple commands like this:

    run_ilastik.sh --headless --project /path/to/some/file.ilp  image1.png image2.png ... imageN.png &

If you have access to a SLURM cluster, just make an array job that runs the above command and submit multiple steps of it.

Each command should use a different set of images but the `.ilp` files should be the same for all.

## Desktop:
 - ilastik version: [e.g. 1.3.2post1]
 - OS: 64-bit Linux, Ubuntu 16.04:

        $ lsb_release -a
        No LSB modules are available.
        Distributor ID: Ubuntu
        Description:    Ubuntu 16.04.6 LTS
        Release:    16.04
        Codename:   xenial

**Comment by constantinpape** [comment]
You can start ilastik headless in read-only mode by passing the flag `--readonly=1`.
This should fix your issue.
