### ISSUE TITLE
ilastik won't start on windows7; 

### ISSUE THREAD

**Issue by k-dominik** [ilastik/ilastik#2003]
## Describe the bug
Per [user report](https://forum.image.sc/t/ilastik-1-3-3-first-beta/25097/2?u=k-dominik), ilastik won't start on windows 7

## Error message
"The ordinal 191 could not be located in the dynamic link library libiomp5md.dll"

## Desktop (please complete the following information):
 - ilastik version: [e.g. 1.3.3b1]
 - OS: Windows 10

**Comment by k-dominik** [comment]
tiny update, I have a windows7 machine lurking in some closet at home and on this one, ilastik runs. It will be interesting to find the circumstances that led to the reported failure.

**Comment by m-novikov** [comment]
Related: https://github.com/ilastik/ilastik/issues/1918 workaround on forum resolved user problem.
Apparently there is some additional mechanism in place linked to way the Intel MKL is installed, maybe they use `regsvr32` to register DLLs.
To resolve we need to get consistently reproducible case with Win7 and Intel MKL.
