### ISSUE TITLE
Scrolling: Alt+mouse scrolling down behaves improperly 

### ISSUE THREAD

**Issue by anindgupta** [ilastik/ilastik#2009]
## Describe the bug
When scrolling through a 3D stack of images using alt+mouse, both the scrolling up and down increment by 10 slices (e.g., scroll up: 10+10 and scroll down 10+10) 

## Expected behavior
Should decrement by 10 slices when scrolling in down direction.

## Desktop (please complete the following information):
ilastik version: 1.3.2post1
OS: Ubuntu 16.04.4 LTS

**Comment by k-dominik** [comment]
Thanks for that one!

**Comment by k-dominik** [comment]
closed via https://github.com/ilastik/volumina/pull/294
