### ISSUE TITLE
Carving: update of superpixels invalidates objects, but objects are still present

### ISSUE THREAD

**Issue by k-dominik** [ilastik/ilastik#2011]
## Describe the bug
Right now, if one already has some saved objects and decides to change the superpixel segmentation, already carved objects are still present (associated with superpixel ids that don't make sense anymore).
Furthermore, if the number of superpixels is reduced, it is very likely that there will be `IndexErrors` accessing the superpixels from saved objects (as superpixels with large ids are not present anymore).

## Expected behavior
Updating the superpixel segmentation should not result in inconsistent, non-sensical objects. Safest for now would be to remove all objects and add a fair warning about this!

## To Reproduce
Within the Carving workflow
1. Add some 2d/3d, do preprocessing, carve/save some objects
2. Go back to the preprocessing applet, make changes to the superpixel segmentation
3. In the labeling applet you can now, load an object and see that it doesn't make sense at all anymore

## Screenshots
To illustrate, you go from this:
![export](https://user-images.githubusercontent.com/24434157/57307097-3e349a80-70e4-11e9-947c-c98dc1b84551.png)

to this 
![export2](https://user-images.githubusercontent.com/24434157/57307116-455ba880-70e4-11e9-89bf-5115f2911cfa.png)

## Desktop (please complete the following information):
 - ilastik version: 1.3.2post1, 1.3.3b1
 - OS: all

**Comment by k-dominik** [comment]
xref: #918

**Comment by btbest** [comment]
As of #2664, we now discard all saved objects when the user changes preprocessing. The user is warned about this before they re-execute preprocessing.

Cross-posting the consideration regarding an alternative solution from #918: We could consider keeping the labels of saved objects and discarding only their segmentations, but doing this properly will require reworking the handling of saved objects quite a bit. One would also need to extend Carving with a sub-workflow to guide the user to re-segment all saved objects after changing preprocessing. The user would have to do this manually for each object. And they _should_ do it manually, as it's not sound to just assume that all saved labels are semantically valid with the new preprocessing.
