### ISSUE TITLE
[Question] How to access predictions after headless training

### ISSUE THREAD

**Issue by hno2** [ilastik/ilastik#2017]
Hey there, 

training now works perfectly when using `generate_trained_project_file()` from train_headless.py. Now I want to predict the results for the file I trained with before directly after the training. 
I looked at [`example_python_client.py`](https://github.com/ilastik/ilastik/blob/master/examples/example_python_client.py).
There seems to be some kind of functionality implemented in [`OpPredictionPipelineNoCache`](https://github.com/ilastik/ilastik/blob/master/ilastik/applets/pixelClassification/opPixelClassification.py#L411-L465), but I am not sure how to operate this with a trained `opPixelClassification.Classifier`.

Is there some documentation I am missing?
Thanks a lot in advance for your help!

**Comment by k-dominik** [comment]
Sorry for  not replying before. I'd say the python api we have for pixel classification will do the job. Example notebook: https://github.com/ilastik/ilastik/tree/main/notebooks/pixel_classification_api
