### ISSUE TITLE
White/Transparent pixels in prediction (3rd class with 2 defined classes)

### ISSUE THREAD

**Issue by VolkerH** [ilastik/ilastik#2025]
## Describe the bug

Using the release version `1.3.2post1-win64.exe` on Win 10:

 With only two classes defined (label colors yellow/green), the segmentation output 
shows a few white (or transparent) pixels. When I turn on the visibility for the "raw image"
the pixel values of the raw image show through at these locations.  Possibly this is related to https://github.com/ilastik/ilastik/issues/72 ?

![image](https://user-images.githubusercontent.com/2210044/58059594-04b66180-7bb1-11e9-9803-be66b00e9cac.png)

## Expected behavior
* Each pixel belongs to one of the two defined classes
* raw image data not visible at any pixel location if segmentation view is enabled

## To Reproduce
Just labelled a volume with 2 classes

**Comment by VolkerH** [comment]
one more screenshot with `raw input` layer turned on:

![image](https://user-images.githubusercontent.com/2210044/58060108-139e1380-7bb3-11e9-905e-179c376955ff.png)

**Comment by k-dominik** [comment]
could reproduce this on linux, too.

**Comment by VolkerH** [comment]
Just stumbled on this again.
![image](https://user-images.githubusercontent.com/2210044/84619944-f81e4d00-af19-11ea-8f0f-22f524016599.png)

Still happens in 1.4.0b5
