### ISSUE TITLE
Training tab stays grayed-out if number of raw images is even

### ISSUE THREAD

**Issue by awedwards** [ilastik/ilastik#2028]
## Describe the bug
The "Training" tab stays grayed-out if there are an even number of training images in version 1.3.3b1.

## Expected behavior
Once I have loaded in my images and selected features, the "Training" tab usually becomes available. I noticed that if I add an even number of images, it never becomes available. But if the number of raw training images is odd, the training tab becomes accessible.

## To Reproduce
Within the Pixel Classification + Object Classification workflow
1. Add some 2d data
2. Select features in the "Feature Selection" applet
3. Watch the "Training" tab to see behavior as the number of input images is changed

## Error message/traceback

No errors are shown

## Desktop (please complete the following information):
 - ilastik version: 1.3.3b1
 - OS: Windows 7

**Comment by k-dominik** [comment]
was fixed in `1.3.3b2`
