### ISSUE TITLE
Selecting multiple files in Beta Version 1.3.3b1

### ISSUE THREAD

**Issue by sharoncy** [ilastik/ilastik#2029]
## Describe the bug
In the beta version of ilastik I am unable to select more than one file for upload at any one time (in the "Input Data" and "Batch Processing" applets.  

## Expected behavior
In the older versions I was able to select multiple files by highlighting for import to "Input data" or "Batch Processing". 

## To Reproduce
For example, in "Batch Processing" I click "select raw data files" and then try to highlight all the files (ctrl, A). It doesn't work and I am only able to select one file at a time.

## Screenshots
If applicable, please add screenshots to help explain your problem.

## Desktop (please complete the following information):
 - ilastik version: 1.3.3b1
 - OS: Windows 10

**Comment by k-dominik** [comment]
Thanks a lot for the report @sharoncy 

note to us: this is related to #2004

**Comment by k-dominik** [comment]
@sharoncy, could you please try http://files.ilastik.org/ilastik-1.3.3b2-win64.exe whether it resolves your problem?

**Comment by sharoncy** [comment]
I've tested and it works well, thanks! @k-dominik
