### ISSUE TITLE
bug in batch processing

### ISSUE THREAD

**Issue by lramsa1** [ilastik/ilastik#2094]
This was initially posted as a comment to someone with the same issue in an older ilastik github, but then I realized it makes more sense to report it as a new bug here.
I am using ilastik 1.3.2post1 on macOS Mojave version 10.14.5.

I performed object classification (raw data and pixel prediction map) on a subset of 30 images with the features "Mean intensity," "Variance of intensity," and "Variance of intensity in neighborhood." The export for these images was fine. Then I attempted to do batch processing on an additional 57 images. At which point I get the error message below. I have done these exact steps with other images and it worked fine, so I'm not sure exactly how to reproduce the error.

RuntimeError: 
Precondition violation!
RandomForestn::predictProbabilities(): Too few columns in feature matrix.
(/Volumes/Data/kutra/conda-build/vigra_1549301195098/work/include/vigra/random_forest.hxx:1250)

ERROR 2019-08-30 14:35:31,058 log_exception 41480 4495586752 Error encountered during batch processing:

Precondition violation!
RandomForestn::predictProbabilities(): Too few columns in feature matrix.
(/Volumes/Data/kutra/conda-build/vigra_1549301195098/work/include/vigra/random_forest.hxx:1250)

![image](https://user-images.githubusercontent.com/7682706/64045578-a8f85e80-cb37-11e9-9bbd-4afce1a1eb35.png)

**Comment by k-dominik** [comment]
This is really unfortunate. Does it only occur if you do batch processing with many files, or is there one specific file that triggers this? In this case, would it be maybe possible for you to share your project and the "bad" dataset with us? -> team@ilastik.org

**Comment by lramsa1** [comment]
I attempted batch processing with many files and with just one file at a time (I tried several different ones from the batch) and I always get the same error. I will send my project and data to that email address shortly.

**Comment by lramsa1** [comment]
Turns out my email bounced and the message went to my spam box. It's no matter in any case because I figured out the issue. I was trying to use mask files output from CellProfiler as a "Pixel Prediction Map." Ilastik didn't like this file format. When I asked CellProfiler to output an image rather than a mask it worked. So I think this issue can be closed.

**Comment by k-dominik** [comment]
oh, thank you very much for letting us know! And great that you have figured it out. Closing this :)
