### ISSUE TITLE
BatchProcessingExport.run_export no longer accepts preloaded arrays

### ISSUE THREAD

**Issue by clbarnes** [ilastik/ilastik#2137]
The new PreloadedArrayDatasetInfo is an improvement, but if you pass a list of them to `run_export` as the value of the `role_data_dict`, it still gets interpreted as a truthy `role_input_path` by `export_dataset`, and so ilastik tries to convert it to a `FileSystemDatasetInfo` (and fails).

Is there a new way to run a given workflow on preloaded arrays?

**Comment by Tomaz-Vieira** [comment]
Hey, thanks for catching that. I think this was just an oversight on my part during the refactoring; I'm working on a quick fix for it.

I have to assume that you're using ilastik inside a script to have stumbled upon this limitation. Could you just illustrate your use case just so I have it in mind in the future?

**Comment by clbarnes** [comment]
I'm using the ilastik GUI to paint my training data and train my classifiers (a 2-stage autocontext and multicut segmentation of ssTEM). Then I'm using python to get ilastik to use those classifiers on A) JPEG tiles B) specific regions (non-axis-aligned) within an N5 volume C) arbitrary arrays - but obviously if I can get the latter to work I can just handle the conversion of A and B into C myself. I'm also doing my own parallelisation (ilastik's cache thread doesn't like `multiprocessing` so I'm having to spin up separate python interpreters with `subprocess` and coordinate them with redis), because I think ilastik's built-in parallelism uses python `threading` and relies on vigra's threading and GIL releasing, but because each of my jobs is very small (a 2D tile), I don't get very good CPU utilisation with all the round trips.
