### ISSUE TITLE
Object Classification: shift + left mouse click should be panning

### ISSUE THREAD

**Issue by martinsch** [ilastik/ilastik#216]
...like in the pixel classification workflow. To pan, one has to select the navigation cursor at the moment, however, this should also be possible with the brush.

**Comment by dlogan** [comment]
Ah!  I just discovered this (shift-left-click to pan images in the main viewer).  The docs (http://ilastik.org/documentation/basics/navigation) only mention middle-click-panning (not easy on a trackpad!).  Just a suggestion to add this to the documentation

**Comment by stuarteberg** [comment]
Good point, thanks.  Done!
