### ISSUE TITLE
tifffile migration

### ISSUE THREAD

**Issue by k-dominik** [ilastik/ilastik#2161]
We're currently still stuck with `tifffile 0.4`, while the world has moved on quite a bit and introduced yet more backwards-incompatible changes.
The list of new features is pretty long. E.g. reading of czi files.

There seems to be some momentum now on conda-forge to package tifffile along with imagecodecs, which allows for (fast) reading/writing of compressed tiffs.
We could probably go away from reading tiffs via vigra then.

https://github.com/conda-forge/tifffile-feedstock/pull/33
https://github.com/conda-forge/staged-recipes/pull/6842

Once those packages are in, there is a very  good chance for a tiff reading overhaul!

**Comment by ocefpaf** [comment]
It should take a while for the CDN to sync (~50 min) but let me know if the new package solved your problems. Note that I used `imagecodecs-lite` and not `imagecodecs`.

**Comment by k-dominik** [comment]
ugh this is done!
