### ISSUE TITLE
Inconsistent output values in pixel classification 'Simple Segmentation' 

### ISSUE THREAD

**Issue by tischi** [ilastik/ilastik#2165]
The values in pixel classification output (Simple Segmentation) is inconsistent depending on whether the export was executed from the GUI or in the headless mode, i.e. if I export my segmentation from the GUI as uint8, my labels are enumerated from beginning (0, 1, 2,...), but when I export in headless my labels are enumerated from the end (255, 254,...). The output should be the same no matter if we executed from the GUI or the headless.

**Comment by k-dominik** [comment]
interesting, I wasn't aware of that. I tried to reproduce this and would get the same values irrespective whether I used the headless mode, or ilastik from the gui. I think it is possible that our plugin does something there. Did you use the plugin export, maybe?
