### ISSUE TITLE
Let users set the number of active threads

### ISSUE THREAD

**Issue by SarenT** [ilastik/ilastik#2167]
## Description
A setting where users can set the number of active threads, which are running to train the data or any expensive task.
## Scenario

A settings window, where users can enter a number with a short hint of how to choose a good number. I would argue number of cores - 2 would be a good start. This setting should be stored and become defualt next time program is run.

## Rationale

Ilastik requires lots of processing power. This drives CPU usage to 100% at all CPU cores. This can affect rest of the system and make systems almost unusable for other applications. Tasks, which take a few seconds should use full power to finish the task as soon as possible. However, longer than this is annoying to wait. So user should be able to use the system for other purposes, while the task is finishing in the background. Leaving 2 cores aside for other tasks would be great. It is ideal if user can choose, how many cores to dedicate for Ilastik.

## Drawbacks

Almost none, as by default Ilastik will use all cores. Only experienced users or guiding UI will set a limit possibly extending time required to finish the task. However, waiting and not being able to do anything is more wasteful.

## Scope

All heavy computations such as training of the network.

## Possible implementation

I don't know how Ilastik is managing the threads or threadpool. However, it should be able to keep count of tasks to keep them on hold, until some are finished. Max number of running threads should always be equal or less than the allowed limit.

**Comment by constantinpape** [comment]
Setting the number of threads is already possible by setting the environment variable `LAZYFLOW_THREADS`, e.g. by starting ilastik from the command line like this:
```bash
LAZYFLOW_THREADS=4 ./run_ilastik.sh
```

There is no option to set this in the GUI yet afaik.

**Comment by stuarteberg** [comment]
In case it's useful, you can also configure this via a configuration file.  The details are documented here:

https://www.ilastik.org/documentation/basics/installation.html#controlling-cpu-and-ram-resources
