### ISSUE TITLE
Smarter axes guess

### ISSUE THREAD

**Issue by alyst** [ilastik/ilastik#2170]
## Description

Use the axes from the last loaded image (if it's compatible) as the initial guess for the axes of the new image.

## Scenario

User adds new images to the *Raw Data* tab, no *"Constraint of 'Pixel Classification' applet was violated"* alert box followed by the image properties dialog popup are being shown.

## Rationale

It would make adding raw images much easier.

**Comment by k-dominik** [comment]
Hi @alyst,

i thought ilastik was doing that (and it did in previous versions). Seems like a change undid this. This will most likely be reverted to the original behavior ( or something maybe even smarter - will be discussed ).

Thanks bringing this up. Wasn't caught in the reviews.
