### ISSUE TITLE
Performance problems in live training API when requiesting tiles

### ISSUE THREAD

**Issue by m-novikov** [ilastik/ilastik#2172]
Given the following array
```
+---+---+---+
| 1 | 2 | 3 |
+---+---+---+
| 4 | 5 | 6 |
+---+---+---+
| 7 | 8 | 9 |
+---+---+---+
```
Consecutively requesting tiles 1, 2, 3, 4 is significantly slower than requesting slice including tiles [1..4]
Probably the cause it that request is misaligned because of halo expansion for feature computation.

**Comment by Tomaz-Vieira** [comment]
Apparently my problem was that, since the tiles were so small, most of the cpu time was being spent running python code rather than numpy or fastfilters. Running using separate processes via MPI or ProcessPoolExecutor would max out my CPUs, as expected.
