### ISSUE TITLE
Downloading ilastik

### ISSUE THREAD

**Issue by reinat168** [ilastik/ilastik#2175]
## Describe the bug
Please add a clear and concise description of what the bug is.

I have downloaded version 1.3.3post2 (2019-12-13) (mirror)
When I tried to run it I got the following message:
The ordinal 191 could not be located in the dynamic link library libiomp5d.dll

**Comment by k-dominik** [comment]
Hi @reinat168,

thank you very much for the report!

From what I see the problem might be that ilastik does not understand the data you are adding. Could you maybe please elaborate what kind of image you are trying to load?

**Comment by reinat168** [comment]
I get this message while trying to run ilastik itself for the first time. Immediatly after clicking on the ilastik icon I get this error.
Thank you,
Reinat

**Comment by k-dominik** [comment]
Okay - sorry, I think I've fallen for the default traceback message that is in your post, I'll remove all boilerplate to make it more obvious...

**Comment by k-dominik** [comment]
Okay, I take it you are on windows? Possibly Windows 7? From what I can tell by this description I'd guess that there is an incompatible mkl library somewhere in your path.

Check out maybe this post https://forum.image.sc/t/ilastik-wont-start-on-win8-1pro-since-1-3-0/20545/16?u=k-dominik

**Comment by reinat168** [comment]
Yes, Windows 7 and it solved the problem! Thank you very much!

**Comment by k-dominik** [comment]
cool, thank you very much for letting us know. Closing this as resolved
