### ISSUE TITLE
Investigate timing test failure on circleci

### ISSUE THREAD

**Issue by k-dominik** [ilastik/ilastik#2184]
Did not menage to reproduce this anywhere else, but currently, vigra seems to be faster than fastfilters :o

See: https://circleci.com/gh/ilastik/ilastik/2102

once this resolved, https://github.com/ilastik/ilastik/pull/2191/commits/91e7ff823dfd4af343a80f1c18afae587208652c should be reverted

**Comment by Tomaz-Vieira** [comment]
The fastfilters repo also has some performance tests comparing itself to vigra. Maybe we can use those for some benchmarking too

**Comment by k-dominik** [comment]
closed via https://github.com/ilastik/ilastik/pull/2757
