### ISSUE TITLE
Cannot adjust raw input display thresholds

### ISSUE THREAD

**Issue by mitkovm** [ilastik/ilastik#2195]
## Describe the bug
Unable to adjust lookup table usage for raw image data display. Resulting error message is: 

Window title: 
>TypeError 

Message content: 
>bool object is not subscriptable   
>Advanced information about this error may be found in the log file: path\ilastik_log.txt)
 

## Expected behavior
Menu with adjustable lower/upper LUT thresholds should have appeared. 

## To Reproduce
Within the Pixel Classification Workflow (Training interface):
1. Right-click on "Raw Input"
2. Left-click on "Adjust thresholds"

## Error message/traceback

ERROR 2020-03-06 10:06:38,476 excepthooks 37008 73860 Unhandled exception in thread: 'MainThread'
ERROR 2020-03-06 10:06:38,476 excepthooks 37008 73860 Traceback (most recent call last):
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\volumina\volumina\widgets\layercontextmenu.py", line 53, in adjust_thresholds_callback
    dlg = GrayscaleLayerDialog(layer, menu.parent())
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\volumina\volumina\widgets\layerDialog.py", line 60, in __init__
    self.grayChannelThresholdingWidget.setValue(layer.normalize[0][0], layer.normalize[0][1])
TypeError: 'bool' object is not subscriptable

## Desktop (please complete the following information):
 - ilastik version: 1.4.0b1
 - OS: Windows 10
 
## Thank you, Ilastik Team
Thank you for your amazing work in making these techniques available to the community!

**Comment by k-dominik** [comment]
Thanks for the report and for the warm words! We'll fix this of course :)
