### ISSUE TITLE
Can't draw labels in uppermost region of training applet due to some invisible bar

### ISSUE THREAD

**Issue by christophdecker** [ilastik/ilastik#222]
In training applet you can't draw labels in the uppermost region of the volume, i.e. between the swap/rotate/etc. icons. The cursor can still be moved there, but the crosshairs stop at some invisible bar and you can't draw labels underneath (which I just needed to do).

![label_at_top](https://f.cloud.github.com/assets/2794524/350722/aaf5c2c0-a02a-11e2-8d61-8b57a6ddb83d.png)11

Workarounds:
1. Zoom in massively such that only one pixel is covered by the invisible bar -> quite impractical
2. Start drawing below the invisible bar and just draw the cursor up -> marks everything from below the invisible bar up to the thing you wanted to label -> now you can do the same trick with the eraser to remove the unwanted labeling ;-)

**Comment by k-dominik** [comment]
Phew, so it wasn't the HUD that ate the widgets, it was the ```EventSwitch```... I have fixed the behaviour with PR https://github.com/ilastik/volumina/pull/184

**Comment by akreshuk** [comment]
fixed in ilastik/volumina#184
