### ISSUE TITLE
how to run version 1.4.0b1 from windows

### ISSUE THREAD

**Issue by liangy10** [ilastik/ilastik#2236]
Hi, I want to segment blood vessels in a 3D stack and installed 1.4 beta version to use its Voxel Segmentation Workflow. But it says: " In order to access this workflow, supply the --hbp command line flag when starting ilastik." May I know how to do that? since in window 10, i just start ilastik from start.  Thanks!

**Comment by k-dominik** [comment]
Hi @liangy10,

there are at least two ways to supply a command line flag to ilastik.

#### 1 start ilastik via the terminal/command-line
* type `cmd` into the search field, click on "Command Prompt" to start a terminal window
* In this terminal window you have to navigate to the ilastik installation folder. If you didn't change it when installing this should be "C:\Program Files\ilastik-1.4.0b3". So in the command prompt, type (including the quote marks) and press enter:
 ```cmd
cd "C:\Program Files\ilastik-1.4.0b3"
```
you should now see `C:\Program Files\ilastik-1.4.0b3>` left of the curser (where you type text).
* here you can start ilastik and supply the `--hbp` flag by typing
```cmd
ilastik.exe --hbp
```

#### 2 create a shortcut with the command line flag

The second method is for a more permanent setup.
You will create a shortcut to ilastik on your desktop that will always supply the `--hbp` flag.
So you can simply start it with a double click.
* locate ilastik in your start menu:
![il1](https://user-images.githubusercontent.com/24434157/79202295-ad108c80-7e39-11ea-8550-ea03b685ab08.png)
* click on it with the left mouse button and hold the button while dragging it to the desktop. You have created a link (visible by the little curved arrow in the lower-left corner):
![il2](https://user-images.githubusercontent.com/24434157/79202369-cdd8e200-7e39-11ea-9c52-59588f8a46c1.png)
* edit the properties (right click - Properties) of the link to include the command line flag (highlighted in yellow in the following screenshot):
![il3](https://user-images.githubusercontent.com/24434157/79202741-53f52880-7e3a-11ea-8596-712220984e40.png)

**Comment by k-dominik** [comment]
Hi @liangy10, did you manage to run ilastik in debug mode?

**Comment by k-dominik** [comment]
closing this usage question, no further action required.
