### ISSUE TITLE
dirty ROI - Could not load project file

### ISSUE THREAD

**Issue by sashakrol** [ilastik/ilastik#2239]
## Describe the bug
Failure to load a previously saved project for pixel classification. 

Error message:  Could not load project file. The dirty ROI (Subregion:start '[0,0,0]' stop '[1,3372,8820']) appears incorrect for the InputSlot, whihc has shape (1,1,3372,8820,1).

This is particularly frustrating as can now not access the classifier at all. 

## To Reproduce
Its possible this occurred following setting the export settings to export just the prediction (and not the raw data) as a tif ( having to change some of the setting there). 

## Desktop (please complete the following information):
 - ilastik version:1.3.3(post2)
 - OS: Windows 7

**Comment by k-dominik** [comment]
Hi @sashakrol,

I can understand that it is frustrating not being able to access your trained project. I haven't seen this particular error yet so it would be great if you could upload your project file (along with the data) to [this filedrop](https://oc.embl.de/index.php/s/uEfcHZE7Ax4WL4v)

Did you train the project with the same version of ilastik?

**Comment by sashakrol** [comment]
Hi @k-dominik 

Thanks so much - will upload now. 
And yes I did. A previous version of the classifier is opening fine. I was also getting a similar error when I was exporting the predictions hence my comment. I'm surprised that this then caused the file not to be able to open however.

**Comment by k-dominik** [comment]
Hi @sashakrol,

thank you very much for providing the data and the project file. I can reproduce this now. Would it help you if I send you a project file that works again (of the current state) (I can either upload it publicly somewhere, or send it to you via email, drop me a line: dominik.kutra@embl.de if you prefer it privately), while we investigate how this can happen in the first place? Btw. thanks for hinting at the export settings, this seems to be the problem - indeed!

**Comment by sashakrol** [comment]
Hi @k-dominik 
Thank you so much for looking into this and hopeful for a fix. As I mentioned I was having trouble exporting the probability map as a tif - I would get similar errors until I eventually got it to work. Basically I go to the  prediction export settings, there's a panel below with the probabilities previews and the raw data.  i then click 'choose export settings' ,  change it to 'tif',  and unsigned16bit, renormalize, transpose to axis order cyx -  and get the same dirty ROI error ( and no output). eventually playing around with the range of 'c' I sometimes get it to work.  Sorry if this isn't clear but the error isn't super consistent.

**Comment by k-dominik** [comment]
The minimal path to reproduce this is to take a 2d dataset that is saved as 5d (with singletons) and then change the export axisorder dropping singleton axes to something like: `cyx` (effectively dropping  the singletons `z`, and `t`)

**Comment by sashakrol** [comment]
@k-dominik I generate the h5 dataset needed to begin the project with the fiji export tool. Is it possible to change those settings in that tool so as to save the h5 dataset in 2d prior to importing into ilastik?

**Comment by k-dominik** [comment]
> @k-dominik I generate the h5 dataset needed to begin the project with the fiji export tool. Is it possible to change those settings in that tool so as to save the h5 dataset in 2d prior to importing into ilastik?

no, the ilastik hdf5 export always does 5D. What you could do, however, is running the pixel classification via the fiji plugin. This will open the result in Fiji right away.

**Comment by sashakrol** [comment]
> > @k-dominik I generate the h5 dataset needed to begin the project with the fiji export tool. Is it possible to change those settings in that tool so as to save the h5 dataset in 2d prior to importing into ilastik?
> 
> no, the ilastik-fiji-plugin hdf5 export always does 5D. What you could do, however, is running the pixel classification via the fiji plugin. This will open the result in Fiji right away.

This seems like a good solution but I can't seem to get the pixel classification plugin to work with either .tif or .h5 files as inputs. Please see error below which also show the imagej and java versions.  
g) 
![ilastikimagejerror](https://user-images.githubusercontent.com/61850294/79601408-bf4b2e80-80b6-11ea-8033-9bb058d263a9.PNG)

**Comment by k-dominik** [comment]
Hi, have you chosen the ilastik executable location first? On Windows it's per default in `C:\Program Files\ilastik-1.x.y\ilastik.exe` ...
It tries to start it from `C:\opt\ilastik` which would be an odd location on windows
