### ISSUE TITLE
Labels lost on loading

### ISSUE THREAD

**Issue by qin-yu** [ilastik/ilastik#2244]
## Describe the bug
Save, close, and then reopen a Pixel Classification + Object Classification project at step 6/7/8. Now the first labelled (object classified) image becomes unlabelled. If you leave it like this, save and reopen again, then the first labelled image (which is the second image) will become unlabelled.

## Expected behaviour
When a user reopens a saved project, everything in the project stays the same as it was.

## To Reproduce
Steps to reproduce the behaviour:
Within the Pixel Classification + Object Classification workflow
1. Add some 2d data in the data selection applet
2. Train the pixel classifier to segment the objects out
3. Train the object classifier by labelling 5 classes
4. Save the project at "object classification" applet or "object information export" applet
5. Quit ilastik and reopen ilastik
6. Load the saved project
7. "object classification" applet automatically shows up and the first image with binary image masked also shows up. But now the labels are all gone

## Desktop (please complete the following information):
 - ilastik version: ilastik-1.3.3post2-Linux
 - Ubuntu 18.04

**Comment by k-dominik** [comment]
Hi @qin-yu ,

thank you very much for the detailed report. It was straight-forward reproducing this issue.

Until this is fixed I want to add that we, in general, do not recommend to use this combined workflow for "real" work. It's there mostly for demo purposes. It is in general more advisable to have separate steps for pixel classification, and object classification.

Cheers and thank you again!
