### ISSUE TITLE
Trouble Running ilastik Software

### ISSUE THREAD

**Issue by howardli123** [ilastik/ilastik#2254]
## Describe the bug
Hello,

Thank you for developing this software. I have the latest version of the ilastik software installed. However, when trying to run the program, an error occurs - see attached screenshot. The error heading reads "python.exe - Ordinal Not Found" and the error message reads "The ordinal 191 could not be located in the dynamic link library libiomp5md.dll." Are there any steps I can take to fix this? Thank you so much!

## Error message/traceback

If applicable, please add tracebacks with formatting, such as

```pytb
ERROR 2018-08-29 10:04:59,901 excepthooks 3936 140154429757184 Unhandled exception in thread: 'Worker #3'
ERROR 2018-08-29 10:04:59,901 excepthooks 3936 140154429757184 Traceback (most recent call last):
  File "/.../envs/idev/ilastik-meta/volumina/volumina/tiling.py", line 773, in _fetch_tile_layer
    img = ims_req.wait()
  File "/.../envs/idev/ilastik-meta/volumina/volumina/pixelpipeline/imagesources.py", line 387, in wait
    return self.toImage()
  File "/.../envs/idev/ilastik-meta/volumina/volumina/pixelpipeline/imagesources.py", line 425, in toImage
    raise NotImplementedError()
NotImplementedError

```

## Screenshots
![Screen Shot 2020-06-19 at 4 13 39 PM](https://user-images.githubusercontent.com/66743784/85433993-56b77c80-b553-11ea-9e67-e22ad257f787.jpg)

## Desktop (please complete the following information):
 - ilastik version: [e.g. 1.3.2b1]
 - OS: [e.g. Ubuntu 18.04, macOS 10.12: Sierra (Fuji), Windows 10]

**Comment by k-dominik** [comment]
Hi @howardli123,

on what windows version are you? We had problems like these in the past on "older" machines, where some already installed libraries would be picked up instead of the ones that come with ilastik.

Could yo maybe check: https://forum.image.sc/t/ilastik-wont-start-on-win8-1pro-since-1-3-0/20545/16?u=k-dominik

**Comment by howardli123** [comment]
That forum fixed it! Thank you so much!
