### ISSUE TITLE
Tile size not updated after typing in a number

### ISSUE THREAD

**Issue by FynnBe** [ilastik/ilastik#2260]
## Describe the bug
Changing the tile size is only possible via the arrow keys, typing in numbers gets ignored (if one does not click inside the pop up window before clicking ok/hitting enter)

## Expected behavior
tile size should be editable by typing numbers!

## To Reproduce
Open any workflow, when data is loaded go to view -> set tile size... 
type in a number and directly hit enter.

![image](https://user-images.githubusercontent.com/15139589/86379347-034bd980-bc8b-11ea-9fde-32b27c5921c9.png)

## Desktop (please complete the following information):
 - ilastik version: 1.4.0b7
 - OS: Windows 10

## Guess at fix:
I suppose this is a Qt gui problem. There might be a setting of that editor box to update the value after typing (and not after leaving the box)..

**Comment by k-dominik** [comment]
interesting, I cannot really reproduce this on windows.

The only explanation I have is that seemingly you are using a tile size with 4 digits and per default the cursor is added left to the last digit. Only four digits are allowed in this field, so before typing you'd have to erase something.

Could you please try again and confirm that this might be the issue?
