### ISSUE TITLE
[BUG] lazyflow prints wrong block memory size if axis order is not xyt / xyz

### ISSUE THREAD

**Issue by boazmohar** [ilastik/ilastik#2271]
[In this line](https://github.com/ilastik/ilastik/blob/73e303dca1317186c1c8da4138f22ff11e4b2fbb/lazyflow/utility/bigRequestStreamer.py#L259):
``` python
fmt = Memory.format(ram_usage_per_requested_pixel * numpy.prod(blockshape[:-1]))
```
There is a wrong assumption that gets rid of the last axis.
If we just move that line to before we insert the `t` and `c` axes (currently line 250 in that file) and change it to
 ``` python
fmt = Memory.format(ram_usage_per_requested_pixel * numpy.prod(blockshape))
```
I think it would solve it.
Sorry for not submitting a PR but I find it hard to setup the environments in python.
I changed it in my "production" code and it gave the correct answer.

Also related to the note in #2268

**Comment by k-dominik** [comment]
Hi @boazmohar,

thank you very much for fixing this. If you prefer not to go through the python environment setup I can commit the changes in your name. Alternatively have a look at our [contributing guidelines](https://github.com/ilastik/ilastik/blob/master/CONTRIBUTING.md). There is a lot of text, but also explanations for every step. If you already have conda and know your way around it it can be quite quick to set it up.
