### ISSUE TITLE
ilastik 1.1.9 is not found

### ISSUE THREAD

**Issue by esn89** [ilastik/ilastik#2273]
I cannot find ilastic 1.1.9 anywhere, even as a release/tag.  I have a version of ClearMap which uses this.

https://github.com/ChristophKirst/ClearMap/blob/master/ClearMap/Settings.py#L19

**Comment by k-dominik** [comment]
Hi @esn89,

our download page is undergoing some revamping to make all archival releases available. In the meantime here are the links

* windows: https://files.ilastik.org/ilastik-1.1.9-win64.exe
* OSX: https://files.ilastik.org/ilastik-1.1.9-OSX.zip
* linux: https://files.ilastik.org/ilastik-1.1.9-Linux.tar.gz

if you start a new project I would strongly recommend to use the latest version of ilastik.

**Comment by esn89** [comment]
Thanks @k-dominik!
