### ISSUE TITLE
[Question] lazyflow module called from python?

### ISSUE THREAD

**Issue by hungyiwu** [ilastik/ilastik#2275]
I found one function `blockwise_view` ([link](https://github.com/ilastik/ilastik/blob/master/lazyflow/utility/blockwise_view.py)) very useful and would like to call it from python, but I don't need other parts of ilastik for now. I couldn't find either `lazyflow` or `ilastik` on https://pypi.org though. Is this use case possible?

**Comment by jjerphan** [comment]
Hi @hungyiwu,

It seems that this function is contained in a file which does not use any other features from ilastik or lazyflow. Hence, you should be able to use this file directly.

Though thoses packages aren't accessible on pypi, [you can still install them from GitHub with `pip`](https://pip.pypa.io/en/stable/reference/pip_install/#vcs-support); in the case of Ilastik for example:

```
pip install git+https://github.com/ilastik/ilastik.git
```

**Comment by hungyiwu** [comment]
@jjerphan Thank you for the explanation!
