### ISSUE TITLE
Use json format for .ilastik_preferences

### ISSUE THREAD

**Issue by m-novikov** [ilastik/ilastik#2300]
`.ilasitk_preferences` file stores information on recently opened projects/images in ilastik. Currently it uses pickle format.

If we use json format for this file, then we can improve ilastik interoperability with other apps like fiji plugin.
Enabling autodiscovery of recent projects and maybe ilastik executable location.

Also using pickle for configuration could be potential security issue.

**Comment by k-dominik** [comment]
I am fully behind going to `.json`, even if it weren't for the additional benefit of being able to access this information from outside ilastik (which is a huge plus, imo). But just being able to finally read that file with a text-editor would be awesome.

**Comment by emilmelnikov** [comment]
It is required to migrate old preferences to a new format?
