### ISSUE TITLE
Need help when I pressed 'Track!' button in automatic tracking (using the animal tracking workflow)

### ISSUE THREAD

**Issue by satorutada** [ilastik/ilastik#2302]
Dear all,
I'm working on the detection of mouse movement with ilastik, and have a problem. Please tell me how to fix this problem. Thank you very much for all your supprot in advance.

PC: System76 LemurPro
OS: Ubuntu 20.04.1 LTS (64 bit)
CPU: Intel® Core™ i7-10510U CPU @ 1.80GHz × 8 
ilastik: 1.3.3post3

## What I did before I saw a but
I took a movie of a wondering mouse in ".mov' format with my iPhone11Pro, and removed audio with ffmpeg.
Then I cropped the movie with HandBrake (1.3.1) to reduce the background. I also put down the Framerate to 5.
HandBrake generated '.m4v' file, so I again used ffmpeg to convert this movie to '.avi' format with 'mjpeg' video codec.
I imported this file to FIJI (1.53c) to convert it into HDF5 format. (Fastest and largest compression selected, and preset standard selected)
Finally, I imported this file to ilastik, and followed the manual below.
https://www.ilastik.org/documentation/animaltracking/animaltracking
I succeeded in "PixelClassification" procedure, and had 2 files ("2493.h5" for the original movie, and "2493-t0-channel0_Probabilities.h5" for the segmentation.

## Describe the bug
I loaded two files above to the ilastik to go on to the automatic trafficking descrived in the "USE CASE" of animal tracking.
I exactly followed the instructions and then I pressed the "Track!" button. Then Error message appeared.

## Expected behavior
Maybe I can have a tracking data of  the animal.

## To Reproduce
I share the link to access my files mentioned above ("2493.avi" original avi file, "2493.h5" and "2493-t0-channel0_Probabilities.h5") so that you can reproduce my trouble. 
https://www.dropbox.com/sh/molfeqh9spbdcaz/AAA5EFoau3ySZX565Y7_XB6aa?dl=0

## Error message/traceback

XmbTextListToTextProperty result code -2
  File "/home/satorubuntu76/Desktop/ilastik-1.3.3post3-Linux/ilastik-meta/ilastik/ilastik/applets/tracking/structured/structuredTrackingGui.py", line 602, in _track
    progressVisitor=self.progressVisitor,
  File "/home/satorubuntu76/Desktop/ilastik-1.3.3post3-Linux/ilastik-meta/ilastik/ilastik/applets/tracking/conservation/opConservationTracking.py", line 517, in track
    hypothesesGraph = self._createHypothesesGraph()
  File "/home/satorubuntu76/Desktop/ilastik-1.3.3post3-Linux/ilastik-meta/ilastik/ilastik/applets/tracking/conservation/opConservationTracking.py", line 308, in _createHypothesesGraph
    progressVisitor=self.progressVisitor,
  File "/home/satorubuntu76/Desktop/ilastik-1.3.3post3-Linux/lib/python3.7/site-packages/hytra/core/ilastikhypothesesgraph.py", line 66, in __init__
    skipLinks=skipLinks,
  File "/home/satorubuntu76/Desktop/ilastik-1.3.3post3-Linux/lib/python3.7/site-packages/hytra/core/hypothesesgraph.py", line 223, in buildFromProbabilityGenerator
    del kdTreeFrames[0]  # this is the current frame
XmbTextListToTextProperty result code -2

## Screenshots
![Screenshot from 2020-09-11 11-18-51](https://user-images.githubusercontent.com/60815868/92849332-2bdc1680-f426-11ea-9cf5-513261a0a24b.png)

## Desktop (please complete the following information):
PC: System76 LemurPro
OS: Ubuntu 20.04.1 LTS (64 bit)
CPU: Intel® Core™ i7-10510U CPU @ 1.80GHz × 8 
ilastik: 1.3.3post3

 Thanks.

**Comment by k-dominik** [comment]
Hi @satorutada,

thank you very much for providing the data! As mentioned in your image.sc thread I will update any findings about this problem in this issue, here on github.

This seems to be a bug. I can reproduce it and am narrowing down the root cause. Will not have time to look into this more today, but will continue tomorrow.

**Comment by satorutada** [comment]
Dear Dr. Dominik,

Thank you very much for your comment and response. I am more than happy to hear that this could be a bug and will be fixed in the future. I appreciate again for your help. Please let me know if I need to share other information regarding this issue. Kindest regards, Satoru

**Comment by k-dominik** [comment]
Hi @satorutada,

turns out this is some very bad user experience from our side. But there is a simple "solution". In tracking there is this size filter, in order to exclude very small, or very large objects. Per default the upper limit is set to 10000 pixels. Your mice, however, are bigger (more in the region of 20000 pixels). You can set this value to something very high to be on the safe side (say, 50000) and tracking should work.

There should really be a _helpful_ message when running into this issue, not this horrible error. Will think about something.

Please let us know if this works for you.

Best
Dominik

**Comment by satorutada** [comment]
Dear Dominik, 

Thank you very much for your valuable comments. I will try your method, and let you know if it works.

Kindest regards,
Satoru

**Comment by satorutada** [comment]
Dear Dominik,

Thanks to your help and comments, I finally succeeded in the automatic tracking of my mice! I really appreciate your help here and in Image.sc Forum.

Best regards,
Satoru TADA
