### ISSUE TITLE
Headless outputs don't match on different systems.

### ISSUE THREAD

**Issue by m-novikov** [ilastik/ilastik#2314]
Running headless using pretrained pixel classification project results in different prediction probabilities maps on different systems/dependencies.
Differences are up to 1 decimal point.
This is surprising as no training is involved.

**Comment by k-dominik** [comment]
this post is still wip, especially regarding performance analysis on osx, windows.

I looked into this a bit - here are some findings:

### Summary:
* `fastfilters` currently, uses some aggressive optimizations when compiled on linux and osx (not on win). Especially switching on `-ffast_math` which leads to _somewhat faster code_ (see performance section), that is _not 100% IEEE compliant_ for floating point operations (see accuracy section).
* We can observe max 1 pixel that changes class with a 0.5 threshold. Retraining the random forest with the same labels (but changed random seed) yields 2372 pixels (`0.2 %`)


### Accuracy

Setting: ilastik pixel classification project trained on linux with ilastik 1.4.0b15, 2dcells_apoptotic (1344x1024x1) with all features on. Comparing headless results running on win, osx, ubuntu for ilastik-1.4.0b15, ubuntu with 1.3.3post3. Furthermore, I once predicted using `--retrain`, which means training the random forest with the same annotations, but different random seed.

For the following tables:
* `pa` - "Platform A"
* `pb` - "Platform B"
* `iva` - "ilastik version A"
* `ivb` - "ilastik version B"
* `flipped` - number of pixels with changed classification outcome, assuming a threshold of `0.5`

#### Features

| pa      | iva              | pb      | ivb              |        mean |         std |         max |
|:--------|:-----------------|:--------|:-----------------|------------:|------------:|------------:|
| Linux   | 1.4.0b15         | Linux   | 1.3.3post3       | 0           | 0           | 0           |
| Darwin  | 1.4.0b15         | Linux   | 1.3.3post3       | 7.38076e-07 | 2.51149e-06 | 0.000366211 |
| Windows | 1.4.0b15         | Linux   | 1.3.3post3       | 2.84554e-08 | 5.95479e-07 | 0.000305176 |
| Linux   | 1.4.0b15         | Darwin  | 1.4.0b15         | 7.38076e-07 | 2.51149e-06 | 0.000366211 |
| Linux   | 1.4.0b15         | Windows | 1.4.0b15         | 2.84554e-08 | 5.95479e-07 | 0.000305176 |
| Darwin  | 1.4.0b15         | Windows | 1.4.0b15         | 7.30659e-07 | 2.47615e-06 | 0.000366211 |

#### Predictions

| pa      | iva              | pb      | ivb              |        mean |         std |   max |   flipped |
|:--------|:-----------------|:--------|:-----------------|------------:|------------:|------:|----------:|
| Linux   | 1.4.0b15         | Linux   | 1.3.3post3       | 0           | 0           |  0    |         0 |
| Darwin  | 1.4.0b15         | Linux   | 1.3.3post3       | 1.51861e-06 | 0.000262312 |  0.09 |         1 |
| Windows | 1.4.0b15         | Linux   | 1.3.3post3       | 8.71931e-08 | 5.65426e-05 |  0.06 |         0 |
| Linux   | 1.4.0b15         | Darwin  | 1.4.0b15         | 1.51861e-06 | 0.000262312 |  0.09 |         1 |
| Linux   | 1.4.0b15         | Windows | 1.4.0b15         | 8.71931e-08 | 5.65426e-05 |  0.06 |         0 |
| Darwin  | 1.4.0b15         | Windows | 1.4.0b15         | 1.51861e-06 | 0.000258405 |  0.09 |         1 |
| Linux   | 1.4.0b15         | Linux   | 1.4.0b15-retrain | 0.00302223  | 0.00985298  |  0.21 |      2372 |
| Darwin  | 1.4.0b15         | Linux   | 1.4.0b15-retrain | 0.00302254  | 0.00985496  |  0.21 |      2373 |
| Windows | 1.4.0b15         | Linux   | 1.4.0b15-retrain | 0.0030223   | 0.00985336  |  0.21 |      2372 |
| Linux   | 1.4.0b15-retrain | Linux   | 1.3.3post3       | 0.00302223  | 0.00985298  |  0.21 |      2372 |


### Performance

2D filters - Linux
|   sigma |   blocksize |   nd |   mean Linux-nofast |   mean Linux-ffast_math |   speedup |
|--------:|------------:|-----:|--------------------:|------------------------:|----------:|
|       1 |          32 |    2 |         2.06255e-05 |             2.02165e-05 |  1.02023  |
|       2 |          32 |    2 |         2.68445e-05 |             2.53952e-05 |  1.05707  |
|       3 |          32 |    2 |         3.53038e-05 |             3.37537e-05 |  1.04592  |
|       5 |          32 |    2 |         7.25466e-05 |             7.02495e-05 |  1.0327   |
|       7 |          32 |    2 |         0.000105844 |             0.000104243 |  1.01536  |
|      10 |          32 |    2 |         0.000187421 |             0.000184386 |  1.01646  |
|       1 |          64 |    2 |         3.11803e-05 |             3.02176e-05 |  1.03186  |
|       2 |          64 |    2 |         4.74746e-05 |             4.54732e-05 |  1.04401  |
|       3 |          64 |    2 |         7.81156e-05 |             6.92277e-05 |  1.12839  |
|       5 |          64 |    2 |         0.000158125 |             0.000157431 |  1.00441  |
|       7 |          64 |    2 |         0.000256092 |             0.000251332 |  1.01894  |
|      10 |          64 |    2 |         0.000481253 |             0.000428982 |  1.12185  |
|       1 |         128 |    2 |         4.84884e-05 |             4.93779e-05 |  0.981987 |
|       2 |         128 |    2 |         8.51342e-05 |             8.61237e-05 |  0.988511 |
|       3 |         128 |    2 |         0.000130491 |             0.000122456 |  1.06561  |
|       5 |         128 |    2 |         0.000310708 |             0.000304841 |  1.01925  |
|       7 |         128 |    2 |         0.000513533 |             0.000503286 |  1.02036  |
|      10 |         128 |    2 |         0.00089689  |             0.000898788 |  0.997888 |
|       1 |         256 |    2 |         0.000116607 |             0.000109371 |  1.06616  |
|       2 |         256 |    2 |         0.000198967 |             0.000200285 |  0.993421 |
|       3 |         256 |    2 |         0.000320008 |             0.00030346  |  1.05453  |
|       5 |         256 |    2 |         0.000710337 |             0.000717574 |  0.989915 |
|       7 |         256 |    2 |         0.00124738  |             0.00115766  |  1.0775   |
|      10 |         256 |    2 |         0.00208884  |             0.00220003  |  0.94946  |
|       1 |         512 |    2 |         0.00101721  |             0.000972408 |  1.04607  |
|       2 |         512 |    2 |         0.00118661  |             0.00123791  |  0.958561 |
|       3 |         512 |    2 |         0.00161851  |             0.00149505  |  1.08258  |
|       5 |         512 |    2 |         0.00258049  |             0.00291823  |  0.884264 |
|       7 |         512 |    2 |         0.00435881  |             0.00384391  |  1.13395  |
|      10 |         512 |    2 |         0.00584491  |             0.00648792  |  0.900891 |
|       1 |        1024 |    2 |         0.00358308  |             0.00349552  |  1.02505  |
|       2 |        1024 |    2 |         0.00449002  |             0.00485051  |  0.92568  |
|       3 |        1024 |    2 |         0.00636392  |             0.00550984  |  1.15501  |
|       5 |        1024 |    2 |         0.00914887  |             0.0108248   |  0.84518  |
|       7 |        1024 |    2 |         0.0155064   |             0.0135454   |  1.14477  |
|      10 |        1024 |    2 |         0.0206169   |             0.0229227   |  0.899409 |
|       1 |        2048 |    2 |         0.0110356   |             0.0106285   |  1.0383   |
|       2 |        2048 |    2 |         0.0137612   |             0.0154405   |  0.891241 |
|       3 |        2048 |    2 |         0.0208676   |             0.0174037   |  1.19904  |
|       5 |        2048 |    2 |         0.0304951   |             0.0370831   |  0.822345 |
|       7 |        2048 |    2 |         0.0581095   |             0.0496481   |  1.17043  |
|      10 |        2048 |    2 |         0.0819758   |             0.0903131   |  0.907684 |

3d filters - Linux

|   sigma |   blocksize |   nd |   mean Linux-ffast_math |   mean Linux-nofast |   speedup |
|--------:|------------:|-----:|------------------------:|--------------------:|----------:|
|       1 |          32 |    3 |             0.00018715  |         0.000195942 |  1.04698  |
|       2 |          32 |    3 |             0.000433397 |         0.000423028 |  0.976075 |
|       3 |          32 |    3 |             0.000722814 |         0.00076663  |  1.06062  |
|       5 |          32 |    3 |             0.00194942  |         0.00191266  |  0.981145 |
|       7 |          32 |    3 |             0.00322964  |         0.00322291  |  0.997916 |
|      10 |          32 |    3 |             0.00584175  |         0.00588843  |  1.00799  |
|       1 |          64 |    3 |             0.00183536  |         0.00188796  |  1.02866  |
|       2 |          64 |    3 |             0.00308996  |         0.00305407  |  0.988383 |
|       3 |          64 |    3 |             0.00456929  |         0.00503933  |  1.10287  |
|       5 |          64 |    3 |             0.0116756   |         0.0112238   |  0.961308 |
|       7 |          64 |    3 |             0.0179223   |         0.0183449   |  1.02358  |
|      10 |          64 |    3 |             0.0312216   |         0.0307839   |  0.985983 |
|       1 |         128 |    3 |             0.0129035   |         0.0119749   |  0.928036 |
|       2 |         128 |    3 |             0.0175711   |         0.0197437   |  1.12365  |
|       3 |         128 |    3 |             0.0286436   |         0.027377    |  0.955782 |
|       5 |         128 |    3 |             0.0568851   |         0.0617294   |  1.08516  |
|       7 |         128 |    3 |             0.0928182   |         0.0910376   |  0.980816 |
|      10 |         128 |    3 |             0.155847    |         0.159373    |  1.02262  |
|       1 |         256 |    3 |             0.063342    |         0.0626173   |  0.988559 |
|       2 |         256 |    3 |             0.105086    |         0.106286    |  1.01142  |
|       3 |         256 |    3 |             0.259912    |         0.262176    |  1.00871  |
|       5 |         256 |    3 |             0.461627    |         0.468909    |  1.01577  |
|       7 |         256 |    3 |             0.771506    |         0.775727    |  1.00547  |
|      10 |         256 |    3 |             1.26509     |         1.26389     |  0.999049 |

**Comment by k-dominik** [comment]
closed via https://github.com/ilastik/fastfilters/pull/7
