### ISSUE TITLE
preferences import fails with specific "old" preferences files

### ISSUE THREAD

**Issue by k-dominik** [ilastik/ilastik#2322]
probably an obscure one, but if users have
* used one of the versions between `1.3.3b2` and `1.3.3rc2`, and
* loaded data from an h5 file

there might be a setting in the form of:

```Python
settings = {
    ...,
    {'inner_paths__role{roleIndex}': {'exported_data'}
}
```
containing a `set` as a value. This cannot be json serialized and will fail on `migrate`. Even worse, it will also partially write a new config, that also cannot be read. On OSX, ilastik will just do nothing (no window, no error).

CC: @emilmelnikov

**Comment by emilmelnikov** [comment]
https://github.com/ilastik/volumina/pull/276 should prevent that from happening.

Since this bug is very rare, and occurs only for a specific beta versions, I'd suggest users to delete their files manually instead of trying to fix this in code.

**Comment by k-dominik** [comment]
agreed.
