### ISSUE TITLE
Does not start on macOS Big Sur

### ISSUE THREAD

**Issue by emilmelnikov** [ilastik/ilastik#2344]
## Describe the bug
ilastik does not work on macOS Big Sur.

## Expected behavior
ilastik should run normally.

## Desktop (please complete the following information):
 - ilastik version: master
 - OS: macOS 11.0.1 (Intel CPU)

ilastik ilastik/ilastik@a7ee78d7936ed573b10c6ff4d8733e1f126a00ea
volumina ilastik/volumina@64b12218163e6fa9b7ccde6460ee2f79c93f2bdd

---

The execution hangs when Qt tries to show the splash screen: https://github.com/ilastik/ilastik/blob/a7ee78d7936ed573b10c6ff4d8733e1f126a00ea/ilastik/shell/gui/startShellGui.py#L65

Quick experimentation showed that removing the splash screen does nothing (the application still hangs).

**Comment by emilmelnikov** [comment]
It seems that this is an upstream problem. I tried running a hello world app in a separate environment with the following versions and code, with the same results:

* qt 5.12.9 (build `h717870c_0`) from conda-forge
* pyqt 5.12.3 (build `py39h9d385e7_4`) from conda-forge

```python
import sys
from PyQt5.QtWidgets import QApplication, QWidget, QLabel
from PyQt5.QtGui import QIcon
from PyQt5.QtCore import pyqtSlot

def window():
   app = QApplication(sys.argv)
   widget = QWidget()

   textLabel = QLabel(widget)
   textLabel.setText("Hello World!")
   textLabel.move(110,85)

   widget.setGeometry(50,50,320,200)
   widget.setWindowTitle("PyQt5 Example")
   widget.show()
   sys.exit(app.exec_())

if __name__ == '__main__':
   window()
```

**Comment by m-novikov** [comment]
Maybe related [macOS unable to open any non-Apple application](https://twitter.com/lapcatsoftware/status/1326990296412991489)

**Comment by emilmelnikov** [comment]
It's probably because all these packages contain Qt built with the older XCode versions: https://bugreports.qt.io/browse/QTBUG-87014

**Comment by emilmelnikov** [comment]
The solution is to `export QT_MAC_WANTS_LAYER=1`.
