### ISSUE TITLE
Rotate and/or delete old logs

### ISSUE THREAD

**Issue by emilmelnikov** [ilastik/ilastik#2347]
Currently, my ilastik log file (which starts from 25.09.2020) weighs 42.3 MB. I could imagine users being annoyed by huge logs because it's hard to find relevant information from a recent run. Also, it's too much space just for a log file.

We could rotate and compress old logs (by size/date), and also delete very old rotated ones (say, after 1 year).

As a related issue, it would be great to reduce the number of log lines too, especially warnings and repeated messages, but this obviously requires much more effort.

cc @k-dominik @m-novikov @Tomaz-Vieira

**Comment by k-dominik** [comment]
I'm fully in favor! I got around this by frequently deleting it before any experimentation. 42,3 megs - that's impressive...

I'm not sure if we need to go through the trouble of rotation, and compression and all that. bash_history also just cuts off after a while... I mean we will not do any analysis of sorts by screening logs, like e.g. when you have something like a service that you monitor. In any case `RotatingFileHandler` has everything we'd need there, with multiple files, or just a single one...
