### ISSUE TITLE
revert osx BIG sur workaround once python dependency plays nice with it

### ISSUE THREAD

**Issue by k-dominik** [ilastik/ilastik#2360]
see #2345 

revert https://github.com/ilastik/ilastik/commit/82e2932f0274c2abf69d04feced327ae253b5452

**Comment by emilmelnikov** [comment]
Related: https://github.com/ilastik/volumina/pull/277

**Comment by k-dominik** [comment]
> Related: [ilastik/volumina#277](https://github.com/ilastik/volumina/pull/277)

but that one can probably stay. No need to import that stuff if we don't intend to show it :)

**Comment by emilmelnikov** [comment]
> > Related: [ilastik/volumina#277](https://github.com/ilastik/volumina/pull/277)
> 
> but that one can probably stay. No need to import that stuff if we don't intend to show it :)

This is true, but it would be nice to reorganize code so that it doesn't have a big condition. Of course, not a priority.
