### ISSUE TITLE
no cache while  using live update 

### ISSUE THREAD

**Issue by hfl112** [ilastik/ilastik#2370]
## Describe the bug
(MAC version)
because of too many pics, my ilastik just stopped at live update while doing pixel classification 
After I shut the software and reload the file, it is still the same. Ilastik seems to just stop at the final step, because every time I tried it stopped at the same place. 

## Expected behavior
Please add a clear and concise description of what you expected to happen.

it Always have 48-50 active requests with no caches, seems quite weird.

Any advices might help. Should I update ilastik to the latest version?

**Comment by k-dominik** [comment]
Hi @hfl112,

sorry for not getting back to you earlier. Could you add a little detail on what you are doing? Did you add a lot of annotations, by any chance (say very thick brushes on all your images)?
Can you verify in the Activity Monitor that ilastik is indeed not doing anything?
What version of ilastik are you using?

Cheers
Dominik

**Comment by k-dominik** [comment]
closing, not really reproducible with the supplied amount of details.
