### ISSUE TITLE
Blank dropdown menu

### ISSUE THREAD

**Issue by elatella** [ilastik/ilastik#2402]
## Describe the bug
When I use the GUI and click on dropdown menu buttons, such as Projects/Settings or Help  but also on Add New, a blank dropdown menu appears. It has various sizes and when I blindly click into the menu things happen but the words in the dropdown menu are missing and it is a bit difficult to guess what each space in the menu does.

## Expected behavior
I expected the dropdown menu to open, containing texts describing the different things it does when clicked. such as "open new" "save project"...

## To Reproduce
Use Ubuntu 20.04.2 LTS
Install ilastik 1.3.2 as described on the website
Open Ilastik, click on any button that should prompt a dropdown menu.

## Screenshots
![ilastik_01](https://user-images.githubusercontent.com/44403256/109153773-a21ecc00-776d-11eb-980d-dedcbd95b50e.png)

## Desktop (please complete the following information):
 - ilastik version: [1.3.2]
 - OS: Ubuntu 20.04.2 LTS

**Comment by k-dominik** [comment]
Hello @elatella ,

thank you for the report! Is there a particular reason that you do not use a later version of ilastik (I would recommend the latest beta..)?

In any case, I think I remember a related problem. The solution was adding this environment variable before you start ilastik:

```bash
export QT_STYLE_OVERRIDE=gtk2
./run_ilastik.sh
```

Please let us know if this solves your issue.
Cheers
Dominik

**Comment by elatella** [comment]
Hi @k-dominik 

I didn't realise that I used an old version. I installed the new version and it all works great (just maybe the location pointers in the add New dropdown menu are swapped).
Thank you so much for the quick fix.

Best!
