### ISSUE TITLE
Saved ilp model not running in command line

### ISSUE THREAD

**Issue by alecrimi** [ilastik/ilastik#2406]
## Describe the bug
Saved ilp model not running in command line

## Expected behavior
I have loaded  a training image, draw some class lables, be satisfied how they look in the gui. Saved th ilp file, run it on command line using the saved project.
 
## Error message/traceback
 
```pytb
ERROR 2021-03-03 22:10:31,410 objectClassificationWorkflow 65243 140336518113088 Can't run batch prediction.
Couldn't obtain a classifier from your project file: advessel.ilp.
Please make sure your project is fully configured with a trained classifier.


```
 

## Desktop (please complete the following information):
 - ilastik version: [e.g. 1.3.3]
 - OS: [e.g. Ubuntu 18.04,  ]

**Comment by k-dominik** [comment]
Hello @alecrimi,

sorry for not getting back earlier - this slipped my attention.
Are you in the object classification workflow? It looks like you have added an annotation or something like that without live-update on (hence the classifier is invalid - does not match your current set of annotations). Solution to this would be opening the project file, turning live update on, and then saving the project.

Cheers
Dominik

**Comment by k-dominik** [comment]
closing this - without a reply for over a year.
