### ISSUE TITLE
Cannot Change Display Settings during Object Classification

### ISSUE THREAD

**Issue by tischi** [ilastik/ilastik#2420]
ilastik 1.3.3post2

When trying to Adjust Thresholds...

<img width="326" alt="image" src="https://user-images.githubusercontent.com/2157566/115146471-f1d79080-a056-11eb-9bd9-998ae2f7d708.png">

...I am getting this error:

<img width="739" alt="image" src="https://user-images.githubusercontent.com/2157566/115146466-eab08280-a056-11eb-8287-c6256b29a9cd.png">

**Comment by k-dominik** [comment]
this is fixed in the current beta....
