### ISSUE TITLE
Can no longer add new raw data images into ilastik

### ISSUE THREAD

**Issue by csun606** [ilastik/ilastik#2426]
Hi everyone,

I have been using ilastik for a while with no issues, but when I came to start a new Pixel Classification project, I received the following error pop-up (no text though):
![IlastikError_10May21](https://user-images.githubusercontent.com/66408818/117594523-5b4c4a00-b192-11eb-8b50-482d32283b8f.PNG)

Log below:
[ilastik_log.txt](https://github.com/ilastik/ilastik/files/6448834/ilastik_log.txt)

I tried an uninstall/reinstall to no avail. Any help would be greatly appreciated!

Cherry

#2387

**Comment by k-dominik** [comment]
Hello @csun606,

thank you for including the log. It appears that ilastik cannot has problems with the tiff image you are supplying. We do not support _all_ tiff flavors that are around. In case ilastik cannot open your image, we recommend using the [ilastik fiji import/export plugin](https://www.ilastik.org/documentation/fiji_export/plugin) and saving the image in question via Fiji using the plugin. This has the added benefit of speeding up processing in ilastik.

Do you know how this particular tiff file was produced?

**Comment by csun606** [comment]
Thanks @k-dominik !
Tried the export plugin but it is giving error messages (no data in HDF5 file?) but now able to import TIFFs again as long as I drag and drop files, rather than using the 'Select Raw Data Files' option, although unsure why... But hey if it works I'm happy!
Will consider this issue closed for now :)
