### ISSUE TITLE
Could not load project file

### ISSUE THREAD

**Issue by kelvinlee760948065** [ilastik/ilastik#2432]
Once I have built an ilastik project and soon I moved the input pictures somewhere. 
Next time it told me that the input pictures missed and asked me to choose the input pictures again.
But this time I choose the pictures with filepath named in Chinese. And the project file could not be loaded forever.

![image](https://user-images.githubusercontent.com/71078929/120065469-0a9a8380-c0a4-11eb-85f5-d8d37a518a01.png)

![image](https://user-images.githubusercontent.com/71078929/120065460-fb1b3a80-c0a3-11eb-8c2e-a10384f04e63.png)

**Comment by k-dominik** [comment]
hi @kelvinlee760948065,

thank you very much for reporting this issue! This is in fact related to #2431, very sorry that you ran into this. I will close _this_ issue (and keep #2431) to make it a little bit easier to track.

In short - if you want to have chinese characters in your file name, convert your data to hdf5, e.g. using our [fiji import/export plugin](https://www.ilastik.org/documentation/fiji_export/plugin). If you want to keep using tiffs, then _right now_ there is no other way than removing any special characters from your path (only ascii will work).

Cheers
Dominik
