### ISSUE TITLE
Live view won't load past 80%

### ISSUE THREAD

**Issue by c-morgans** [ilastik/ilastik#2438]
After annotating my image, I press live view but it won't render past 80%. I left a TIF file for 3 hours, then started a new project and tried again with 2 different images but it still wouldn't load past 80%.  When I tried closing the application it froze and crashed. When I tried to open the project it said "Corrupted Project" Unable to open project file "

I don't think the live view should take longer than half an hour max to update (especially with only one image) and shouldn't crash. 

I am very new to this program so is hopefully a simple fix!

![screenshot ilastic](https://user-images.githubusercontent.com/85984222/122330472-994d4280-cf76-11eb-92eb-a7bc6deb4078.PNG)

**Comment by k-dominik** [comment]
Hello @c-morgans,

I can see that what you report is super frustrating. Live update is intended to be more or less instant - half an hour is definitely already way too much..

Multiple things are at play, your ilastik instance is stuck in training (that is my guess at least) - some observations given the attached screenshot:


* You are using tif files. ilastik performs somewhat not ideal when used with tif files. Ideally we need a format where small blocks or tiles can be accessed efficiently. For such cases we usually [recommend converting the data in fiji to hdf5 with the ilastik import/export plugin](https://www.ilastik.org/documentation/fiji_export/plugin).
* I am not sure what brush size you have used, but it seems you have added a lot of annotations with (bigger) brushes. The classifier used in ilastik is not really made for that (and does not necessarily perform better with more training data). We recommend starting with a small brush (size 3, maybe - personally I use size 1 usually) and annotate only a little - then go directly to live update, and correct the classifier where it is wrong, always observing the changes.
* if you are not using the latest beta version (I think we introduced data-dependent setting of this data in 1.4.0b14), then the default tile size in ilastik is more geared towards 3D data. You could check in the training applet, by going to the Menu: _View -> Set Tile Width ..._. A setting of `512` should be good for your data.

Some general considerations are also the scale of the data, but it looks like you are interested in small things, so downscaling might not be an option. What is roughy the size of this image?

**Comment by c-morgans** [comment]
Hi @k-dominik 

Thank you so much for your help! It appears as though I was over-annotating, I tried using smaller brush strokes and annotating less and it loads quickly now.

Cheers!

**Comment by k-dominik** [comment]
awesome!
