### ISSUE TITLE
3D widget not visible

### ISSUE THREAD

**Issue by zoelx** [ilastik/ilastik#2461]
For me it says
> 3D widget disabled via $HOME/.voluminarc or environment variable
> VOLUMINA_SHOW_3D_WIDGET
> Example .voluminarc
> `[volumina]`
> `show_3d_widget: true`

when I option for 'Show 3D' in the GUI.

I have tried both setting the variable (via `export VOLUMINA_SHOW_3D_WIDGET=true`) and adding a new `.voluminarc`-file in my home folder and after this restarted ilastik but so far I was not able to get a 3D view.

(ilastik version: 1.4.0b15-OSX, macOS 11.01: BigSur)

**Comment by k-dominik** [comment]
Hello @zoelx,

this is currently the limitation we have with BigSur...  Currently there is no way around that. From our download page:

>  Dear macOS users, if you have upgraded to macOS 11 (Big Sur), please download the latest ilastik beta version (1.4.0b11 or newer). Currently, there is no 3D preview in Carving, all other functionality should work as expected. This message will disappear once we can offer full support of ilastik on macOS Big Sur in the latest release.

**Comment by zoelx** [comment]
So not only in Carving? Thank you for clarifying.

**Comment by k-dominik** [comment]
well, the 3D widget pretty much is only used in Carving.
