### ISSUE TITLE
second round of training in autocontext does not allow image adjustment 

### ISSUE THREAD

**Issue by jimmib78** [ilastik/ilastik#2462]
## Describe the bug
I am playing with Autocontext in Ilastik, on a multi-channel image (4).
When I get to the second round of training. The brightness of all channels is way up, and when I try and adjust then i get the error,
“TypeError: ‘bool’ object is not subscriptable”

## Expected behavior
I expect the image brightness to a be adjustable as in the first training.

## To Reproduce
Within the autocontext(2-stage) workflow
1. Add some 4D data in the data selection applet
2. Proceeded through the first round of training
3.at the second round of training right click on the raw input tab and select "Adjust Thresholds

## Error message/traceback
“TypeError: ‘bool’ object is not subscriptable”

If applicable, please add tracebacks with formatting, such as

In the log file it looks like
```ERROR 2021-07-24 12:45:57,128 excepthooks 36700 34520 Unhandled exception in thread: ‘MainThread’
ERROR 2021-07-24 12:45:57,129 excepthooks 36700 34520 Traceback (most recent call last):
File “C:\Program Files\ilastik-1.3.3post2\ilastik-meta\volumina\volumina\widgets\layercontextmenu.py”, line 53, in adjust_thresholds_callback
dlg = GrayscaleLayerDialog(layer, menu.parent())
File “C:\Program Files\ilastik-1.3.3post2\ilastik-meta\volumina\volumina\widgets\layerDialog.py”, line 60, in init
self.grayChannelThresholdingWidget.setValue(layer.normalize[0][0], layer.normalize[0][1])
TypeError: ‘bool’ object is not subscriptable
```

## Screenshots
If applicable, please add screenshots to help explain your problem.

## Desktop (please complete the following information):
 - ilastik version:1.3.3post2
 - OS:  Windows 10

**Comment by k-dominik** [comment]
Hello @jimmib78,

thank you very much for the report and sorry you ran into this. As mentioned on [image.sc](https://forum.image.sc/t/ilastik-autocontext-error/55633) this issue is fixed in [the latest beta](https://www.ilastik.org/download.html#beta).

xref: https://github.com/ilastik/ilastik/issues/2281 
fix: https://github.com/ilastik/volumina/pull/265
