### ISSUE TITLE
Not support for macOS version 10.15.3

### ISSUE THREAD

**Issue by alice45678** [ilastik/ilastik#2477]
I am not able to install ilastik on my mac pro which has version macOS 10.15.3
When I made a double click, it showed the following warning.
Do you have any advices for this issue? Thank you!

## Screenshots
![Screenshot 2021-09-15 at 11 28 36](https://user-images.githubusercontent.com/39770544/133408302-cbf99223-f069-4fa4-a469-e28f833d91af.png)

**Comment by k-dominik** [comment]
Hi Alice!

This is, unfortunately a common problem with almost all open source software (that is not signed with a apple developer certificate). Do the instructions [here](https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac) resolve the problem for you?

Cheers
Dominik

**Comment by alice45678** [comment]
> Hi Alice!
> 
> This is, unfortunately a common problem with almost all open source software (that is not signed with a apple developer certificate). Do the instructions [here](https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac) resolve the problem for you?
> 
> Cheers
> Dominik

Hi Dominik,
Yes, I made a right click and clicked open. It works.

Thank you!

**Comment by k-dominik** [comment]
awesome, thx for getting back and closing :)
