### ISSUE TITLE
Question: anyone knows the location of the log file?

### ISSUE THREAD

**Issue by dfmuriel** [ilastik/ilastik#2505]
anyone knows the location of the log file?

**Comment by k-dominik** [comment]
Hello @dfmuriel,

sure, the location of the log files is known. It depends on the version of ilastik that you are using:


from `1.4.0b8` on, it's easiest to go via the gui: _Settings -> Open log folder_
for completeness, the locations are

* win: `C:\Users\<USERNAME>\AppData\Local\ilastik\Logs`
* osx: `/Users/<USERNAME>/Library/Logs/ilastik`
* linux: `/home/<USERNAME>/.cache/ilastik`


before it the log file (`ilastik_log.txt`) would be located in the home folder:

<details>

* win: `C:\Users\<USERNAME>\ilastik_log.txt`
* osx: `/Users/<USERNAME>/ilastik_log.txt`
* linux: `/home/<USERNAME>/ilastik_log.txt`

</details>
