### ISSUE TITLE
SHA256/MD5 security Hash

### ISSUE THREAD

**Issue by mezwick** [ilastik/ilastik#2507]
Hi.

Are you able to provide either an SHA256 or MD5 Hash for Ilastik (specifically windows Version 1.3.3, ideally also for latest windows beta releases 1.4.0b20 and 1.4.0b20-gpu)? 

This is being requested by my local IT department team to check file install intergrity prior to installing Ilastik >.<

Thanks!
Merrick

**Comment by k-dominik** [comment]
Hello @mezwick,

we have sha256 for all of our versions. for download, you can access them by appending `.sha256` to the binary link.

so, e.g.

* windows 1.3.3post3
  * binary: https://files.ilastik.org/ilastik-1.3.3post3-win64.exe
  * checksum https://files.ilastik.org/ilastik-1.3.3post3-win64.exe.sha256 
* windows 1.4.0b20
  * binary: https://files.ilastik.org/ilastik-1.4.0b20-win64.exe
  * checksum: https://files.ilastik.org/ilastik-1.4.0b20-win64.exe.sha256

we should make this obvious from the download page, thank you for pointing it out!!

**Comment by mezwick** [comment]
Fantastic. Thanks!
