### ISSUE TITLE
Multicut workflow is broken in latest beta

### ISSUE THREAD

**Issue by constantinpape** [ilastik/ilastik#2543]
The multicut workflow is broken in the latest beta version (1.4.0b23): when clicking on `Training and Multicut` after running the watershed it opens an error message:
![ilastik-mc-bug](https://user-images.githubusercontent.com/4263537/153925136-9e3784a6-2b0a-4720-b573-95e32010f48d.png)

I checked the previous beta version (1.4.0b21) and the issue is not present there.

**Comment by k-dominik** [comment]
packaged an older version of volumina for this release by accident - thx for reporting
