### ISSUE TITLE
Autocontext workflow on multichannel data

### ISSUE THREAD

**Issue by DSbioimaging** [ilastik/ilastik#2567]
## Describe the bug
I created an Auto-context workflow using multichannel fluorescence microscopy 3D data. After a first successful training round, the second training applet shows a data window with only the first channel.  

## Expected behavior
All raw data channels should be visible in the second training round.

## To Reproduce
Within the ... workflow
1. Add some [3d] multichannel data in the data selection applet, the raw data is visible with RGB lookup tables 
2. Train first pixel classifier
3. Go to second training applet
4. Click on Raw Input-->Adjust Thresholds-->only one channel is visible

## Error message/traceback

If applicable, please add tracebacks with formatting, such as

NA

## Screenshots
If applicable, please add screenshots to help explain your problem.

## Desktop (please complete the following information):
 - ilastik version: [e.g. 1.4.0]
 - OS: [Windows 10]

**Comment by k-dominik** [comment]
Hi @DSbiomedAU,

sorry you are running into this. This is a bit of an inconvenience in ilastik. I assume you have either a 2 or 3 channel dataset, which ilastik per default maps to the RGB space (showing the first channel in red, the second in green the third in blue). So far so good. For more channels than two or three, the channels will be shown separately.
In the second round of autocontext, internally in ilastik, the new probabilities, are stacked on top of the raw data, and then you have at least 4 or more channels. As stated above, those are then shown separately.
While it is not possible to get the colored view back in the second round, you can cycle through the channels to see them individually:
![Screenshot 2022-04-19 at 16 03 27](https://user-images.githubusercontent.com/24434157/164022620-5a760968-cef3-483c-87cf-1bc866ac1fdf.png)

**Comment by DSbiomedAU** [comment]
Hi Dominik, thanks for the suggestion! I missed the toggle and it definitely could work for my case (multiple classes, very complex image from intravital microscopy).
