### ISSUE TITLE
What hardware does ilastik comsume most in an intense workflow, CPU or GPU ?

### ISSUE THREAD

**Issue by samuelsuntree** [ilastik/ilastik#2575]

**Comment by samuelsuntree** [comment]
One of my friends is planning to build a workstation speciallized for ilastik, but we are not sure which part of the hardware is the major part of the consumption in a regular workflow(especially in [Pixel Classification] and [Voxel Segmentation Workflow]), CPU or GPU? We would like to know the most important part and use the funding in a proper way, and would be so
very grateful to get informed!

**Comment by k-dominik** [comment]
Hello @samuelsuntree,

[Pixel Classification](https://www.ilastik.org/documentation/pixelclassification/pixelclassification) and Voxel Segmantation are both CPU-bound. So for good performance you'd want something like 4 or 8 cores (intel will probably be faster compared to amd). One crucial part is also the amount of RAM, especially if you work in 3D and are planning to maybe also use the [Autocontext](https://www.ilastik.org/documentation/autocontext/autocontext) workflow. Then I'd say you should aim for a minimum of 32GB. More is better.

The GPU can be utilized in the [Neural Network Classification](https://www.ilastik.org/documentation/nn/nn) workflow (pre-trained networks available in the [bioimage.io model zoo](https://bioimage.io/#/)). It also works on CPU, but with an Nvidia GPU it is way faster.

Hope this helps!

**Comment by samuelsuntree** [comment]
Thanks a lot ! Actually he is planning to build a workstation with a double-3090 GPU and a 64-core AMD EPYC CPU with 1T RAM for the usage of the whole lab, so i guess it meets the requirment ! However, I noticed that you mentioned Intel is faster than AMD, so is there any issue for AMD in ilastik(such as instruction set miss) ? If not, I think we can start the purchasing process. Thank you very much again, dear dominik !

> Hello @samuelsuntree,
> 
> [Pixel Classification](https://www.ilastik.org/documentation/pixelclassification/pixelclassification) and Voxel Segmantation are both CPU-bound. So for good performance you'd want something like 4 or 8 cores (intel will probably be faster compared to amd). One crucial part is also the amount of RAM, especially if you work in 3D and are planning to maybe also use the [Autocontext](https://www.ilastik.org/documentation/autocontext/autocontext) workflow. Then I'd say you should aim for a minimum of 32GB. More is better.
> 
> The GPU can be utilized in the [Neural Network Classification](https://www.ilastik.org/documentation/nn/nn) workflow (pre-trained networks available in the [bioimage.io model zoo](https://bioimage.io/#/)). It also works on CPU, but with an Nvidia GPU it is way faster.
> 
> Hope this helps!

**Comment by k-dominik** [comment]
Hey, one of the main reasons is mkl, which is involved in many numpy and pytorch operations. This library comes from intel and it is notorious for underperforming on amd for artificial reasons.

**Comment by k-dominik** [comment]
Hi @samuelsuntree,

I'll close this issues - feel free to reopen it, or open a new one if you have further issues/questions!

Cheers
Dominik
