### ISSUE TITLE
the ssl certificate for the download site expired 0n 7/10/2022

### ISSUE THREAD

**Issue by ChrisNeefus** [ilastik/ilastik#2597]

**Comment by k-dominik** [comment]
thank you for the report, we'll try to resolve this as quickly as possible and keep you updated

**Comment by k-dominik** [comment]
Hi @ChrisNeefus,

for the time being we added alternative links (under "mirror") for the most important downloads to keep things moving, while the SSL certificate issue is being resolved.

Cheers
Dominik

**Comment by k-dominik** [comment]
Certificate has been updated - again, @ChrisNeefus, thank you very much for making us aware of that!!
