### ISSUE TITLE
Carving, changing superpixels while segmenting results in inconsistent state

### ISSUE THREAD

**Issue by k-dominik** [ilastik/ilastik#2627]
## Describe the bug
When doing carving (first object) and doing some annotations, segmenting... then going back to `Preprocessing`, changing any of the values resulting in different superpixels, the Labeling Applet seems to be in an inconsistent state. Annotations are still visible, previous segmentation is still visible, clicking `segment` makes it disappear. Adding more annotations will only reflect the new ones in the segmentation. The old annotations remain visible though.

## Expected behavior

Annotations should probably remain, segmentation should get invalidated and disappear, clicking segment should also use the "old" annotations.

## To Reproduce
Within the Carving workflow
1. Add some data in the data selection applet
2. Do any kind of preprocessing
3. Annotate some background and foreground, click segment
5. go back and change superpixel settings, create new superpixels
6. in labeling, click segment (old segmentation disappears, labels are still visible)
7. even add new labels and see that old labels, while they remain visible, are not at all used in the solution.

## Error message/traceback

No Error!

## Screenshots

<img width="405" alt="image" src="https://user-images.githubusercontent.com/24434157/197477343-e74078f0-da61-468d-a539-fcd4b8691af1.png">

## Desktop (please complete the following information):
 - ilastik version: `1.4.0rc6`
 - OS: All operating systems

**Comment by btbest** [comment]
Duplicates #1214
