### ISSUE TITLE
Multicut creates .hdf5 tile border-based superpixels on Windows 10

### ISSUE THREAD

**Issue by kbestak** [ilastik/ilastik#2661]
## Bug description
I started a new Boundary-based Segmentation with Multicut project. Used the raw image and probabilities exported from pixel classification as Input Data. The DT Watershed produced a grid-like segmentation pattern (in addition to the expected cell segmentation) as seen below. Even the background, which was masked out of the pixel classification got segmented into the 512x512 tiles.
![image](https://user-images.githubusercontent.com/86408271/214805687-d311f41b-2254-48a5-a474-5bb434642ce2.png)

## Expected behavior
To confirm if this was indeed a Windows problem, a colleague used the exact same files as Input Data and was able to get a segmentation without the above mentioned grid effect on a Mac device.

## To Reproduce
Within the Boundary-based Segmentation with Multicut workflow
1. Add raw image (ome.tif converted to .h5 with the Fiji ilastik plugin) and probability map (exported from the Pixel classification workflow).
2. Go to DT Watershed, select any Input Channel and click "Update Watershed"

## Desktop:
 - ilastik version: 1.4.0rc8
 - OS: Windows 10

**Comment by k-dominik** [comment]
Dear @kbestak,

we have recently changed the processing in the superpixel generation to run in parallel. This enables processing of larger files (and is in general faster). As you have noticed, this introduced "artificial" block boundaries. We have so far found that, either given a sufficiently good boundary map and going to the multicut directly, or training a random forest classifier on the edges will get rid of these boundaries in the final result quite easily.

As for the masking: this is not supported in the multicut workflow. Multicut will always run on the whole image. Apart from the longer running time during superpixel generation, for solving the multicut problem it shouldn't have a noticeable influence on running time.

Cheers
Dominik
