### ISSUE TITLE
what can I do if I want to quanfity  the width and the length of  rob-shaped bacteria?

### ISSUE THREAD

**Issue by AD-CQ** [ilastik/ilastik#2679]
## Morphological parameters of bacteria
Length, width, area, volum,circularity,cavature,

## Scenario

I took images of Ecoli grown between a glass cover slip and an agar pad and I want to quantify their length, width,area and maybe other features (circularity,cavature) . I firstly use Pixel Classification to obtain segementation output and then I want to use  Object Classification to distinguish seperated cells and connetted cell, finally I want to get the length/width/area of the seperated cells to quantify the cell size. BUT I don't know which current parameters I can use to represent the  length/width/area of the seperated cells?

## Rationale

It is improtant to quanfity the cell size of bacterial cells.

**Comment by k-dominik** [comment]
Hi @AD-CQ,

I hope you don't mind that we close this and keep [this on image.sc](https://forum.image.sc/t/how-can-i-use-ilastik-to-quantify-the-morphological-parameters-of-bacteria/77535?u=k-dominik)

Cheers
Dominik
