### ISSUE TITLE
Pip install from repo misses requirements

### ISSUE THREAD

**Issue by azagajewski** [ilastik/ilastik#2697]
## Describe the bug
Tried pip installing ilastik directly from the repo for better integration with other systems. Ilastik installs but without dependencies.

## Expected behavior
Ilastik installs successfully with all dependencies.

## To Reproduce
Steps to reproduce the behaviour:

pip install -e git+https://github.com/ilastik/ilastik.git#egg=ilastik-core 
python import ilastik

## Error message/traceback

```pytb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\AEZW\dataengine\src\ilastik-core\ilastik\__init__.py", line 28, in <module>
    import h5py
ModuleNotFoundError: No module named 'h5py'

```

## Screenshots
If applicable, please add screenshots to help explain your problem.

N/A

## Desktop (please complete the following information):

 - OS: [Windows 10]

**Comment by k-dominik** [comment]
Hi @azagajewski,

we don't support installation via pip (unless you installed all the dependencies vie conda already).

The preferred way is to follow the [instructions in the readme](https://github.com/ilastik/ilastik#installation).

Cheers
Dominik
