### ISSUE TITLE
Vigranumpycore import failed

### ISSUE THREAD

**Issue by userInsider** [ilastik/ilastik#2712]
Hi, I'm not a dev at all. So, I need help regarding my problem.

I am trying to use the script from the link below:
https://github.com/ilastik/ilastik/blob/main/examples/example_python_client.py

But I can't manage to import the vigra library. I got this error:
Traceback (most recent call last):
  File "Ilastik_python_client.py", line 25 (88), in <module>
    import vigra
  File "C:\Program Files/ilastik-1.4.0rc2/Lib/site-packages\vigra\__init__.py", line 113, in <module>
    import vigra.vigranumpycore as vigranumpycore
ImportError: DLL load failed while importing vigranumpycore: The specified module could not be found.

I am working on windows.

Thank you in advance for your help.

**Comment by k-dominik** [comment]
Hi @userInsider,

I'm closing this issue, as there's not really much else we can do in addition to pointing to the conda installation. Please reopen/create a new issue in case you run into anything else, or have questions of any kind!

Cheers
Dominik
