### ISSUE TITLE
add "clear log" functionality

### ISSUE THREAD

**Issue by k-dominik** [ilastik/ilastik#2717]
Since we never delete the log it can grow to unfortunate sizes. So when I ask users for logs, I usually describe the following procedure: 

1. Start up ilastik
2. go to Settings → Open Log Folder
3. delete the log.txt file
4. restart ilastik
5. open the project in question and look at the log.txt file.

which is a bit cumbersome. I'd suggest to have a new menu entry to clear the log file, no restart required.

**Comment by emilmelnikov** [comment]
Does it make sense to delete old logs automatically? For example, if they are at least 6 months old and occupy more than 100MB.

**Comment by emilmelnikov** [comment]
It just seems to me that clearing log files is not something users should do themselves, and it should be done automatically (obviously, with some reasonable caveats, like always keep recent logs). If someone really wants/needs to do this, they can _Open log file directory_ and delete them as usual files.

**Comment by k-dominik** [comment]
> It just seems to me that clearing log files is not something users should do themselves, and it should be done automatically (obviously, with some reasonable caveats, like always keep recent logs). 

why?

again, I want to shortcut the process from 5 steps to 2 steps.

**Comment by emilmelnikov** [comment]
Sure, we could do that, but I think it would be even better to have 0 steps, not 2 for the common case.

**Comment by k-dominik** [comment]
there will always be one step :D

**Comment by k-dominik** [comment]
not needed anymore  with session logs introduced in #2879 :)
