### ISSUE TITLE
Update README to instruct how to setup a dev environment and run ilastik from code.

### ISSUE THREAD

**Issue by phamtronglam** [ilastik/ilastik#2719]
As the title says, sometimes non developers also want to run ilastik from code.
Could you provide some instructions on how to do it?

Thanks a lot.

----------------------------------------
I tried myself with the following and got error.

Step 1. Setup dev environment
```
cd dev
conda env create -n ilastik-dev -f environment-dev.yml -y
conda activate ilastik-dev
```

Step2. Try to run python setup.py but failed.
```
pip install setuptools_scm
python setup.py
```

```
Traceback (most recent call last):
  File "D:\tmp\ilastik-try_turn_off_proxy\setup.py", line 4, in <module>
    _version = setuptools_scm.get_version(write_to="ilastik/_version.py")
  File "D:\miniconda3_windows\envs\ilastik-dev\lib\site-packages\setuptools_scm\__init__.py", line 148, in get_version
    _version_missing(config)
  File "D:\miniconda3_windows\envs\ilastik-dev\lib\site-packages\setuptools_scm\__init__.py", line 108, in _version_missing
    raise LookupError(
LookupError: setuptools-scm was unable to detect version for D:\tmp\ilastik-try_turn_off_proxy.

Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj

```

**Comment by k-dominik** [comment]
Hi @phamtronglam,

of course it makes total sense to run code for developers! It seems that currently, `setuptools_scm` and `pip` are missing from [`dev/environment-dev.yml`](https://github.com/ilastik/ilastik/blob/128c5e6d870831985010a960dd44b11a948e7295/dev/environment-dev.yml#L56). Thank you for bringing that up! If those are present then you can do point 5 from our CONTRIBUTING guidelines:

```
conda activate ilastik
# from the folder containing ilastik and volumina
pip install --editable ilastik
pip install --editable volumina
```

this enables you to run code. We recommend using an editable install over doing `python setup.py`.

Do you think you could open a pull request, adding those dependencies to the `dev/environment-dev.yml` file?

See also [our git workflow](https://github.com/ilastik/ilastik/blob/main/CONTRIBUTING.md#workflow).

**Comment by phamtronglam** [comment]
Hi @k-dominik,

Thanks for your quick reply.
Certainly I would love to open a pull request (I'm not comfortable with git workflow yet, though).

However, I encountered the following error trying to `pip install --editable ilastik`. Please check.

```
(ilastik) D:\tmp\ilastik-main\ilastik>pip install --editable ilastik
ERROR: ilastik is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).
```

**Comment by k-dominik** [comment]
Hi @phamtronglam,

if you are inside the ilastik folder already, you should do `pip install --editable .`. Sorry, this is not very clear in the instructions. Please also make sure to do the same for `volumina`.

**Comment by phamtronglam** [comment]
Hi @k-dominik,

Thanks. Here is the error output with `pip install --editable ..`. Please help me check.


```
(ilastik) D:\tmp\ilastik-main\ilastik>pip install --editable ..
Obtaining file:///D:/tmp/ilastik-main
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... error
  error: subprocess-exited-with-error

  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      Traceback (most recent call last):
        File "D:\miniconda3_windows\envs\ilastik\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "D:\miniconda3_windows\envs\ilastik\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "D:\miniconda3_windows\envs\ilastik\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 132, in get_requires_for_build_editable
          return hook(config_settings)
        File "C:\Users\Z036650\AppData\Local\Temp\pip-build-env-jib_6bpd\overlay\Lib\site-packages\setuptools\build_meta.py", line 450, in get_requires_for_build_editable
          return self.get_requires_for_build_wheel(config_settings)
        File "C:\Users\Z036650\AppData\Local\Temp\pip-build-env-jib_6bpd\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\Z036650\AppData\Local\Temp\pip-build-env-jib_6bpd\overlay\Lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "C:\Users\Z036650\AppData\Local\Temp\pip-build-env-jib_6bpd\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 4, in <module>
        File "C:\Users\Z036650\AppData\Local\Temp\pip-build-env-jib_6bpd\overlay\Lib\site-packages\setuptools_scm\__init__.py", line 148, in get_version
          _version_missing(config)
        File "C:\Users\Z036650\AppData\Local\Temp\pip-build-env-jib_6bpd\overlay\Lib\site-packages\setuptools_scm\__init__.py", line 108, in _version_missing
          raise LookupError(
      LookupError: setuptools-scm was unable to detect version for D:\tmp\ilastik-main.

      Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

      For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

I don't know if this is relevant, but I downloaded ilastik source code using github web GUI as zip file (screenshot below).
![image](https://github.com/ilastik/ilastik/assets/70121060/ab9cf1d1-150e-403b-848e-c7108991a619)

**Comment by k-dominik** [comment]
Hello @phamtronglam,

now I see. When doing "download zip" you get only the code without the history (and importantly, the tags that help `setuptools_scm` determine the version. I would really recommend to follow [our setup instructions](https://github.com/ilastik/ilastik/blob/main/CONTRIBUTING.md#development-environment). Namely, forking the repositories, and cloning those forks.

<details>
<summary><i>Alternatively</i> If you don't want to rely on the github cli tools, you can also do it manually (using github cli is probably the easiest though).</summary>

1. in [ilastik](https://github.com/ilastik/ilastik), and [volumina](https://github.com/ilastik/volumina), click the "fork" button:
  ![image](https://github.com/ilastik/ilastik/assets/24434157/0eee4deb-f7ea-404f-9368-4c3941f67fb0)
2. Then clone the repositories from the command line with `git clone https://github.com/phamtronglam/ilastik` and `git clone https://github.com/phamtronglam/volumina`
3. set up the upstream in each of the repository to point to our organization:
   ```bash
   cd ilastik
   git remote add upstream https://github.com/ilastik/ilastik
   git branch main -u upstream/main
   cd ..
   cd volumina
   git remote add upstream https://github.com/ilastik/volumina
   git branch main -u upstream/main
   # with that you can always get the current main branch from us by:
   git checkout main
   git pull --rebase
   ```

and _then_ you can do the environment creation with final `pip install --editable .` in each of the two folders.

</details>

Hope this helps
Cheers
Dominik

**Comment by phamtronglam** [comment]
Wow, that's a lot of steps for a non-developer beginner.

Thanks a lot. NOW I could run ilastik from code.

To my surprise, following the instructions in [setup instructions](https://github.com/ilastik/ilastik/blob/main/CONTRIBUTING.md#development-environment), the error about setuptools_scm did not appear.
It seems that this error was due to my frst attempt not following the official instructions.

In addition, now I see that the guide for setting up the environment is already included in the README file, at the CONTRIBUTING section. 

I'm sorry for not checking carefully from the beginning.

My conclusion is that this issue was originally solved if I had read carefully README file and followed the corresoponding instructions.

I'm closing this issue now without any PR.

Thank you very much for your time and I'm embarrassed.
Thank you for developing and maintaining such a good tool.

Bests,
Lam
