### ISSUE TITLE
Changing label drawing color preserved during active sessing between projects

### ISSUE THREAD

**Issue by k-dominik** [ilastik/ilastik#2728]
## Describe the bug
When changing the label _drawing_ color in project `A`, closing the project, and creating a new project `B`, the label corresponding to the changed index in project `A` will have the same color in project `B`.

## Expected behavior
Project color changes should not be preserved between projects

## To Reproduce
1) Create a pixel classification project, change one of the label _drawing_ colors.
2) Close the project
3) Create a new project and go to training -> label color (for _drawing and probability_ display) is changed there, too

## Desktop (please complete the following information):
 - ilastik version: `1.4.0`, `1.4.1b6`
 - OS: all

**Comment by btbest** [comment]
Even better: I reproduced this by selecting a new "Color for drawing", but left the "Color for probability display" untouched. In the new project, it took over my custom "Color for drawing" also as the "Color for probability display".
