### ISSUE TITLE
What is the best way to segment densely-spaced cells? 

### ISSUE THREAD

**Issue by alexlenail** [ilastik/ilastik#2749]
I have images of densely-spaced cells, which the Pixel Classification workflow does a rather good job of assigning. Unfortunately, the segmentations in Ilastik (both "simple" and "hysteresis') are relatively naive. 

Have people found good ways of segmenting probability maps coming out of Ilastik? Something that doesn't require thresholding (and hence doesn't throw away information), and can search for objects with a particular shape (round) and size range? 

Ideally it would be possible to load this segmentation back into ilastik for object classification (which is super useful). 

For the ilastik developers: this is a feature request to include a better segmentation directly in ilastik. (Maybe integration with Meta's SegmentAnything would be a quick way to accomplish this?)

**Comment by alexlenail** [comment]
<img width="600" alt="image" src="https://github.com/ilastik/ilastik/assets/2761597/7f387215-03c1-4edc-a79c-89fec09cc074">

**Comment by k-dominik** [comment]
Hi @alexlenail,

in terms of better segmentation routines directly - working on it ;). There is already integration of pretrained neural networks [from the bioimage model zoo](https://bioimage.io/#/?partner=ilastik) in the [neural network classification workflow](https://www.ilastik.org/documentation/nn/nn). But I don't think there is currently a network there that will match your data.

One thing I would try from the probability maps (assuming your objects are _roundish_) is running them through [stardist](https://github.com/stardist/stardist). There is a fiji plugin, so it might be relatively low effort to try it out.

The results you can take back into object classification. Note, that there, for dense scenes like yours, you might want to hide the "binary image" layer (try the object identity layer to see the individual cells).

Hope this helps
Cheers
D
