### ISSUE TITLE
unbounded/less bounded size filters for Object Classification from Pixel Prediction Map

### ISSUE THREAD

**Issue by oanegros** [ilastik/ilastik#2778]
Currently the size filters in the Object Classification from Pixel Prediction Map pipeline have bounds, where they could be less bounded, for example the minimum size maxes out at 100.000; shouldnt the only bounds these have be min < max && min >= 0 ?
<img width="319" alt="Screenshot 2023-11-29 at 11 03 56" src="https://github.com/ilastik/ilastik/assets/42999309/f1c37a13-645a-4565-a6ae-d4797f674cbc">

**Comment by btbest** [comment]
The [commit](https://github.com/ilastik/ilastik/commit/87379a1384a3fca9b6375933425b311d8c9b627f) that introduced the 100000 max doesn't mention any reason. I'm guessing this was just a good-enough value chosen to avoid having to implement logic coupling one spinner's limit to the other spinner's value.

Choosing a min > max doesn't actually seem to cause any problems (besides obviously leading to nothing passing the filter), so we could just remove the max on the spinner altogether...

Looks like it's only a GUI limit btw, so one could still choose any value by manually tweaking the .ilp :grin:
