### ISSUE TITLE
Unable to do Batch Processing with Trainable Domain Adaptation workflow.

### ISSUE THREAD

**Issue by daviddaytw** [ilastik/ilastik#2789]
## Describe the bug

Unable to do Batch Processing with Trainable Domain Adaptation workflow to perform the predictions.

## Expected behavior

Perform predictions on selected images.

## To Reproduce
Within the Trainable Domain Adaptation workflow
1. Add some 2D data in the data selection applet.
2. Go to the Features applet and select some features.
3. Go to the Training applet, enable a model (I used https://bioimage.io/#/?id=10.5281%2Fzenodo.5764892), and make some annotations.
4. Go to the Batch Processing applet and select some images with same shape.
5. Click on Process all files.

## Error message/traceback

```pytb
ERROR 2024-01-02 00:20:40,548 request 347037 140134708143872 Traceback (most recent call last):
  File "/home/wday/ilastik-1.4.1b13-gpu-Linux/lib/python3.9/site-packages/lazyflow/request/request.py", line 383, in _execute
    self._result = self.fn()
  File "/home/wday/ilastik-1.4.1b13-gpu-Linux/lib/python3.9/site-packages/lazyflow/request/request.py", line 883, in __call__
    return self.func(*totalargs, **self.kwargs)
  File "/home/wday/ilastik-1.4.1b13-gpu-Linux/lib/python3.9/site-packages/lazyflow/slot.py", line 869, in __call__
    result_op = self.operator.call_execute(self.slot.top_level_slot, self.slot.subindex, self.roi, destination)
  File "/home/wday/ilastik-1.4.1b13-gpu-Linux/lib/python3.9/site-packages/lazyflow/operator.py", line 602, in call_execute
    return self.execute(slot, subindex, roi, result, **kwargs)
  File "/home/wday/ilastik-1.4.1b13-gpu-Linux/lib/python3.9/site-packages/lazyflow/operators/tiktorch/operators.py", line 244, in execute
    raise ValueError(
ValueError: The requested roi Subregion: start '[0, 480, 0]' stop '[480, 600, 2]' with halo [16 16  0] is too large for the session's valid shapes: {'input0': [(512, 512, 1)]}
```
Complete error log: [ilastik_log.txt](https://github.com/ilastik/ilastik/files/13806458/ilastik_log.txt)

## Screenshots

![image](https://github.com/ilastik/ilastik/assets/47077427/2cfe891c-94a2-4175-9541-7406be5ab73b)

## Desktop (please complete the following information):
 - ilastik version: 1.4.1b13
 - OS: Ubuntu 20.04.06

**Comment by k-dominik** [comment]
Hello @daviddaytw,

first of all, thank you very much for the report! And sorry you ran into this problem with batchprocessing with the trainable domain adaptation workflow (our latest addition). We'll have a look!

Cheers
Dominik

**Comment by k-dominik** [comment]
Hi @daviddaytw,

sorry for the delayed update. I looked into this and in general the batch processing works, also with this model. What catches my eye now in the error message you posted is the requested shape. It seems to have two channels for some reason. Could you please verify, that the data that you put in there, really has the same number of channels, too, as the training data?

Cheers
Dominik

**Comment by daviddaytw** [comment]
Hi Dominik,

Yes, I am sure that the data has the same number of channels.
One thing that I didn't mention is that in the data selection applet, I manually changed the axis from `zxy` to `cxy` for every image. I hope this information is helpful. I apologize that due to the privacy policy in my institution, I can not send some samples to test it out.

Best,
David

**Comment by k-dominik** [comment]
Hi @daviddaytw,

thank you for the update! I  tried with data that I generated myself, and changed the axisorder - batch still worked.

However, I came up with one more thing you could try to check: I could generate a  suspiciously similar error when having selected two labels in the training applet:

<img width="283" alt="image" src="https://github.com/ilastik/ilastik/assets/24434157/0f11a2c7-ca1e-401f-99e9-6eccc1bef0a6">


<details><summary>error-message</summary>

```python
ERROR 2024-02-16 09:18:13,284 request 59617 6210662400 Traceback (most recent call last):
  File "/Users/kutra/sources/ilastik-meta/ilastik/lazyflow/request/request.py", line 383, in _execute
    self._result = self.fn()
  File "/Users/kutra/sources/ilastik-meta/ilastik/lazyflow/request/request.py", line 883, in __call__
    return self.func(*totalargs, **self.kwargs)
  File "/Users/kutra/sources/ilastik-meta/ilastik/lazyflow/slot.py", line 869, in __call__
    result_op = self.operator.call_execute(self.slot.top_level_slot, self.slot.subindex, self.roi, destination)
  File "/Users/kutra/sources/ilastik-meta/ilastik/lazyflow/operator.py", line 602, in call_execute
    return self.execute(slot, subindex, roi, result, **kwargs)
  File "/Users/kutra/sources/ilastik-meta/ilastik/lazyflow/operators/tiktorch/operators.py", line 244, in execute
    raise ValueError(
ValueError: The requested roi Subregion: start '[0, 0, 0]' stop '[250, 250, 2]' with halo [16 16  0] is too large for the session's valid shapes: {'input0': [(512, 512, 1)]}
```

</details>

Cheers,
Dominik

**Comment by daviddaytw** [comment]
Hi Dominik,

Great! I believe this is the same issue I encountered. I selected two channels in the training applet because I thought it meant computing pixel classification based on multiple channels and could therefore increase the accuracy.

Best,
David

**Comment by daviddaytw** [comment]
Hi @k-dominik ,

Gotcha, thank you for your clarification. I guess the issue is closed then.

Best,
David

**Comment by k-dominik** [comment]
Alright, I'll close this (in the meantime there is #2813).
