### ISSUE TITLE
"Export all" button disabled after Batch Processing

### ISSUE THREAD

**Issue by k-dominik** [ilastik/ilastik#2811]
## Describe the bug
After batch processing, when going back to the export applet, the export all button is disabled. I verified this in 2 workflows (pixel classification and trainable domain adaptation) which makes me think this is a general issue.

## Expected behavior
The export all button should not be affected by  batch processing...

## To Reproduce
I assume in any workflow:
1. Add a file
2. Do whatever is necessary to enable export
3. Batch process a few files
4. go back to the export applet and observe 😢 

## Screenshots

<img width="304" alt="image" src="https://github.com/ilastik/ilastik/assets/24434157/69cb1671-9fb9-460a-815e-7b5a5a503de4">

## Desktop (please complete the following information):
 - ilastik version: 1.4.1b13
 - OS: tested on OSX, but I assume it affects all.

**Comment by btbest** [comment]
Reproduces in Windows
