### ISSUE TITLE
Save Project As does not add project to recent projects in ilastik splash screen

### ISSUE THREAD

**Issue by oanegros** [ilastik/ilastik#2830]
Just a slight annoyance, that if i 'Save Project As...' i wil have to look up this project in my file tree again. This also leads to me accidentally working in the wrong project as i select the most recent project, assuming this is where i left off.

 
Related, if people are looking into this: can we have a few more recent projects listed? Or even a scrollable list?

**Comment by k-dominik** [comment]
Thank you for the report @oanegros 

For the number of projects, it's currently hardcoded here:
https://github.com/ilastik/ilastik/blob/ed23825fba433680ff951d2624a8a5f8da3796b5/ilastik/shell/gui/ilastikShell.py#L1691
we could add a configuration key for the magic number "5" here...

For the save as:
yes, the list is currently only updated if project is loaded via "load project"... Also "save copy as" (which I would argue is the "snapshot" functionality in ilastik) doesn't update the list :/ It would be cool if that would actually be tracked in the project file (link to snapshot) or  something... but I'm digressing. Save-as should definitely trigger an update of the list!
