### ISSUE TITLE
WM_CLASS not set on X11

### ISSUE THREAD

**Issue by k-dominik** [ilastik/ilastik#2872]
This was brought to our attention by @sunyi000 and caused problems in abc(cba)desktop. In particular, clicking the task bar icon of ilastik would open a new instance instead of showing the existing window - pretty annoying. I don't think QApplications are supposed to be started with an empty argv.

**Comment by btbest** [comment]
True, the [docs](https://doc.qt.io/qt-5/qapplication.html#QApplication) are pretty explicit: `argv must contain at least one valid character string`
