### ISSUE TITLE
Can't open ilastik in Application (MacOS), error message "macOS cannot verify that this app is free from malware"

### ISSUE THREAD

**Issue by AliceAlmazan** [ilastik/ilastik#2926]
## Describe the bug
I was able to download ilastik and put it into Application on my Mac. However when I tried to open it, I got a pop-up warning saying "“ilastik-1.4.0.post1-OSX” cannot be opened because the developer cannot be verified", with two options: Move to Trash or Cancel. 

I then tried to open it from Privacy & Security with "Open Anyway" and I got the same pop-up warning. 

## Expected behavior
Open successfully on my MacOS

## To Reproduce
1. On your Mac, choose Apple menu  > System Settings, then click Privacy & Security  in the sidebar. 
2. Go to Security, then click Open.
3. Click Open Anyway. This button is available for about an hour after you try to open the app.
4. Enter your login password, then click OK.

## Error message/traceback

- “ilastik-1.4.0.post1-OSX” cannot be opened because the developer cannot be verified.
- macOS cannot verify that this app is free from malware.

## Screenshots
<img width="708" alt="Screenshot 2024-11-03 at 3 20 56 PM" src="https://github.com/user-attachments/assets/9df95599-608e-411f-9821-ceef4ffa8ded">

## Desktop (please complete the following information):
 - ilastik version: 1.4.0.post1-OSX
 - OS: MacOS Sonoma 14.7.1

**Comment by AliceAlmazan** [comment]
I tried the following trick and it worked for me now

Solution: 

1. Open terminal, type sudo spctl --global-disable or sudo spctl --master-disable
2. Enter login password
3. Type in “xattr -d com.apple.quarantine <file path>” and hit “Enter.” Make sure to replace <file path> with the app’s actual path. Simply drag the app from its folder directly into the Terminal window, and it will fill in the path for you.
4. For example, the full command with ilastik's file path is xattr -d com.apple.quarantine /Applications/ilastik-1.4.0.post1-OSX.app
5. Close Terminal and restart the Mac
6. Launch the app. 
7. Open terminal again and type sudo spctl --global-enable or sudo spctl --master-enable

**Comment by k-dominik** [comment]
Hello @AliceAlmazan,

Thank you for this detailed solution. I have to admit that this was never necessary for me. With the _second_ right-click open it will open for me after a fresh download.

Cheers, and thank you again!
