### ISSUE TITLE
GUI: pixel classification gui is draggable in KDE

### ISSUE THREAD

**Issue by burgerdev** [ilastik/ilastik#356]
OS: 
- Arch Linux 
- KDE 4.10.2-1
- Qt 4.8.4-16

Steps to reproduce:
- start pixel classification workfllow
- provide input
- select features
- go to training
- add label
- try to label 

Result: The window is being dragged while labeling.

Couldn't reproduce this with Unity 5.18.0 (Ubuntu 12.04, Qt 4.8.1-0ubuntu4.4) though.

---

**Workaround:**

The bug is related to the oxygen widget settings of KDE, and changing these settings is simple:

From a shell (or ALT-F2) run `oxygen-settings`, then choose _Widget Style_ on the left in the upcoming window. Under the tab _General_, look for _Windows' drag mode_ and set it to _Drag windows from titlebar only_.

**Comment by akreshuk** [comment]
Let's reopen this one if it hits again.
