### ISSUE TITLE
export surface meshes that are readable by blender 

### ISSUE THREAD

**Issue by FredHamprecht** [ilastik/ilastik#403]
as per Graham Knott's specifications

**Comment by stuarteberg** [comment]
Mesh extraction was overhauled in commits d6e2a3625ef63b8be3abfea146ee6a849918d8cd through 7cea800aadccfba202f6a95f55ccc0a1968f968e.  The exported meshes can be loaded in Blender.

**Comment by stuarteberg** [comment]
(I'm assuming this issue refers to the carving workflow.)
