### ISSUE TITLE
Layer property "adjust thresholds" should be a button next to the layer name

### ISSUE THREAD

**Issue by lfiaschi** [ilastik/ilastik#409]
The space near the layer name in the layerstack viewer  is unused empty space. Upon discussion with Behrnard: it can be useful to place small buttons for the "adjust_treshold" settings and the "export" settings. Right now, these are not intuitively placed in the right-click drop down menu of the layer.

**Comment by akreshuk** [comment]
This really depends on the layer name, some are much longer ("Segmentation for My Favorite Class"). I think right-click is intuitive enough, most users are trained to right-click by FIJI.
