### ISSUE TITLE
Pixel classification and Object counting: batch prediction terribly slow for many images

### ISSUE THREAD

**Issue by lfiaschi** [ilastik/ilastik#718]
Suppose that I want to batch processing 10 000 images with the pixel classification workflow or the object counting workflows:

Adding the list of images creates an opFeatureSelection for each image. This needs to be reconnected to the graph. Each connection ~0.5 second on my machine meaning that we have to wait around 5 000 sec (~2 hr) just for adding the images to be processed to the list .... (note that no computation was done yet)

**Comment by blaiseMibeck** [comment]
I am only using Ilastik for pixel classification.  I have not gotten headless to work -- and batch mode in the is difficult to use past 100 images or so (exactly how btekgit describes it). 

I was excited to see 1.1.5 come out -- it does seem faster but I still have the same problem with batch processing. Headless mode tries to start, but complains that cplex and gurobi are not found. 

Is there note I missed for how to setup headless mode with out these .dll files?

Thanks for any help you can provide. All the best!

**Comment by akreshuk** [comment]
cplex and gurobi error messages are irrelevant. The reason you are seeing them is that headless mode automatically runs in debug and there are more diagnostic "internal" errors (which we shouldn't be showing to begin with). So I guess headless mode does start for you, but it also needs a long start-up time, similar to batch processing.

**Comment by blaiseMibeck** [comment]
That is good to know -- I guess I give up too quickly :) 
Thanks!!

**Comment by stuarteberg** [comment]
Closing this old issue.  Was fixed at some point.
