### ISSUE TITLE
Collection of thoughts from user testing

### ISSUE THREAD

**Issue by thorbenk** [ilastik/ilastik#740]
Here follow some notes on the ilastik introduction / user testing from the Zeiss meeting in October 2013.
- Importer for [MRC](http://en.wikipedia.org/wiki/MRC_%28file_format%29)
  file format. To quote wikipedia:
  "MRC is a file format for electron density that has become industry standard in 
  Cryo-electron microscopy, where the result of the technique is a three-dimensional grid 
  of voxels each with a value corresponding to density of electrons"
- be able to interface with the
  [IMOD](http://en.wikipedia.org/wiki/IMOD_%28software%29) software, 
  "IMOD is an open-source, cross-platform suite of modeling, display and image 
  processing programs used for 3D reconstruction and modeling of microscopy images 
  with a special emphasis on electron microscopy data."
- in particular, it would be very useful to export the meshes of a segmentation
  produced in ilastik (e.g. via thresholding in the pixel classification workflow)
  for use in IMOD.
- for pixel classification to be more useful, we need to append the thresholding
  applet so that we can filter out small components. At the moment, when viewing
  a binarized prediction in an external 3D volume viewer, there are so many spurious
  pixels that the segmented structure is hard to see.
- in order to bring the interactive learning paradigm up to the stage of actual  
  segmentations (which is what users want to get out in the end):
  Let the user define a 3D region of interest (with a limited volume), for which the
  3D viewer then can show some volume rendering / meshes. Because of the limited
  volume, we should be able to stay interactive and allow the user to tweak
  the parameters of pixel classification until the end goal (segmentation) looks
  acceptable.
- github.ilastik.io would profit from tutorials that show how to interoperate with
  other software packages (like Fiji, Vaa3D, IMOD).

**Comment by akreshuk** [comment]
Individual issues opened for easier browsing/search.
