### ISSUE TITLE
CPLEX: Make sure the full version of CPLEX is installed, not the trial version

### ISSUE THREAD

**Issue by martinsch** [ilastik/ilastik#754]
If only the trial version is installed, the tracking workflow loads correctly, but later in optimization, it throws the error:

> The CPLEX Optimizers will solve problems up to 500 variables and 500 constraints.

We either have to make sure in the documentation that the users install the correct CPLEX version, or -- as a long-term solution -- check during tracking workflow import whether CPLEX can solve an easy problem with more than 500 variables... Maybe then set a flag in the ilastik config file, to not check it on every startup...

**Comment by candreasm** [comment]
Hi

Version 12.6 is hard to find. How can we obtain it? I have yet to get a response from IBM and the parts page is inactive. Please advise.

**Comment by k-dominik** [comment]
Hi @candreasm the current version of ilastik (1.3.3post2) was compiled with cplex 12.9 - so that's the one you should get.

**Comment by candreasm** [comment]
Hi 

Thanks for the prompt response in your website it says 12.6.


Sincerely, 

Chven Mitchell

Please excuse any typos or errors in spelling as I am replying/ emailing from my mobile. Thanks in advance

**Comment by k-dominik** [comment]
> Thanks for the prompt response in your website it says 12.6.

thank you for bringing that up. We corrected the docs.

**Comment by k-dominik** [comment]
This original issue should not be a problem anymore with @chaubold's solver
