### ISSUE TITLE
Export classifier for the cell profiler bridge

### ISSUE THREAD

**Issue by akreshuk** [ilastik/ilastik#770]
@czhci  says, that there are users asking for it, so we should bring it back.

**Comment by nickholway** [comment]
I'd like to use a model created in Ilastik 1.x in CellProfiler; was this functionality ever reimplemented?

If not it'd be really useful if it could be re-added please.

**Comment by LeeKamentsky** [comment]
We haven't yet added 1.0 to our build (but it's planned). Christoph Sommer has added [a module](https://github.com/CellProfiler/CellProfiler/blob/master/cellprofiler/modules/ilastik_pixel_classification.py#L232) to CellProfiler and it reads the classifier from the project.

**Comment by stuarteberg** [comment]
@LeeKamentsky, Thanks for pointing that out.  The function you linked to will work with the current released version, but I recently made some changes that would break it in our next release.  (The API it uses had been stable for ~2 years, but we need to change it now.)

I'd be happy to update the function to use our new API (should just be a few line changes).  I may need pointers on setting up a development environment for CellProfiler.

**Comment by stuarteberg** [comment]
BTW, a note about dependencies (mostly for my own reference): ilastik 1.1.x requires at least the following to perform pixel classification:

- vigra
- h5py
- psutil
- greenlet
- faulthandler

In theory the following additional dependencies shouldn't really be needed in the CellProfiler use-case, but I'll probably have to comb over our code and make sure no modules are requiring them unconditionally.  (Up until now, we've never needed to minimize our non-optional dependencies.)

- tifffile
- scikit-learn
- scikit-image
- jsonschema
- nose
- yapsy
- boost (for vigra)
- libpng, libtiff, libjpeg, etc. (for vigra)

**Comment by stuarteberg** [comment]
@LeeKamentsky @sommerc, In general, the idea of integrating the (increasingly heavy) dependencies into the CellProfiler build gives me the heebie-jeebies.  There would be no need for such integration if CellProfiler were able to use a separately downloaded copy of the ilastik binary.  But for that to work, CellProfiler would need to do one of the following:

- Use ilastik's command-line interface, which requires writing input files to disk and reading the output predictions from disk.
- If hitting the hard disk is unacceptable, we could cook up a simple client/server API for ilastik pixel classification.  That would be pretty easy to implement.

**Comment by stuarteberg** [comment]
BTW, one of the benefits to using either of the approaches mentioned above is that CellProfiler would be relying on an explicitly stable API, which we would strive to maintain backwards compatibility with.

**Comment by LeeKamentsky** [comment]
Our long-term direction is likely to be web services and I think that solves a lot of these "build the world" issues. At this point, about all I'm ready to do is to put the message out there that we should start discussing a community standard for bioimaging web services (see https://github.com/imagej/imagej-server/issues/1), but in time, it would be fantastic if you could build an application using arbitrary algorithms that consumed and provided images and derived data via uniform web interfaces.

**Comment by k-dominik** [comment]
closing this, there is CP interop via the predict module.
