### ISSUE TITLE
Pixel Classification with user-supplied binary background mask

### ISSUE THREAD

**Issue by christophdecker** [ilastik/ilastik#780]
For a huge amount of tasks it could in my opinion be beneficial, if the user could provide a binary background mask where all pixels which definitely belong to the background are set to zero and not taken into account for pixel classification. 

This could speed up computation a lot (if you either approximately know where your object/region of interest is or if you have data with non-rectangular shape e.g. cells in a round dish) and might also positively affect precision.

Implementation-wise I'm thinking of an (optional) input slot, where the user may supply a binary mask of the same shape as the data. If this mask is supplied, the pixels with mask value zero are not considered in feature computation, training and prediction.

Thoughts?

**Comment by stuarteberg** [comment]
This was implemented in c0755a6fe96cf2bfdf76ec3ca1886b67d3e38fd2 for debug mode, and now finally enabled in non-debug mode via 17d72b5bfeda45e0136e6a18cff172fb14b9577e.
