### ISSUE TITLE
Cannot change (or disable all) feature selection without raw data after changing from single 2D file to stack of 2D files

### ISSUE THREAD

**Issue by hanslovsky** [ilastik/ilastik#819]
Switching from a single 2D image input to a stack of 2D images as input with an additional spatial dimension is not possible if features have already been selected and ilastik needs to be restarted.

I do not know, if this is really a bug, because selecting features (and train) for a 2D image should not be followed by 3D analysis. However, ilastik should not become malfunctioning on user input (restart required).

This is how you get there:

Pixel Classification -> Input Data -> Add New -> Add seperate image(s) -> select single 2D image -> Feature Selection -> Select Features -> select all -> Input Data -> Remove previously added data -> Add New -> Add a single 3D/4D Volume from Stack -> select Files (stack of 2d images) and open -> Warning Message:

"Dataset Needs Correction
Can't use default properties for dataset:

/home/phanslov/Downloads/ilastik_test/test_data/pixel-classification/same_type_and_size/c_cells_1.png
...
/home/phanslov/Downloads/ilastik_test/test_data/pixel-classification/same_type_and_size/c_cells_3.png

because it violates a constraint of the Feature Selection applet.

Some of your selected feature scales are too large for your dataset.
Choose smaller scales (sigma) or use a larger dataset.
The invalid scales are: [1, 1.6, 3.5, 5.0, 10.0]

Please enter valid dataset properties to continue."

-> OK -> Dataset Properties window pops up -> setting axes to txyc works fine, however if we select three spatial axes, e.g. zyxc or xyzc, the following error message pops up:

"Unacceptable Settings
Failed to apply your new settings to the workflow because they violate a constraint of the Feature Selection applet.

Some of your selected feature scales are too large for your dataset.
Choose smaller scales (sigma) or use a larger dataset.
The invalid scales are: [1, 1.6, 3.5, 5.0, 10.0]"

-> OK -> Cancel (in order to deselect features) -> Error Message:

"IndexError
list index out of range

 (Advanced information about this error may be found in the log file: /home/phanslov/.ilastik_log.txt)"

-> Feature Selection stays grayed out and the Add New Button in the Input data app is missing and a restart of ilastik is required.

**Comment by akreshuk** [comment]
This sequence of steps works now, no crash, no warning.
