### ISSUE TITLE
Error on blockwise object classification

### ISSUE THREAD

**Issue by fdiego** [ilastik/ilastik#820]
I got an error when I set up block size to 32 and halo also to 32. After running few seconds, I got this message. I have already saved the ilastik_log just in case. In the next comment, I will upload an screenhot of the console.

![errorblockwiseobjectclassification_computing_zoom_in_out](https://f.cloud.github.com/assets/6662998/2150062/d16d56d6-93fc-11e3-877c-b63ea5997dfb.png)

**Comment by stuarteberg** [comment]
This was fixed in 5643641f865bd200f9284e3372a2dd97258e8418
