### ISSUE TITLE
Crash when using Qt with debug symbols

### ISSUE THREAD

**Issue by buotex** [ilastik/ilastik#850]
When loading a project in ilastik, the following assert fails and will therefore crash the program when the qt library is build with debug settings:
ASSERT: "visual != -1" in file itemviews/qheaderview.cpp, line 1184

This is due to the following lines:
`self.horizontalHeader().setResizeMode(DatasetDetailedInfoColumn.Nickname, QHeaderView.Interactive)
self.horizontalHeader().setResizeMode(DatasetDetailedInfoColumn.Location, QHeaderView.Interactive)
self.horizontalHeader().setResizeMode(DatasetDetailedInfoColumn.InternalID, QHeaderView.Interactive)
self.horizontalHeader().setResizeMode(DatasetDetailedInfoColumn.AxisOrder, QHeaderView.Interactive)`

in ilastik/applets/dataSelection/datasetDetailedInfoTableView.py

When removed, the error disappears, but it doesn't look as pretty.

Apparently this assert is optimized out in the Release build and therefore unlikely to be relevant to end users, but probably showcasing some racing condition problems.

**Comment by akreshuk** [comment]
Is it still a problem? @stuarteberg , can we close it?

**Comment by stuarteberg** [comment]
I have no idea.  I don't build Qt with debug symbols, and we don't have a conda package for it.  I'm not inclined to investigate.
