### ISSUE TITLE
VTK 6 seems to have removed QVTKWidget2

### ISSUE THREAD

**Issue by thorbenk** [ilastik/ilastik#855]
Quoting David Gobbi from below: "However, no one is maintaining the SIP wrappers anymore, so I do not know if they still work, and if they do, I do not know if they work with PySide."
http://www.vtk.org/pipermail/vtkusers/2013-November/082045.html
http://www.vtk.org/pipermail/vtkusers/2013-November/082047.html

Also see:
http://www.vtk.org/Wiki/VTK/Examples/Python/Widgets/EmbedPyQt
http://www.vtk.org/Wiki/VTK/Examples/Python/Widgets/EmbedPyQt2

In addition, some functions (`SetInput` in particular) were renamed, requiring a version check.
More on these breaking changes can be found at
http://www.vtk.org/Wiki/VTK/VTK_6_Migration/Replacement_of_SetInput

**Comment by stuarteberg** [comment]
I did some investigation of this issue recently.  Although the `QVTKWidget2` source code is still included in the VTK repository, don't be fooled: The sip bindings for that widget are definitely broken, and my trivial attempts at fixing them did not work.  I don't even know if the C++ version still works in VTK6.  

There is a widget in VTK6 named `QVTKRenderWindowInteractor` which **does** have Python binding support and might be a suitable replacement for `QVTKWidget2`, but I don't know VTK well enough to know for sure.  We need to investigate.

**Comment by k-dominik** [comment]
not using vtk anymore
