### ISSUE TITLE
Carving: Fetching labels from the labeling operator is too slow

### ISSUE THREAD

**Issue by thorbenk** [ilastik/ilastik#86]
The timing measurements on the lower left part of the ilastik window show that the labeling operator is by far the slowest. This makes scrolling through the volume not very pleasant, even for moderately sized blocks of 450^3

Estimated time to find a good solution: 2-5 days

**Comment by stuarteberg** [comment]
Labeling was sped up significantly by switching to `OpDenseLabelArray` via 312326257086475d3a3ac4a98adde2a45d21829d
