### ISSUE TITLE
Do not assume channel is last

### ISSUE THREAD

**Issue by akreshuk** [ilastik/ilastik#867]
There are plenty of places in the code that assume channel to be the last axis. It used to be true, but now we allow users to change the axis order. Luckily, there is an assert, preventing them from putting channel as not last, but a) the wording in the resulting error message is not very clear to non-devs, b) one day we should just stop assuming this.

**Comment by stuarteberg** [comment]
>I have a similar issue here: Want to load a 4D dataset as xyzt, but it is loaded as xyzc and I cannot change the axis in the pixel classification workflow, since I would change from 4D to 5D.

In the current implementation of pixel classification, this works, as long as the user hasn't started labeling.  If the user has already started labeling, it will complain and forbid the action, but this is still a huge improvement over the original state of affairs described in this issue.
