### ISSUE TITLE
Read 4D tif files directly

### ISSUE THREAD

**Issue by martinsch** [ilastik/ilastik#887]
ImageJ/Fiji allows to save/read Hyperstacks, i.e. 4D images, directly as one tif file. Ilastik, however, reads them in as one 3D image, with the 4th dimension concatenated along the 3rd axis. If possible, we should directly read those images as 4D.

**Comment by akreshuk** [comment]
How are we doing this now with tifffile? Is it still an issue?

**Comment by k-dominik** [comment]
I think this should be now fixed (or at least this would be an issue with tifffile now :D). I have confirmed that loading single file 5D tiffs works.
