### ISSUE TITLE
Export what you see

### ISSUE THREAD

**Issue by martinsch** [ilastik/ilastik#914]
It would be a great enhancement if the user could export exactly what she sees in volumina, i.e. all layers stacked into one image (and the color maps applied). This would avoid cumbersome screenshots and one could easily export videos. 

Side note: When ColorMapImages are exported, we currently export the uint grayscale image. Instead, users might want to export the colored images, which could be accomplished using this feature suggested.

**Comment by stuarteberg** [comment]
This is implemented in ilastiik/volumina#155.  When it's merged, we can close this issue.
