### ISSUE TITLE
Label class list widget improvements

### ISSUE THREAD

**Issue by stuarteberg** [ilastik/ilastik#96]
Janelia users suggested:
- Respond to the del key for deleting labels
- Provide a context menu that includes "erase all" as an option.
- 'x' button disappears on windows in live mode

**Comment by akreshuk** [comment]
Right-clicking on the color, still displays "None" instead of the label name. Clear all is provided. "x" button should disappear in live mode. Del key is too ambiguous for a shortcut.

**Comment by k-dominik** [comment]
sorry for the cluttered references here ;) only the PR #1516 is relevant

**Comment by akreshuk** [comment]
Final point about label names when right-clicking on color solved in #1516
