### ISSUE TITLE
headless batch mode doesn't support alternate result selections

### ISSUE THREAD

**Issue by stuarteberg** [ilastik/ilastik#993]
In the GUI, the user can select which result he wants to export, e.g. "Probabilities", "Simple Segmentation", or "Uncertainty".  But headless mode only exports the first one.  Need to expand the headless interface to allow the user to select which one to export.

TODO: 

 - [ ] Notify user Van Thai Hoang when this feature is implemented. (See ilastik-user mailing list thread.)

**Comment by JosephKM** [comment]
documentation page for headless operation appears does not show this feature. Please advise on how to use it. Thank you!

**Comment by stuarteberg** [comment]
Good point.  I just pushed a line to our online documentation:

- `--export_source` The data to export.  See the dropdown list on the Data Export GUI for choices. (For example, in pixel classification try `--export_source="Simple Segmentation"`)
